---
title: "0_Functions_Calculate_Indices"
author: "yuki"
date: "2023-04-30"
output: html_document
---
# MC Reliability for Indice
```{r mcshr_rt, message=FALSE}
mcshr_rt <- function(list, nc, Target) {
  
  # Initialize the parallel backend
  registerDoParallel(nc)

  r_values <- foreach(j = 1:length(list), .packages = c("dplyr", "tidyr")) %dopar% {
    
    SPE_half_1 <- list[[j]][[1]] %>%
      dplyr::filter(., Matching == "Matching", ACC == "1") %>%
      dplyr::group_by(Subject, Session, Identity) %>%
      dplyr::summarise(mean_rt = mean(RT_ms)) %>%
      dplyr::ungroup() %>%
      tidyr::pivot_wider(names_from = Identity,
                         values_from = mean_rt) %>%
      dplyr::mutate(rt_1_SPE = Self - !!sym(Target)) %>%
      dplyr::select(rt_1_SPE)
    
    SPE_half_2 <- list[[j]][[2]] %>%
      dplyr::filter(., Matching == "Matching", ACC == "1") %>%
      dplyr::group_by(Subject, Session, Identity) %>%
      dplyr::summarise(mean_rt = mean(RT_ms)) %>%
      dplyr::ungroup() %>%
      tidyr::pivot_wider(names_from = Identity,
                         values_from = mean_rt) %>%
      dplyr::mutate(rt_1_SPE = Self - !!sym(Target)) %>%
      dplyr::select(rt_1_SPE)

    cor(SPE_half_1, SPE_half_2, method = "pearson")
  }
  
  # Stop the parallel backend
  stopImplicitCluster()

  # Calculate the mean of the Pearson correlation coefficients
  r_values_vector <- unlist(r_values)
  r <- mean(r_values_vector)
  CI <- quantile(r_values_vector, c(0.025, 0.975))

  values <- data.frame("Indece" = "RT", "r" = r, "LLCI" = CI[1], "ULCI" = CI[2])
  return(values)
}
```

```{r mcshr_acc, message=FALSE}
mcshr_acc <- function(list, nc, Target) {
  
  # Initialize the parallel backend
  registerDoParallel(nc)

  r_values <- foreach(j = 1:length(list), .packages = c("dplyr", "tidyr")) %dopar% {
    
    SPE_half_1 <- list[[j]][[1]] %>%
      dplyr::filter(.,Matching == "Matching") %>%   
      dplyr::group_by(Subject,Session,Identity)%>% 
      dplyr::summarise(acc = mean(ACC))%>% 
      dplyr::ungroup() %>% 
      tidyr::pivot_wider(names_from = Identity,
                         values_from = acc) %>%
      dplyr::mutate(acc_SPE = Self - !!sym(Target)) %>%
      dplyr::select(acc_SPE)
    
  SPE_half_2 <- list[[j]][[2]] %>%
      dplyr::filter(.,Matching == "Matching") %>%   
      dplyr::group_by(Subject,Session,Identity)%>% 
      dplyr::summarise(acc = mean(ACC))%>% 
      dplyr::ungroup() %>% 
      tidyr::pivot_wider(names_from = Identity,
                         values_from = acc) %>%
      dplyr::mutate(acc_SPE = Self - !!sym(Target)) %>%
      dplyr::select(acc_SPE)

    cor(SPE_half_1, SPE_half_2, method = "pearson")
  }
  
  # Stop the parallel backend
  stopImplicitCluster()

  # Calculate the mean of the Pearson correlation coefficients
  r_values_vector <- unlist(r_values)
  r <- mean(r_values_vector)
  CI <- quantile(r_values_vector, c(0.025, 0.975))

  values <- data.frame("Indece" = "ACC", "r" = r, "LLCI" = CI[1], "ULCI" = CI[2])
  return(values)
}
```

```{r mcshr_dp, message=FALSE}
mcshr_dp <- function(list, nc, Target) {
  
  # Initialize the parallel backend
  registerDoParallel(nc)

  r_values <- foreach(j = 1:length(list), .packages = c("dplyr", "tidyr")) %dopar% {
    
    SPE_half_1 <- list[[j]][[1]] %>%
    dplyr::group_by(Subject,Session,Identity) %>% 
    dplyr::summarise(
      hit = length(ACC[Matching == "Matching" & ACC == 1]),
      fa = length(ACC[Matching == "Nonmatching" & ACC == 0]),
      miss = length(ACC[Matching == "Matching" & ACC == 0]),
      cr = length(ACC[Matching == "Nonmatching" & ACC == 1]),
      Dprime = qnorm(
        ifelse(hit / (hit + miss) < 1,
               hit / (hit + miss),
               1 - 1 / (2 * (hit + miss))
              )
           ) - qnorm(
        ifelse(fa / (fa + cr) > 0,
               fa / (fa + cr),
               1 / (2 * (fa + cr))
              )
                    )) %>% 
    dplyr::ungroup() %>%
    select(-"hit",-"fa",-"miss",-"cr") %>%
    tidyr::pivot_wider(names_from = Identity,
                       values_from = Dprime) %>%
    dplyr::mutate(dprime_SPE = Self - !!sym(Target)) %>%
    dplyr::select(dprime_SPE)
    
  SPE_half_2 <- list[[j]][[2]] %>%
    dplyr::group_by(Subject,Session,Identity) %>% 
    dplyr::summarise(
      hit = length(ACC[Matching == "Matching" & ACC == 1]),
      fa = length(ACC[Matching == "Nonmatching" & ACC == 0]),
      miss = length(ACC[Matching == "Matching" & ACC == 0]),
      cr = length(ACC[Matching == "Nonmatching" & ACC == 1]),
      Dprime = qnorm(
        ifelse(hit / (hit + miss) < 1,
               hit / (hit + miss),
               1 - 1 / (2 * (hit + miss))
              )
           ) - qnorm(
        ifelse(fa / (fa + cr) > 0,
               fa / (fa + cr),
               1 / (2 * (fa + cr))
              )
                    )) %>% 
    dplyr::ungroup() %>%
    select(-"hit",-"fa",-"miss",-"cr") %>%
    tidyr::pivot_wider(names_from = Identity,
                       values_from = Dprime) %>%
    dplyr::mutate(dprime_SPE = Self - !!sym(Target)) %>%
    dplyr::select(dprime_SPE)

    cor(SPE_half_1, SPE_half_2, method = "pearson")
  }
  
  # Stop the parallel backend
  stopImplicitCluster()

  # Calculate the mean of the Pearson correlation coefficients
  r_values_vector <- unlist(r_values)
  r <- mean(r_values_vector)
  CI <- quantile(r_values_vector, c(0.025, 0.975))

  values <- data.frame("Indece" = "Dprime", "r" = r, "LLCI" = CI[1], "ULCI" = CI[2])
  return(values)
}
```

```{r mcshr_eff, message=FALSE}
mcshr_eff <- function(list, nc, Target) {
  
  # Initialize the parallel backend
  registerDoParallel(nc)

  r_values <- foreach(j = 1:length(list), .packages = c("dplyr", "tidyr")) %dopar% {
    
  SPE_half_1 <- list[[j]][[1]] %>%
    dplyr::group_by(Subject, Identity, Matching, Session) %>% 
    dplyr::summarise(Eff = mean(RT_ms)/mean(ACC))%>% 
    dplyr::ungroup() %>%
    tidyr::pivot_wider(names_from = Identity,
                       values_from = Eff) %>%
    dplyr::mutate(eff_SPE = Self - !!sym(Target)) %>%
    dplyr::select(eff_SPE)
    
  SPE_half_2 <- list[[j]][[2]] %>%
    dplyr::group_by(Subject, Identity, Matching, Session) %>% 
    dplyr::summarise(Eff = mean(RT_ms)/mean(ACC))%>% 
    dplyr::ungroup() %>%
    tidyr::pivot_wider(names_from = Identity,
                       values_from = Eff) %>%
    dplyr::mutate(eff_SPE = Self - !!sym(Target)) %>%
    dplyr::select(eff_SPE)

    cor(SPE_half_1, SPE_half_2, method = "pearson")
  }
  
  # Stop the parallel backend
  stopImplicitCluster()

  # Calculate the mean of the Pearson correlation coefficients
  r_values_vector <- unlist(r_values)
  r <- mean(r_values_vector)
  CI <- quantile(r_values_vector, c(0.025, 0.975))

  values <- data.frame("Indece" = "Efficiency", "r" = r, "LLCI" = CI[1], "ULCI" = CI[2])
  return(values)
}
```

```{r mcshr_ddmv, message=FALSE}
mcshr_ddmv <- function(list, nc, Target) {
  
  # Initialize the parallel backend
  registerDoParallel(nc)

  r_values <- foreach(j = 1:length(list), .packages = c("dplyr", "tidyr", "hausekeep")) %dopar% {
    
  SPE_half_1 <- list[[j]][[1]] %>%
    hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
    dplyr::select(Subject, Session, Matching, Identity, v) %>%
    dplyr::filter(Matching == "Matching") %>% 
    tidyr::pivot_wider(names_from = Identity,
                       values_from = v) %>%
    dplyr::mutate(v_SPE = Self - !!sym(Target)) %>%
    dplyr::select(v_SPE)
    
  SPE_half_2 <- list[[j]][[2]] %>%
    hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
    dplyr::select(Subject, Session, Matching, Identity, v) %>%
    dplyr::filter(Matching == "Matching") %>% 
    tidyr::pivot_wider(names_from = Identity,
                       values_from = v) %>%
    dplyr::mutate(v_SPE = Self - !!sym(Target)) %>%
    dplyr::select(v_SPE)

    cor(SPE_half_1, SPE_half_2, method = "pearson")
  }
  
  # Stop the parallel backend
  stopImplicitCluster()

  # Calculate the mean of the Pearson correlation coefficients
  r_values_vector <- unlist(r_values)
  r <- mean(r_values_vector)
  CI <- quantile(r_values_vector, c(0.025, 0.975))

  values <- data.frame("Indece" = "ezDDM: v", "r" = r, "LLCI" = CI[1], "ULCI" = CI[2])
  return(values)
}
```

```{r mcshr_ddmz, message=FALSE}
mcshr_ddmz <- function(list, nc, Target) {
  
  # Initialize the parallel backend
  registerDoParallel(nc)

  r_values <- foreach(j = 1:length(list), .packages = c("dplyr", "tidyr", "hausekeep")) %dopar% {
    
    SPE_half_1 <- list[[j]][[1]] %>%
      hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
      dplyr::mutate(., z = a/v) %>%
      dplyr::select(Subject, Session, Matching, Identity, z) %>%
      dplyr::filter(Matching == "Matching") %>% 
      tidyr::pivot_wider(names_from = Identity,
                         values_from = z) %>%
      dplyr::mutate(z_SPE = Self - !!sym(Target)) %>%
      dplyr::select(z_SPE)
    
  SPE_half_2 <- list[[j]][[2]] %>%
      hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
      dplyr::mutate(., z = a/v) %>%
      dplyr::select(Subject, Session, Matching, Identity, z) %>%
      dplyr::filter(Matching == "Matching") %>% 
      tidyr::pivot_wider(names_from = Identity,
                         values_from = z) %>%
      dplyr::mutate(z_SPE = Self - !!sym(Target)) %>%
      dplyr::select(z_SPE)

    cor(SPE_half_1, SPE_half_2, method = "pearson")
  }
  
  # Stop the parallel backend
  stopImplicitCluster()

  # Calculate the mean of the Pearson correlation coefficients
  r_values_vector <- unlist(r_values)
  r <- mean(r_values_vector)
  CI <- quantile(r_values_vector, c(0.025, 0.975))

  values <- data.frame("Indece" = "ezDDM: z", "r" = r, "LLCI" = CI[1], "ULCI" = CI[2])
  return(values)

}
```

```{r mcshr}
mcshr <- function(list, nc, indice, Target) {
  if (indice == "rt") {
    result <- mcshr_rt(list, nc, Target)
  } else if (indice == "acc") {
    result <- mcshr_acc(list, nc, Target)
  } else if (indice == "dp") {
    result <- mcshr_dp(list, nc, Target)
  } else if (indice == "eff") {
    result <- mcshr_eff(list, nc, Target)
  } else if (indice == "ddmv") {
    result <- mcshr_ddmv(list, nc, Target)
  } else if (indice == "ddmz") {
    result <- mcshr_ddmz(list, nc, Target)
  } else {
    stop("Invalid indice argument")
  }
  return(result)
}
```

# Other SHR functions
```{r shr_rt, message=FALSE}
shr_rt <- function(list, Target) {
  values <- data.frame(matrix(nrow = length(list), ncol = 3))
  for(j in 1:length(list)) {  
    SPE_half_1 <- list[[j]][[1]] %>%
      dplyr::filter(.,Matching == "Matching", ACC == "1") %>%
      dplyr::group_by(Subject, Session, Identity) %>%
      dplyr::summarise(mean_rt = mean(RT_ms)) %>%
      dplyr::ungroup() %>%
      tidyr::pivot_wider(names_from = Identity,
                         values_from = mean_rt) %>%
      dplyr::mutate(rt_1_SPE = Self - !!sym(Target)) %>%
      dplyr::select(rt_1_SPE)
    
    SPE_half_2 <- list[[j]][[2]] %>%
      dplyr::filter(.,Matching == "Matching", ACC == "1") %>%
      dplyr::group_by(Subject, Session, Identity) %>%
      dplyr::summarise(mean_rt = mean(RT_ms)) %>%
      dplyr::ungroup() %>%
      tidyr::pivot_wider(names_from = Identity,
                         values_from = mean_rt) %>%
      dplyr::mutate(rt_1_SPE = Self - !!sym(Target)) %>%
      dplyr::select(rt_1_SPE)
    
      r_value <- cor(SPE_half_1, SPE_half_2, method = "pearson")
      
    values[j,1] <- "RT"
    values[j,2] <- j
    values[j,3] <- r_value
  }
  return(values)
}
```

```{r shr_acc, message=FALSE}
shr_acc <- function(list, Target) {
  values <- data.frame(matrix(nrow = length(list), ncol = 3))
  for(j in 1:length(list)) {  
      SPE_half_1 <- list[[j]][[1]] %>%
        dplyr::filter(.,Matching == "Matching") %>%   
        dplyr::group_by(Subject,Session,Identity)%>% 
        dplyr::summarise(acc = mean(ACC))%>% 
        dplyr::ungroup() %>% 
        tidyr::pivot_wider(names_from = Identity,
                           values_from = acc) %>%
        dplyr::mutate(acc_SPE = Self - !!sym(Target)) %>%
        dplyr::select(acc_SPE)
    
    SPE_half_2 <- list[[j]][[2]] %>%
        dplyr::filter(.,Matching == "Matching") %>%   
        dplyr::group_by(Subject,Session,Identity)%>% 
        dplyr::summarise(acc = mean(ACC))%>% 
        dplyr::ungroup() %>% 
        tidyr::pivot_wider(names_from = Identity,
                           values_from = acc) %>%
        dplyr::mutate(acc_SPE = Self - !!sym(Target)) %>%
        dplyr::select(acc_SPE)
    
      r_value <- cor(SPE_half_1, SPE_half_2, method = "pearson")
      
    values[j,1] <- "ACC"
    values[j,2] <- j
    values[j,3] <- r_value
  }
  return(values)
}
```

```{r shr_dp, message=FALSE}
shr_dp <- function(list, Target) {
  values <- data.frame(matrix(nrow = length(list), ncol = 3))
  for(j in 1:length(list)) {  
    SPE_half_1 <- list[[j]][[1]] %>%
    dplyr::group_by(Subject,Session,Identity) %>% 
    dplyr::summarise(
      hit = length(ACC[Matching == "Matching" & ACC == 1]),
      fa = length(ACC[Matching == "Nonmatching" & ACC == 0]),
      miss = length(ACC[Matching == "Matching" & ACC == 0]),
      cr = length(ACC[Matching == "Nonmatching" & ACC == 1]),
      Dprime = qnorm(
        ifelse(hit / (hit + miss) < 1,
               hit / (hit + miss),
               1 - 1 / (2 * (hit + miss))
              )
           ) - qnorm(
        ifelse(fa / (fa + cr) > 0,
               fa / (fa + cr),
               1 / (2 * (fa + cr))
              )
                    )) %>% 
    dplyr::ungroup() %>%
    select(-"hit",-"fa",-"miss",-"cr") %>%
    tidyr::pivot_wider(names_from = Identity,
                       values_from = Dprime) %>%
    dplyr::mutate(dprime_SPE = Self - !!sym(Target)) %>%
    dplyr::select(dprime_SPE)
    
  SPE_half_2 <- list[[j]][[2]] %>%
    dplyr::group_by(Subject,Session,Identity) %>% 
    dplyr::summarise(
      hit = length(ACC[Matching == "Matching" & ACC == 1]),
      fa = length(ACC[Matching == "Nonmatching" & ACC == 0]),
      miss = length(ACC[Matching == "Matching" & ACC == 0]),
      cr = length(ACC[Matching == "Nonmatching" & ACC == 1]),
      Dprime = qnorm(
        ifelse(hit / (hit + miss) < 1,
               hit / (hit + miss),
               1 - 1 / (2 * (hit + miss))
              )
           ) - qnorm(
        ifelse(fa / (fa + cr) > 0,
               fa / (fa + cr),
               1 / (2 * (fa + cr))
              )
                    )) %>% 
    dplyr::ungroup() %>%
    select(-"hit",-"fa",-"miss",-"cr") %>%
    tidyr::pivot_wider(names_from = Identity,
                       values_from = Dprime) %>%
    dplyr::mutate(dprime_SPE = Self - !!sym(Target)) %>%
    dplyr::select(dprime_SPE)
    
    r_value <- cor(SPE_half_1, SPE_half_2, method = "pearson")

    values[j,1] <- "Dprime"
    values[j,2] <- j
    values[j,3] <- r_value
  }
  return(values)
}
```

```{r shr_eff, message=FALSE}
shr_eff <- function(list, Target) {
  values <- data.frame(matrix(nrow = length(list), ncol = 3))
  for(j in 1:length(list)) {  
      SPE_half_1 <- list[[j]][[1]] %>%
      dplyr::group_by(Subject, Identity, Matching, Session) %>% 
      dplyr::summarise(Eff = mean(RT_ms)/mean(ACC))%>% 
      dplyr::ungroup() %>%
      tidyr::pivot_wider(names_from = Identity,
                         values_from = Eff) %>%
      dplyr::mutate(eff_SPE = Self - !!sym(Target)) %>%
      dplyr::select(eff_SPE)
    
    SPE_half_2 <- list[[j]][[2]] %>%
      dplyr::group_by(Subject, Identity, Matching, Session) %>% 
      dplyr::summarise(Eff = mean(RT_ms)/mean(ACC))%>% 
      dplyr::ungroup() %>%
      tidyr::pivot_wider(names_from = Identity,
                         values_from = Eff) %>%
      dplyr::mutate(eff_SPE = Self - !!sym(Target)) %>%
      dplyr::select(eff_SPE)
    
      r_value <- cor(SPE_half_1, SPE_half_2, method = "pearson")

    values[j,1] <- "Efficiency"
    values[j,2] <- j
    values[j,3] <- r_value
  }
  return(values)
}
```

```{r shr_DDM: v, message=FALSE}
shr_ddmv <- function(list, Target) {
  values <- data.frame(matrix(nrow = length(list), ncol = 3))
  for(j in 1:length(list)) {  
    SPE_half_1 <- list[[j]][[1]] %>%
      hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
      dplyr::select(Subject, Session, Matching, Identity, v) %>%
      dplyr::filter(Matching == "Matching") %>% 
      tidyr::pivot_wider(names_from = Identity,
                         values_from = v) %>%
      dplyr::mutate(v_SPE = Self - !!sym(Target)) %>%
      dplyr::select(v_SPE)
    
    SPE_half_2 <- list[[j]][[2]] %>%
      hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
      dplyr::select(Subject, Session, Matching, Identity, v) %>%
      dplyr::filter(Matching == "Matching") %>% 
      tidyr::pivot_wider(names_from = Identity,
                         values_from = v) %>%
      dplyr::mutate(v_SPE = Self - !!sym(Target)) %>%
      dplyr::select(v_SPE)
    
      r_value <- cor(SPE_half_1, SPE_half_2, method = "pearson")

    values[j,1] <- "ezDDM: v"
    values[j,2] <- j
    values[j,3] <- r_value
  }
  return(values)
}
```

```{r shr_DDM: z, message=FALSE}
shr_ddmz <- function(list, Target) {
  values <- data.frame(matrix(nrow = length(list), ncol = 3))
  for(j in 1:length(list)) {  
    SPE_half_1 <- list[[j]][[1]] %>%
        hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
        dplyr::mutate(., z = a/v) %>%
        dplyr::select(Subject, Session, Matching, Identity, z) %>%
        dplyr::filter(Matching == "Matching") %>% 
        tidyr::pivot_wider(names_from = Identity,
                           values_from = z) %>%
        dplyr::mutate(z_SPE = Self - !!sym(Target)) %>%
        dplyr::select(z_SPE)
    
    SPE_half_2 <- list[[j]][[2]] %>%
        hausekeep::fit_ezddm(data = ., rts = "RT_sec", responses = "ACC", id = "Subject", group = c("Session", "Matching", "Identity")) %>%
        dplyr::mutate(., z = a/v) %>%
        dplyr::select(Subject, Session, Matching, Identity, z) %>%
        dplyr::filter(Matching == "Matching") %>% 
        tidyr::pivot_wider(names_from = Identity,
                           values_from = z) %>%
        dplyr::mutate(z_SPE = Self - !!sym(Target)) %>%
        dplyr::select(z_SPE)
    
      r_value <- cor(SPE_half_1, SPE_half_2, method = "pearson")

    values[j,1] <- "ezDDM: z"
    values[j,2] <- j
    values[j,3] <- r_value
  }
  return(values)
}
```

```{r shr}
shr <- function(list, indice, Target) {
  if (indice == "rt") {
    result <- shr_rt(list, Target)
  } else if (indice == "acc") {
    result <- shr_acc(list, Target)
  } else if (indice == "dp") {
    result <- shr_dp(list, Target)
  } else if (indice == "eff") {
    result <- shr_eff(list, Target)
  } else if (indice == "ddmv") {
    result <- shr_ddmv(list, Target)
  } else if (indice == "ddmz") {
    result <- shr_ddmz(list, Target)
  } else {
    stop("Invalid indice argument")
  }
  return(result)
}
```