---
title: "5_Plot"
author: "yuki"
date: "2023-04-30"
output: html_document
---
# Create NULL List
```{r Create NULL List}
plot <- list()
```

```{r Create NULL List}
df[[3]] <- list()
names(df)[3] <- "Plot"
```

# Palette
```{r Palette}
warm <- c("#C848B9", "#F962A7","#F3533A", "#FD836D","#FA9F42", "#FFBA69")
cold <- c("#057748", "#3D9A8B", "#2EB19F", "#5ACFC9", "#63C2D2", "#B7EDFF")
palette <- list(warm = warm, cold = cold)
rm(warm, cold)
```

# Plot SHR
```{r DataFrame for Plot NM SHR}
# Add a Column for Target
df.friend <- res[[1]][[1]] 
df.stranger <- res[[1]][[2]] 

# Rbind two Data Frame
df[[3]][[1]] <- rbind(df.friend, df.stranger) %>%
  dplyr::mutate(Indice = factor(Indice, levels = c("ezDDM: z", "ezDDM: v", "Efficiency", "Dprime", "ACC", "RT"))) 
names(df[[3]])[[1]] <- "Plot NM SHR"

# Clean Intermediate Variables
rm(df.friend, df.stranger)
```

```{r Plot SHR for Simulated Data, message= FALSE, warning = FALSE}
plot[[1]] <- list()
names(plot)[1] <- "First-Second, Odd-Even, Permuted"
```

```{r DataFrame for Plot MC SHR}
# Add a Column for Target
df.friend <- res[[2]][[1]] 
df.stranger <- res[[2]][[2]] 

# Rbind two Data Frame
df[[3]][[2]] <- rbind(df.friend, df.stranger) %>%
  dplyr::mutate(Indice = factor(Indice, levels = c("ezDDM: z", "ezDDM: v", "Efficiency", "Dprime", "ACC", "RT"))) 
names(df[[3]])[[2]] <- "Plot MC SHR"

# Clean Intermediate Variables
rm(df.friend, df.stranger)
```

```{r Plot SHR for Simulated Data, message= FALSE, warning = FALSE}
plot[[2]] <- ggplot(df[[3]][[2]], aes(x = Indice, y = r, color = interaction(Indice, Target))) +
  ggplot2::geom_errorbar(aes(ymin = LLCI, ymax = ULCI), width = 0.1, size = 2) +
  #geom_line() +
  ggplot2::geom_point(size = 5) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_y_continuous(limits = c(-0.2, 1), 
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1), 
                                                  labels = c("unacceptable", "poor","acceptable", "excellent")),
                              breaks = seq(0,1,by = 0.1)) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + #add dotted line
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position = "none",
                 text = element_text(size = 20),
                 axis.text.x = element_text(size = 20),
                 axis.text.y = element_text(size = 20),
                 axis.title = element_text(size = 25),
                 axis.title.x = element_text(margin = margin(t = 20)),
                 axis.title.y = element_text(margin = margin(t = 10)),
                 plot.margin = unit(c(1,1,1,1), "cm"),
                 panel.grid = element_blank(),#hide the line in background
                 strip.background = element_rect(color = "black", fill = "white", size = 1)
                 ) +
  ggplot2::labs(y = "Monte Carlo-based Split-Half Reliability", x = "Indices") +
  ggplot2::scale_color_manual(values = c(palette$warm, palette$cold)) + 
  ggplot2::facet_wrap(~Target, ncol = 2) 

names(plot)[2] <- "Monte Carlo"

ggsave(filename="../1_2_Planned_Analysis/1_2_2_OUTPUT/Fig4_SPE_SHR.png", width = 20, height = 10)
```

--------------------------------------------------------------------------------

## Plot ICC
```{r DataFrame for Plot ICC}
# Add a Column for Target
df.friend <- res[[3]][[1]] %>%
  dplyr::mutate(Target = "Friend")
df.stranger <- res[[3]][[2]] %>%
  dplyr::mutate(Target = "Stranger")

# Rbind two Data Frame
df[[3]][[3]] <- rbind(df.friend, df.stranger) %>%
  dplyr::mutate(ICC_type = factor(ICC_type, levels = c("ezDDM: z", "ezDDM: v", "Efficiency", "Dprime", "ACC", "RT"))) 
names(df[[3]])[[3]] <- "Plot ICC"

# Clean Intermediate Variables
rm(df.friend, df.stranger)
```

```{r Plot ICC, message= FALSE, warning = FALSE}
plot[[3]] <- ggplot2::ggplot(df[[3]][[3]], aes(x = ICC_type, y = ICC, color = interaction(ICC_type, Target))) +
  ggplot2::geom_errorbar(aes(ymin = LLCI, ymax = ULCI), width = 0.1, size = 2) +
  ggplot2::geom_point(size = 5) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.2, 1), 
                     sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1), 
                                             labels = c("unacceptable", "poor", "acceptable", "excellent")),
                                             breaks = seq(0,1,by = 0.1)) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + #add dotted line
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::theme_bw() +
  ggplot2::theme(text = element_text(size = 20),
                 axis.text.x = element_text(size = 20),
                 axis.text.y = element_text(size = 20),
                 axis.title = element_text(size = 25),
                 axis.title.x = element_text(margin = margin(t = 20)),
                 axis.title.y = element_text(margin = margin(t = 10)),
                 plot.title = element_text(size = 25),
                 plot.margin = unit(c(1,1,1,1), "cm"),
                 legend.key.size = unit(2, "cm"), 
                 legend.text = element_text(size = 20),
                 legend.title = element_blank(),
                 legend.position = "none",
                 panel.spacing = unit(4, "lines"),
                 panel.grid = element_blank(),#hide the line in background
                 strip.text = element_text(size = 20),
                 strip.background = element_rect(color="black", fill="white", size=1)
                 ) +
  ggplot2::labs(y = "Intraclass Correlation Coefficient", x = "Indices") +
  ggplot2::scale_color_manual(values = c(palette$warm, palette$cold)) + 
  ggplot2::facet_wrap(~ type + Target, ncol = 2) 

names(plot)[3] <- "ICC"

rm(plot.ICC_fake)

ggsave(filename="../1_2_Planned_Analysis/1_2_2_OUTPUT/Fig5_SPE_ICC.png", width = 20, height = 20, dpi = 300)
```