---
title: "Untitled"
author: "yuki"
date: "2023-05-31"
output: html_document
---
# Read Data from HDDM Generator
```{r}
raw <- read.csv("../DATA/data.csv") %>%
  dplyr::mutate(resprw = case_when(resp ==  1 ~  "upper",
                                   resp ==  -1 ~  "lower"),
                resp = case_when(resp ==  1 ~  1,
                                 resp ==  -1 ~  0),
                sub = 1,
                cnd = 1,
                )
# 创建一个空的列表
sml <- list()

# 获取数据框的round列中的唯一值
rounds <- unique(raw$round)

# 根据每个round的值进行拆分并存储到列表中
for (round_val in rounds) {
  subset_df <- raw[raw$round == round_val, ]  # 按照round值筛选子数据集
  sml[[as.character(round_val)]] <- subset_df  # 将子数据集存储到列表中
}
rm(subset_df)
```

```{r}
sml <- list()

for (i in 1:500) {
  # 构建文件名
  file_name <- paste0("../DATA/simulate/data", i, ".csv")
  
  # 读取 CSV 文件
  data <- read.csv(file_name) %>%
    dplyr::mutate(resprw = case_when(resp ==  1 ~  "upper",
                                     resp ==  -1 ~  "lower"),
                  resp = case_when(resp ==  1 ~  1,
                                   resp ==  -1 ~  0),
                  sub = 1,
                  cnd = 1,
                  )
  
  # 将数据添加到列表 sml
  sml <- append(sml, list(data))
}
rm(data)
```


```{r}
res_ddm <- list()
out_ddm <- list()
```

```{r, message=FALSE, include=FALSE, warning=FALSE}
start_time <- Sys.time()
for (i in 1:500) {
  res_ddm <- list()
    ##############################################################################
    # RWiener
    temp <- wdm(sml[[i]], yvar = c("q", "resprw"))
  
    result <- data.frame("RWiener",
                         temp$coefficients[1],
                         temp$coefficients[2],
                         temp$coefficients[3],
                         temp$coefficients[4])
    colnames(result) <- c("Package",
                          "a",
                          "t",
                          "z",
                          "v")
    rownames(result) <- NULL
  
    res_ddm[[1]] <- result
    names(res_ddm)[1] <- "RWiener"
    rm(temp, result)
    # RWiener
    ##############################################################################
  
    ##############################################################################
    # FastDMinR, method = "ks"
    temp <- FastDMinR::fast_dm(data = sml[[i]],            
                           Subject = "sub",
                           Conditions = "cnd",
                           TIME = "q",
                           RESPONSE = "resp",
                           precision = 5.0,
                           method = "ks",
                           fix_to = list(p = 0, d = 0, sv = 0, st0 = 0, szr = 0),
                           depend_on_condition = list(a = "cnd"),
                           invariant = c("zr", "v", "t0"))
    result <- data.frame("FastDMinR_ks",
                         temp$indiv_estimates[3],
                         temp$indiv_estimates[5],
                         temp$indiv_estimates[2],
                         temp$indiv_estimates[4])
    colnames(result) <- c("Package",
                          "a",
                          "t",
                          "z",
                          "v")
    
    res_ddm[[2]] <- result
    names(res_ddm)[2] <- "FastDMinR, method = ks"
    rm(temp, result)
    # FastDMinR, method = "ks"
    ##############################################################################

    ##############################################################################
    # FastDMinR, method = "ml"
    temp <- FastDMinR::fast_dm(data = sml[[i]],            
                           Subject = "sub",
                           Conditions = "cnd",
                           TIME = "q",
                           RESPONSE = "resp",
                           precision = 5.0,
                           method = "ml",
                           fix_to = list(p = 0, d = 0, sv = 0, st0 = 0, szr = 0),
                           depend_on_condition = list(a = "cnd"),
                           invariant = c("zr", "v", "t0"))
    result <- data.frame("FastDMinR_ml",
                         temp$indiv_estimates[3],
                         temp$indiv_estimates[5],
                         temp$indiv_estimates[2],
                         temp$indiv_estimates[4])
    colnames(result) <- c("Package",
                          "a",
                          "t",
                          "z",
                          "v")
    
    res_ddm[[3]] <- result
    names(res_ddm)[3] <- "FastDMinR, method = ml"
    rm(temp, result)
    # FastDMinR, method = "ml"
    ##############################################################################
   
    ##############################################################################
    # FastDMinR, method = "cs"
    temp <- FastDMinR::fast_dm(data = sml[[i]],            
                           Subject = "sub",
                           Conditions = "cnd",
                           TIME = "q",
                           RESPONSE = "resp",
                           precision = 5.0,
                           method = "cs",
                           fix_to = list(p = 0, d = 0, sv = 0, st0 = 0, szr = 0),
                           depend_on_condition = list(a = "cnd"),
                           invariant = c("zr", "v", "t0"))
    result <- data.frame("FastDMinR_cs",
                         temp$indiv_estimates[3],
                         temp$indiv_estimates[5],
                         temp$indiv_estimates[2],
                         temp$indiv_estimates[4])
    colnames(result) <- c("Package",
                          "a",
                          "t",
                          "z",
                          "v")
    
    res_ddm[[4]] <- result
    names(res_ddm)[4] <- "FastDMinR, method = cs"
    rm(temp, result)
    # FastDMinR, method = "cs"
    ##############################################################################  
    
    ##############################################################################  
    # hausekeep, fit_ezddm
    temp <- hausekeep::fit_ezddm(data = sml[[i]],
                                 rts = "q",
                                 responses = "resp") %>%
    dplyr::mutate(Package = "hausekeep",
                  z = a / 2,
                  t = t0_Ter) %>%
    dplyr::select(Package,
                  a,
                  t,
                  z,
                  v)
  
    res_ddm[[5]] <- temp
    names(res_ddm)[5] <- "hausekeep::fit_ezddm"
    rm(temp)
    # hausekeep, fit_ezddm
    ##############################################################################  
  
  out_ddm[[i]] <- do.call(rbind, res_ddm) 
  names(out_ddm)[i] <- i
}
end_time <- Sys.time()
```
# Plot
```{r}
plot <- do.call(rbind, Map(cbind, round = names(out_ddm), out_ddm)) %>%
  dplyr::mutate(
    # hausekeep和其他包的结果有数量级上的差异，故修正一下
    a = ifelse(Package == "hausekeep", a * 10, a),
    z = ifelse(Package == "hausekeep", z * 10, z),
    v = ifelse(Package == "hausekeep", v * 10, v),
  ) %>%
  tidyr::pivot_longer(cols = c(a, t, z, v), names_to = "indice", values_to = "value") 
rownames(plot) <- NULL
```

```{r}
ggplot2::ggplot(aes(x = Package, y = value, fill = indice), data = plot) +
  ggplot2::geom_boxplot(width = 0.1, position = position_nudge(x = -0.05), alpha = 0.5, outlier.color = NA, color = "grey") + 
  ggdist::stat_halfeye(adjust = 0.2,justification = -0.05, alpha = 0.5, width = 0.5, .width = 0, point_colour = NA,) +
  ggdist::stat_dots(side = "left",justification = 1.15, alpha = 0.5,) + 
  ggplot2::coord_flip() +
  ggplot2::scale_y_continuous(limits = c(-0.5, 2.5),
                     sec.axis = sec_axis(~., breaks = c(0.3, 0.7, 1, 2),
                                             labels = c("t", "z", "v", "a")), # nolint
                                breaks = seq(0, 2, by = 0.5)
                                ) +
  ggplot2::geom_hline(yintercept = 0.3, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 2, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none") +
  ggplot2::facet_wrap(~indice, ncol = 2) 
ggsave("Pack_Com.png", width = 20, height = 10)
```

