---
title: "3_Reliability"
author: "yuki"
date: "2023-04-30"
output: html_document
---
# Create NULL List
```{r Create NULL List}
res <- list()
```

# First-Second, Odd-Even, Permuted
```{r Name Self - Friend}
res[[1]] <- list()
names(res)[1] <- "First-Second, Odd-Even, Permuted"
```

## Self - Friend
```{r RT, message=FALSE, warning=FALSE}
df.rt <- batch::shr(list = shl[1:3], indice = "rt", Target = "Friend", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.acc <-batch::shr(list = shl[1:3], indice = "acc", Target = "Friend", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.dp <- batch::shr(list = shl[1:3], indice = "dp", Target = "Friend", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.eff <- batch::shr(list = shl[1:3], indice = "eff", Target = "Friend", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.ddmv <- batch::shr(list = shl[1:3], indice = "ddmv", Target = "Friend", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.ddmz <- batch::shr(list = shl[1:3], indice = "ddmz", Target = "Friend", Paper_ID = "Simulated", mc = FALSE, nc = NULL)
```

```{r Rbind 6 Indices}
res[[1]][[1]] <- rbind(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
res[[1]][[1]] <- res[[1]][[1]] %>%
  dplyr::mutate(Indice = .$X1, Method = .$X2, r = .$X3, Target = .$V4, Paper_ID = .$V5) %>%
  dplyr::mutate(Method = case_when(Method == 1 ~ "First-Second", Method == 2 ~ "Odd-Even", Method == 3 ~ "Permuted")) %>%
  dplyr::select(Indice, Method, r, Target, Paper_ID)

rownames(res[[1]][[1]]) <- NULL
names(res[[1]])[1] <- "Self - Friend"
rm(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
```

```{r Save SHR.Other}
write.csv(res[[1]][[1]], "../1_2_Planned_Analysis/1_2_2_OUTPUT/Supplementary_Table_1.csv", row.names = FALSE)
```

## Self - Stranger
```{r RT, message=FALSE, warning=FALSE}
df.rt <- batch::shr(list = shl[1:3], indice = "rt", Target = "Stranger", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.acc <-batch::shr(list = shl[1:3], indice = "acc", Target = "Stranger", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.dp <- batch::shr(list = shl[1:3], indice = "dp", Target = "Stranger", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.eff <- batch::shr(list = shl[1:3], indice = "eff", Target = "Stranger", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.ddmv <- batch::shr(list = shl[1:3], indice = "ddmv", Target = "Stranger", Paper_ID = "Simulated", mc = FALSE, nc = NULL)

df.ddmz <- batch::shr(list = shl[1:3], indice = "ddmz", Target = "Stranger", Paper_ID = "Simulated", mc = FALSE, nc = NULL)
```

```{r Rbind 6 Indices}
res[[1]][[2]] <- rbind(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
res[[1]][[2]] <- res[[1]][[2]] %>%
  dplyr::mutate(Indice = .$X1, Method = .$X2, r = .$X3, Target = .$V4, Paper_ID = .$V5) %>%
  dplyr::mutate(Method = case_when(Method == 1 ~ "First-Second", Method == 2 ~ "Odd-Even", Method == 3 ~ "Permuted")) %>%
  dplyr::select(Indice, Method, r, Target, Paper_ID)

rownames(res[[1]][[2]]) <- NULL
names(res[[1]])[2] <- "Self - Stranger"
rm(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
```

```{r Save SHR.Other}
write.csv(res[[1]][[2]], "../1_2_Planned_Analysis/1_2_2_OUTPUT/Supplementary_Table_2.csv", row.names = FALSE)
```


# Monte Carlo
```{r Name Self - Friend}
res[[2]] <- list()
names(res)[2] <- "Monte Carlo"
```

## Self - Friend
```{r RT, message=FALSE, warning=FALSE}
df.rt <- batch::shr(list = shl[[4]], indice = "rt", Target = "Friend", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.acc <- batch::shr(list = shl[[4]], indice = "acc", Target = "Friend", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.dp <- batch::shr(list = shl[[4]], indice = "dp", Target = "Friend", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.eff <- batch::shr(list = shl[[4]], indice = "eff", Target = "Friend", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.ddmv <- batch::shr(list = shl[[4]], indice = "ddmv", Target = "Friend", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.ddmz <- batch::shr(list = shl[[4]], indice = "ddmz", Target = "Friend", Paper_ID = "Simulated", mc = TRUE, nc = 16)
```

```{r Rbind 6 Indices}
res[[2]][[1]] <- rbind(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
rownames(res[[2]][[1]]) <- NULL
names(res[[2]])[1] <- "Self - Friend"
rm(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
```

## Self - Stranger
```{r RT, message=FALSE, warning=FALSE}
df.rt <- batch::shr(list = shl[[4]], indice = "rt", Target = "Stranger", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.acc <- batch::shr(list = shl[[4]], indice = "acc", Target = "Stranger", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.dp <- batch::shr(list = shl[[4]], indice = "dp", Target = "Stranger", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.eff <- batch::shr(list = shl[[4]], indice = "eff", Target = "Stranger", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.ddmv <- batch::shr(list = shl[[4]], indice = "ddmv", Target = "Stranger", Paper_ID = "Simulated", mc = TRUE, nc = 16)

df.ddmz <- batch::shr(list = shl[[4]], indice = "ddmz", Target = "Stranger", Paper_ID = "Simulated", mc = TRUE, nc = 16)
```

```{r Rbind 6 Indices}
res[[2]][[2]] <- rbind(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
rownames(res[[2]][[2]]) <- NULL
names(res[[2]])[2] <- "Self - Stranger"
rm(df.rt, df.acc, df.dp, df.eff, df.ddmv, df.ddmz)
```

