---
title: "6_Description"
author: "yuki"
date: "2023-07-07"
output: html_document
---
```{r}
library(bruceR)
library(utils)
```

```{r}
desc <- list()
```

# Label
```{r}
desc[[1]] <- readxl::read_excel("./Label.xlsx") %>%
  dplyr::select(Paper_ID, Sample_Size = Remain, Trials, Author, Year, Exp)
names(desc)[1] <- "Label"
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# nmshr
```{r}
# Trial number of each df
trial_num <- list()
for (i in 1:18) {
  temp <- df[[i]] %>%
    dplyr::group_by(Subject, Matching, Identity, Session) %>%
    dplyr::summarise(n = n())

  trial_num[[i]] <- max(temp$n)
}
desc[[2]] <- trial_num
names(desc)[2] <- "Number of Trial"
rm(trial_num)

# Subject number of each df
sub_num <- list()
for (i in 1:18) {
  temp <- df[[i]] %>%
    dplyr::distinct(Subject) %>%
    dplyr::summarise(n = n())

  sub_num[[i]] <- max(temp$n)
}
desc[[3]] <- sub_num
names(desc)[3] <- "Number of Subject"
rm(sub_num)

rm(temp, i)
```

```{r}
desc[[4]] <- plot[[2]] %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::group_by(Target, Indice, Method) %>%
  dplyr::summarise(mean_r = mean(r),
                   sd_r = sd(r)) 
names(desc)[4] <- "nmshr Description"
```

```{r}
temp <- plot[[2]] %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::mutate(Target = factor(Target, levels = c("Close", "Stranger"))) %>%
  base::split(.$Indice) 

for (i in 1:length(temp)) {
  output <- utils::capture.output({
    bruceR::TTEST(data = temp[[i]],
                  x = "Target",
                  y = "r")
  })
  path <- paste0("./OUTPUT/TTEST/", names(temp[i]), ".md")
  writeLines(output, path)
}

rm(temp, i, path)
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# pershr
```{r}
desc[[5]] <- plot[[1]] %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::group_by(Target, Indice) %>%
  dplyr::summarise(mean_r = mean(r),
                   mean_LLCI = mean(LLCI),
                   mean_ULCI = mean(ULCI)) 
names(desc)[5] <- "mcshr Description"
```

```{r}
temp <- plot[[1]] %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::mutate(Target = factor(Target, levels = c("Close", "Stranger"))) %>%
  base::split(.$Indice) 

for (i in 1:length(temp)) {
  output <- utils::capture.output({
    bruceR::TTEST(data = temp[[i]],
                  x = "Target",
                  y = "r")
  })
  path <- paste0("./OUTPUT/TTEST/", names(temp[i]), ".md")
  writeLines(output, path)
}

rm(temp, i, path)
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# ICC
```{r}
desc[[6]] <- plot[[3]] 
names(desc)[6] <- "ICC Description"
```


################################################################################
--------------------------------------------------------------------------------
################################################################################

# Trials
```{r}
options(scipen = 999)
desc[[7]] <- plot[[1]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::mutate(Target = factor(Target, levels = c("Close", "Stranger"))) 

# 按照分组变量拆分数据集
grouped_data <- split(desc[[7]], list(desc[[7]]$Target, desc[[7]]$Indice))

# 创建一个空的向量来存储结果
r_8 <- vector("numeric", length(grouped_data))

# 对每个组进行回归分析
for (i in 1:length(grouped_data)) {
  grouped_data[[i]]
  
  # 计算回归方程
  regression <- lm(Trials ~ r, data = grouped_data[[i]])
  
  temp <- summary(regression)
  grouped_data[[i]]$r_p <- temp$coefficients[8]
  
  # 计算r = 0.8时的Trials值
  grouped_data[[i]]$r_8 <- predict(regression, data.frame(r = 0.8))
}

desc[[7]] <- do.call(rbind, grouped_data) 
rownames(desc[[7]]) <- NULL
names(desc)[7] <- "Regression predict Trials Number"
rm(grouped_data, r_8, i, regression, group)
```



################################################################################
--------------------------------------------------------------------------------
################################################################################

# Predict Trials
```{r}
desc[[8]] <- plot[[1]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID")

# 定义需要生成列的rate值范围
rate_values <- seq(0.1, 0.9, by = 0.1)

# 循环生成列
for (rate_value in rate_values) {
  column_name <- paste0("rate_", rate_value * 10)
  Needed_column_name <- paste0("Needed_", rate_value * 10)
  
  desc[[8]] <- desc[[8]] %>%
    dplyr::mutate(
      !!column_name := ((rate_value * r - rate_value) / (rate_value * r - r)),
      !!Needed_column_name := abs(!!sym(column_name) * Trials)
    )
}

rm(rate_value, rate_values, Needed_column_name, column_name)

desc[[8]] <- desc[[8]] %>%
  dplyr::select(
    Paper_ID, Target, Indice, r, Sample_Size, Trials, contains("Needed_")
  ) %>%
  tidyr::pivot_longer(
    cols = starts_with("Needed_"), names_to = "r_Expect", values_to = "Trial_Expect"
  ) %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "d Prime" ~ "d'",
      Indice == "Efficiency" ~ "η",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    r_Expect = case_when(
      r_Expect == "Needed_1" ~ 0.1,
      r_Expect == "Needed_2" ~ 0.2,
      r_Expect == "Needed_3" ~ 0.3,
      r_Expect == "Needed_4" ~ 0.4,
      r_Expect == "Needed_5" ~ 0.5,
      r_Expect == "Needed_6" ~ 0.6,
      r_Expect == "Needed_7" ~ 0.7,
      r_Expect == "Needed_8" ~ 0.8,
      r_Expect == "Needed_9" ~ 0.9,
    ),
  ) %>%
  dplyr::left_join(aggr[[1]], by = c("Target", "Indice")) %>%
  dplyr::mutate(
    r_round = round(r, 1),
    wtmr_round = round(wtmr, 1),
    Target = factor(
      Target,levels = c("Close", "Stranger")
    ),
    Indice = factor(
      Indice, 
      levels = c(
        "RT", "ACC", "d'", "η", "v(RWiener)", 
        "z(RWiener)", "v(hausekeep)", "z(hausekeep)"
      )
    )
  )
  

names(desc)[8] <- "Spearman-Brown"
```

