---
title: "Untitled"
author: "yuki"
date: "2024-03-14"
output: html_document
---
Step 1: 把正确率低于0.5的被试找出来
Step 2: 把正确率低的被试删掉, 重新写入csv
Step 3: 从"./DATA/df[n].csv"读取
Step 1: 再次检验是否还存在正确率低的被试

# Check ACC
```{r Step 1}
min_ACC_list <- list()

for (i in 1:26) {
  min_ACC <- df[[i]] %>%
    dplyr::group_by(Subject, Matching, Identity, Session) %>%
    #dplyr::group_by(Subject) %>%
    dplyr::summarise(mean_ACC = mean(ACC)) %>%
    dplyr::ungroup() %>%
    dplyr::filter(mean_ACC < 0.5) %>%
    dplyr::arrange(mean_ACC)
  
  min_ACC_list[[i]] <- min_ACC
  cat(
    "For df[[", i, "]], the min ACC is:",
    min(min_ACC$mean_ACC),
    "\n"
  )
}

rm(min_ACC, i)
```

```{r Step 2}
for (i in 1:length(df)) {
  filtered_df <- df[[i]] %>%
    dplyr::anti_join(min_ACC_list[[i]], by = "Subject") 
  
  df[[i]] <- filtered_df
  
  write.csv(
    x = filtered_df,
    file = paste0("./DATA/df_", i, ".csv"),
    row.names = FALSE
  )
}

rm(filtered_df, i)
```


```{r Step 3}
df <- list()
df[[1]] <- read.csv("./DATA/df_1.csv")
df[[2]] <- read.csv("./DATA/df_2.csv")
df[[3]] <- read.csv("./DATA/df_3.csv")
df[[4]] <- read.csv("./DATA/df_4.csv")
df[[5]] <- read.csv("./DATA/df_5.csv")
df[[6]] <- read.csv("./DATA/df_6.csv")
df[[7]] <- read.csv("./DATA/df_7.csv")
df[[8]] <- read.csv("./DATA/df_8.csv")
df[[9]] <- read.csv("./DATA/df_9.csv")
df[[10]] <- read.csv("./DATA/df_10.csv")
df[[11]] <- read.csv("./DATA/df_11.csv")
df[[12]] <- read.csv("./DATA/df_12.csv")
df[[13]] <- read.csv("./DATA/df_13.csv")
df[[14]] <- read.csv("./DATA/df_14.csv")
df[[15]] <- read.csv("./DATA/df_15.csv")
df[[16]] <- read.csv("./DATA/df_16.csv")
df[[17]] <- read.csv("./DATA/df_17.csv")
df[[18]] <- read.csv("./DATA/df_18.csv")
df[[19]] <- read.csv("./DATA/df_19.csv")
df[[20]] <- read.csv("./DATA/df_20.csv")
df[[21]] <- read.csv("./DATA/df_21.csv")
df[[22]] <- read.csv("./DATA/df_22.csv")
df[[23]] <- read.csv("./DATA/df_23.csv")
df[[24]] <- read.csv("./DATA/df_24.csv")
df[[25]] <- read.csv("./DATA/df_25.csv")
df[[26]] <- read.csv("./DATA/df_26.csv")
```



