---
title: "Untitled"
author: "yuki"
date: "2023-06-24"
output: html_document
---
```{r}
# Clean Data
library(tidyr)
library(dplyr)
# More efficient
library(data.table)
# for ICC
library(psych)
# for DDM
library(hausekeep) # EZ-DDM
library(RWiener) # RW-DDM
# Parallel Computing
library(foreach)
library(parallel)
library(iterators)
library(doParallel)
# My Packages
library(yukiSH)
library(yukiBP)
```

```{r List for Data Frame}
df <- list()
df[[1]] <- read.csv("./DATA/df_1.csv")
df[[2]] <- read.csv("./DATA/df_2.csv")
df[[3]] <- read.csv("./DATA/df_3.csv")
df[[4]] <- read.csv("./DATA/df_4.csv")
df[[5]] <- read.csv("./DATA/df_5.csv")
df[[6]] <- read.csv("./DATA/df_6.csv")
df[[7]] <- read.csv("./DATA/df_7.csv")
df[[8]] <- read.csv("./DATA/df_8.csv")
df[[9]] <- read.csv("./DATA/df_9.csv")
df[[10]] <- read.csv("./DATA/df_10.csv")
df[[11]] <- read.csv("./DATA/df_11.csv")
df[[12]] <- read.csv("./DATA/df_12.csv")
df[[13]] <- read.csv("./DATA/df_13.csv")
df[[14]] <- read.csv("./DATA/df_14.csv")
df[[15]] <- read.csv("./DATA/df_15.csv")
df[[16]] <- read.csv("./DATA/df_16.csv")
df[[17]] <- read.csv("./DATA/df_17.csv")
df[[18]] <- read.csv("./DATA/df_18.csv")
```

```{r List for Paper ID}
p <- list()
p[[1]] <- "P0E1"
p[[2]] <- "P6E1"
p[[3]] <- "P46E2"
p[[4]] <- "P51E1"
p[[5]] <- "P51E2"
p[[6]] <- "P54E1"
p[[7]] <- "P54E3"
p[[8]] <- "Pn4E1"
p[[9]] <- "Pn13E1"
p[[10]] <- "Pn13E3"
p[[11]] <- "Pn13E4"
p[[12]] <- "Pn16E1"
p[[13]] <- "Pn16E2"
p[[14]] <- "Pn16E3"
p[[15]] <- "Pn23E1"
p[[16]] <- "P95E1"
p[[17]] <- "P95E2"
p[[18]] <- "Ps1E1"
```

```{r List for Target}
t <- list()
t[[1]] <- c("Self", "Friend", "Stranger")
t[[2]] <- c("Self", "Partner", "Stranger")
t[[3]] <- c("Self", "Stranger")
t[[4]] <- c("Self", "Celebrity", "Stranger")
t[[5]] <- c("Self", "Celebrity")
t[[6]] <- c("Self", "Mother","none", "Acquaintance")
t[[7]] <- c("Self", "Mother", "Acquaintance")
t[[8]] <- c("Self", "Friend", "Stranger")
t[[9]] <- c("Self", "Friend", "Stranger")
t[[10]] <- c("Self", "Father", "Stranger")
t[[11]] <- c("Self", "Friend", "Stranger")
t[[12]] <- c("Self", "Friend")
t[[13]] <- c("Self", "Friend")
t[[14]] <- c("Self", "Friend")
t[[15]] <- c("Self", "Friend", "Stranger")
t[[16]] <- c("Self", "Friend", "Stranger")
t[[17]] <- c("Self", "Friend", "Stranger")
t[[18]] <- c("Self", "Stranger")
```

```{r lazy_nmshr}
lazy_nmshr <- function(Target, Paper_ID, nc) {

  # 计算8个参数的分半信度 
  df_rt <- yukiBP::shr(list = shl[1:3], Target = Target, Paper_ID = Paper_ID, Indice = "rt", mc = FALSE, nc = nc)
  df_acc <- yukiBP::shr(list = shl[1:3], Target = Target, Paper_ID = Paper_ID, Indice = "acc", mc = FALSE, nc = nc)
  df_dp <- yukiBP::shr(list = shl[1:3], Target = Target, Paper_ID = Paper_ID, Indice = "dp", mc = FALSE, nc = nc)
  df_eff <- yukiBP::shr(list = shl[1:3], Target = Target, Paper_ID = Paper_ID, Indice = "eff", mc = FALSE, nc = nc)
  df_ezddm <- yukiBP::shr(list = shl[1:3], Target = Target, Paper_ID = Paper_ID, Indice = "ezddm", mc = FALSE, nc = nc)
  df_rwddm <- yukiBP::shr(list = shl[1:3], Target = Target, Paper_ID = Paper_ID, Indice = "rwddm", mc = FALSE, nc = nc)

  # 合并8个参数到一个表格内
  result <- rbind(df_rt, df_acc, df_dp, df_eff, df_ezddm, df_rwddm) %>%
    dplyr::mutate(Indice = case_when(Indice == "rt" ~ "RT",
                                     Indice == "acc" ~ "ACC",
                                     Indice == "dp" ~ "d Prime",
                                     Indice == "eff" ~ "Efficiency",
                                     Indice == "ez_v" ~ "ezDDM v",
                                     Indice == "ez_z" ~ "ezDDM z",
                                     Indice == "rw_v" ~ "rwDDM v",
                                     Indice == "rw_z" ~ "rwDDM z",)
                  ) %>%
    dplyr::mutate(Indice = factor(Indice, levels = c("RT", "ACC", "d Prime", "Efficiency", "ezDDM v", "ezDDM z", "rwDDM v", "rwDDM z")),
                  Method = factor(Method, levels = c("First-Second", "Odd-Even", "Permuted")),
                  Target = factor(Target),
                  ) %>%
    dplyr::select(Target, Indice, Method, r, Paper_ID) %>%
    dplyr::arrange(Target, Indice, Method)
  
  # 保存生成的表格
  Path <- paste0("./nmshr_", Paper_ID, ".csv")
  write.csv(x = result, file = Path, row.names = FALSE)

}
```

```{r lazy_mcshr}
lazy_mcshr <- function(Target, Paper_ID, nc) {

  # 计算8个参数的分半信度 
  df_rt <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "rt", mc = TRUE, nc = nc)
  df_acc <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "acc", mc = TRUE, nc = nc)
  df_dp <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "dp", mc = TRUE, nc = nc)
  df_eff <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "eff", mc = TRUE, nc = nc)
  df_ezddm <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "ezddm", mc = TRUE, nc = nc)
  df_rwddm <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "rwddm", mc = TRUE, nc = nc)

  # 合并8个参数到一个表格内
  result <- rbind(df_rt, df_acc, df_dp, df_eff, df_ezddm, df_rwddm) %>%
    dplyr::mutate(Indice = case_when(Indice == "rt" ~ "RT",
                                     Indice == "acc" ~ "ACC",
                                     Indice == "dp" ~ "d Prime",
                                     Indice == "eff" ~ "Efficiency",
                                     Indice == "ez_v" ~ "ezDDM v",
                                     Indice == "ez_z" ~ "ezDDM z",
                                     Indice == "rw_v" ~ "rwDDM v",
                                     Indice == "rw_z" ~ "rwDDM z",)
                  ) %>%
    dplyr::mutate(Indice = factor(Indice, levels = c("RT", "ACC", "d Prime", "Efficiency", "ezDDM v", "ezDDM z", "rwDDM v", "rwDDM z")),
                  Target = factor(Target),
                  ) %>%
    dplyr::select(Target, Indice, r, LLCI, ULCI, Paper_ID) %>%
    dplyr::arrange(Target, Indice)

  # 保存生成的表格
  Path <- paste0("./mcshr_", Paper_ID, ".csv")
  write.csv(x = result, file = Path, row.names = FALSE)

}
```

```{r}
for (i in 4) {
  shl <- list(list(), list(), list(), list())
  
  gc()
  
  # First-Second
  shl[[1]] <- yukiSH::sh_tool(df.split = df[[i]], method = "fs",
                              sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session")
  # Odd-Even
  shl[[2]] <- yukiSH::sh_tool(df.split = df[[i]], method = "od",
                              sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session")
  # Permuted
  shl[[3]] <- yukiSH::sh_tool(df.split = df[[i]], method = "permuted",
                              sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session")
  # Monte Carlo
  shl[[4]] <- yukiSH::sh_tool(df.split = df[[i]], method = "mc",
                              sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session",
                              iteration = 5000, nc = 10)
  
  #lazy_mnshr(Target = t[[i]], Paper_ID = p[[i]], nc = 10)
  lazy_mcshr(Target = t[[i]], Paper_ID = p[[i]], nc = 10)
}
```




