---
title: "8_Meta"
author: "yuki"
date: "2023-08-24"
output: html_document
---
# Meta Analysis

```{r}
raw_meta <- list()
for (i in 1:44) {
  raw_meta[[i]] <- list()
}
```

```{r, message=FALSE}
for (i in 1:44) {
  raw_meta[[i]][[1]] <-yukiBP::df(df = df[[i]], i = i, Indice = "rt")
  raw_meta[[i]][[2]] <-yukiBP::df(df = df[[i]], i = i, Indice = "acc")
  raw_meta[[i]][[3]] <-yukiBP::df(df = df[[i]], i = i, Indice = "dp")
  raw_meta[[i]][[4]] <-yukiBP::df(df = df[[i]], i = i, Indice = "eta")
  raw_meta[[i]][[5]] <-yukiBP::df(df = df[[i]], i = i, Indice = "ezddm")
  raw_meta[[i]][[6]] <-yukiBP::df(df = df[[i]], i = i, Indice = "rwddm")
  
  raw_meta[[i]] <- base::Reduce(
    function(x, y)
      left_join(x, y, by = c("Identity", "Paper_ID")),
    raw_meta[[i]]
  )
}

raw_meta <- bind_rows(raw_meta)
```

```{r Raw Meta Data}
df_meta <- list()
df_meta[[1]] <- raw_meta %>%
  dplyr::filter(
    # 被认为是在原范式上有较大修改(4 session 4 mood)
    !(Paper_ID %in% c("P51E1", "P44E1", "Ps2E1")) 
  ) 

#rm(raw_meta)
names(df_meta)[1] <- "Raw Meta Data"
```

```{r Convert Identity to STD}
df_meta[[2]] <- df_meta[[1]] %>%
  dplyr::mutate(
    Identity = case_when(
      Identity == "Self" ~ "Self",
      Identity == "Friend" ~ "Close",
      Identity == "Partner" ~ "Close",
      Identity == "Mother" ~ "Close",
      Identity == "Father" ~ "Close",
      Identity == "Acquaintance" ~ "Stranger",
      Identity == "Stranger" ~ "Stranger",
      Identity == "Celebrity" ~ "Celebrity",
      Identity == "None" ~ "NonPerson",
    )
  ) %>%
  dplyr::rename(
    ez_v_mean = v_mean.x,
    ez_v_sd = v_sd.x,
    ez_z_mean = z_mean.x,
    ez_z_sd = z_sd.x,
    rw_v_mean = v_mean.y,
    rw_v_sd = v_sd.y,
    rw_z_mean = z_mean.y,
    rw_z_sd = z_sd.y,
  )

names(df_meta)[2] <- "Convert Identity to STD"
```

################################################################################
--------------------------------------------------------------------------------
################################################################################

## Close & Stranger
```{r Self - Close}
df_meta[[3]] <- df_meta[[2]] %>%
  dplyr::filter(
    Identity %in% c("Self", "Close")
  ) %>%
  tidyr::pivot_wider(
    id_cols = Paper_ID,
    names_from = Identity,
    values_from = c(
      RT_mean, RT_sd,
      ACC_mean, ACC_sd,
      d_mean, d_sd,
      eta_mean, eta_sd,
      ez_v_mean , ez_v_sd,
      ez_z_mean, ez_z_sd,
      rw_v_mean, rw_v_sd,
      rw_z_mean, rw_z_sd,
    ),
    names_glue = "{.value}_{Identity}"
  ) %>%
  tidyr::drop_na(
    
  ) %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    ri = 0.7
  )

names(df_meta)[3] <- "Self - Close"
```

```{r Self - Stranger}
df_meta[[4]] <- df_meta[[2]] %>%
  dplyr::filter(
    Identity %in% c("Self", "Stranger")
  ) %>%
  tidyr::pivot_wider(
    id_cols = Paper_ID,
    names_from = Identity,
    values_from = c(
      RT_mean, RT_sd,
      ACC_mean, ACC_sd,
      d_mean, d_sd,
      eta_mean, eta_sd,
      ez_v_mean , ez_v_sd,
      ez_z_mean, ez_z_sd,
      rw_v_mean, rw_v_sd,
      rw_z_mean, rw_z_sd,
    ),
    names_glue = "{.value}_{Identity}"
  ) %>%
  tidyr::drop_na(
    
  ) %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    ri = 0.7
  )

names(df_meta)[4] <- "Self - Stranger"
```

```{r res_meta}
res_meta <- list(
  list(),
  list()
)

res_meta[[1]] <- list()
res_meta[[2]] <- list()

df_meta[[5]] <- list(
  list(),
  list()
)
```

## Close

```{r}
res_meta[[1]][[1]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = RT_mean_Self,
  m2i = RT_mean_Close,
  sd1i = RT_sd_Self,
  sd2i = RT_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "RT",
    Target = "Close"
  )

names(res_meta[[1]])[1] <- "Meta for RT"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[1]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[1]][[1]])

df_meta[[5]][[1]][[1]] <- data.frame(
  Indice = "RT",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[2]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ACC_mean_Self,
  m2i = ACC_mean_Close,
  sd1i = ACC_sd_Self,
  sd2i = ACC_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "ACC",
    Target = "Close"
  )

names(res_meta[[1]])[2] <- "Meta for ACC"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[2]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[2]])

df_meta[[5]][[1]][[2]] <- data.frame(
  Indice = "ACC",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[3]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = d_mean_Self,
  m2i = d_mean_Close,
  sd1i = d_sd_Self,
  sd2i = d_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "d",
    Target = "Close"
  )

names(res_meta[[1]])[3] <- "Meta for d"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[3]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[3]])

df_meta[[5]][[1]][[3]] <- data.frame(
  Indice = "d",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[4]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = eta_mean_Self,
  m2i = eta_mean_Close,
  sd1i = eta_sd_Self,
  sd2i = eta_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "eta",
    Target = "Close"
  )

names(res_meta[[1]])[4] <- "Meta for eta"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[4]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[4]])

df_meta[[5]][[1]][[4]] <- data.frame(
  Indice = "eta",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[5]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_v_mean_Self,
  m2i = ez_v_mean_Close,
  sd1i = ez_v_sd_Self,
  sd2i = ez_v_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM v",
    Target = "Close"
  )

names(res_meta[[1]])[5] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[5]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[5]])

df_meta[[5]][[1]][[5]] <- data.frame(
  Indice = "ezDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[6]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_z_mean_Self,
  m2i = ez_z_mean_Close,
  sd1i = ez_z_sd_Self,
  sd2i = ez_z_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM z",
    Target = "Close"
  )

names(res_meta[[1]])[6] <- "Meta for ezDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[6]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[6]])

df_meta[[5]][[1]][[6]] <- data.frame(
  Indice = "ezDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[7]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_v_mean_Self,
  m2i = rw_v_mean_Close,
  sd1i = rw_v_sd_Self,
  sd2i = rw_v_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM v",
    Target = "Close"
  )

names(res_meta[[1]])[7] <- "Meta for rwDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[7]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[7]])

df_meta[[5]][[1]][[7]] <- data.frame(
  Indice = "rwDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[1]][[8]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_z_mean_Self,
  m2i = rw_z_mean_Close,
  sd1i = rw_z_sd_Self,
  sd2i = rw_z_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM z",
    Target = "Close"
  )

names(res_meta[[1]])[8] <- "Meta for rwDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[8]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[1]][[8]])

df_meta[[5]][[1]][[8]] <- data.frame(
  Indice = "rwDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

## Stranger
```{r}
res_meta[[2]][[1]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = RT_mean_Self,
  m2i = RT_mean_Stranger,
  sd1i = RT_sd_Self,
  sd2i = RT_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "RT",
    Target = "Stranger"
  )

names(res_meta[[2]])[1] <- "Meta for RT"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[1]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[1]])

df_meta[[5]][[2]][[1]] <- data.frame(
  Indice = "RT",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[2]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ACC_mean_Self,
  m2i = ACC_mean_Stranger,
  sd1i = ACC_sd_Self,
  sd2i = ACC_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "ACC",
    Target = "Stranger"
  )

names(res_meta[[2]])[2] <- "Meta for ACC"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[2]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[2]])

df_meta[[5]][[2]][[2]] <- data.frame(
  Indice = "ACC",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[3]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = d_mean_Self,
  m2i = d_mean_Stranger,
  sd1i = d_sd_Self,
  sd2i = d_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "d",
    Target = "Stranger"
  )

names(res_meta[[2]])[3] <- "Meta for d"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[3]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[3]])

df_meta[[5]][[2]][[3]] <- data.frame(
  Indice = "d",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[4]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = eta_mean_Self,
  m2i = eta_mean_Stranger,
  sd1i = eta_sd_Self,
  sd2i = eta_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "eta",
    Target = "Stranger"
  )

names(res_meta[[2]])[4] <- "Meta for eta"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[4]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[4]])

df_meta[[5]][[2]][[4]] <- data.frame(
  Indice = "eta",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[5]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_v_mean_Self,
  m2i = ez_v_mean_Stranger,
  sd1i = ez_v_sd_Self,
  sd2i = ez_v_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM v",
    Target = "Stranger"
  )

names(res_meta[[2]])[5] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[5]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[5]])

df_meta[[5]][[2]][[5]] <- data.frame(
  Indice = "eaDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[6]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_z_mean_Self,
  m2i = ez_z_mean_Stranger,
  sd1i = ez_z_sd_Self,
  sd2i = ez_z_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM z",
    Target = "Stranger"
  )

names(res_meta[[2]])[6] <- "Meta for z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[6]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[6]])

df_meta[[5]][[2]][[6]] <- data.frame(
  Indice = "eaDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[7]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_v_mean_Self,
  m2i = rw_v_mean_Stranger,
  sd1i = rw_v_sd_Self,
  sd2i = rw_v_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM v",
    Target = "Stranger"
  )

names(res_meta[[2]])[7] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[7]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[7]])

df_meta[[5]][[2]][[7]] <- data.frame(
  Indice = "rwDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[2]][[8]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_z_mean_Self,
  m2i = rw_z_mean_Stranger,
  sd1i = rw_z_sd_Self,
  sd2i = rw_z_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM z",
    Target = "Stranger"
  )

names(res_meta[[2]])[8] <- "Meta for rwDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[8]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[2]][[8]])

df_meta[[5]][[2]][[8]] <- data.frame(
  Indice = "rwDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```


################################################################################
--------------------------------------------------------------------------------
################################################################################

## Celebrity & NonPerson
```{r}
res_meta[[3]] <- list()
res_meta[[4]] <- list()
names(res_meta)[3] <- "Celebrity"
names(res_meta)[4] <- "NonPerson"
```

```{r}
df_meta[[9]] <- list(
  list(),
  list()
)
```


```{r}
df_meta[[7]] <- df_meta[[2]] %>%
  dplyr::filter(
    Identity %in% c("Self", "Celebrity")
  ) %>%
  tidyr::pivot_wider(
    id_cols = Paper_ID,
    names_from = Identity,
    values_from = c(
      RT_mean, RT_sd,
      ACC_mean, ACC_sd,
      d_mean, d_sd,
      eta_mean, eta_sd,
      ez_v_mean , ez_v_sd,
      ez_z_mean, ez_z_sd,
      rw_v_mean, rw_v_sd,
      rw_z_mean, rw_z_sd,
    ),
    names_glue = "{.value}_{Identity}"
  ) %>%
  tidyr::drop_na(
    
  ) %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  )

names(df_meta)[7] <- "Self - Celebrity"
```

```{r}
df_meta[[8]] <- df_meta[[2]] %>%
  dplyr::filter(
    Identity %in% c("Self", "NonPerson")
  ) %>%
  tidyr::pivot_wider(
    id_cols = Paper_ID,
    names_from = Identity,
    values_from = c(
      RT_mean, RT_sd,
      ACC_mean, ACC_sd,
      d_mean, d_sd,
      eta_mean, eta_sd,
      ez_v_mean , ez_v_sd,
      ez_z_mean, ez_z_sd,
      rw_v_mean, rw_v_sd,
      rw_z_mean, rw_z_sd,
    ),
    names_glue = "{.value}_{Identity}"
  ) %>%
  tidyr::drop_na(
    
  ) %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    ri = 0.7
  )

names(df_meta)[8] <- "Self - NonPerson"
```

## Celebrity
```{r}
res_meta[[3]][[1]] <- metafor::escalc(
  measure = "SMD", 
  m1i = RT_mean_Self,
  m2i = RT_mean_Celebrity,
  sd1i = RT_sd_Self,
  sd2i = RT_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "RT",
    Target = "Celebrity"
  )

names(res_meta[[3]])[1] <- "Meta for RT"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[1]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[1]])

df_meta[[9]][[1]][[1]] <- data.frame(
  Indice = "RT",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[2]] <- metafor::escalc(
  measure = "SMD", 
  m1i = ACC_mean_Self,
  m2i = ACC_mean_Celebrity,
  sd1i = ACC_sd_Self,
  sd2i = ACC_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "ACC",
    Target = "Celebrity"
  )

names(res_meta[[3]])[2] <- "Meta for ACC"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[2]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[2]])

df_meta[[9]][[1]][[2]] <- data.frame(
  Indice = "ACC",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[3]] <- metafor::escalc(
  measure = "SMD", 
  m1i = d_mean_Self,
  m2i = d_mean_Celebrity,
  sd1i = d_sd_Self,
  sd2i = d_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "d",
    Target = "Celebrity"
  )

names(res_meta[[3]])[3] <- "Meta for d"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[3]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[3]])

df_meta[[9]][[1]][[3]] <- data.frame(
  Indice = "d",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[4]] <- metafor::escalc(
  measure = "SMD", 
  m1i = eta_mean_Self,
  m2i = eta_mean_Celebrity,
  sd1i = eta_sd_Self,
  sd2i = eta_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "eta",
    Target = "Celebrity"
  )

names(res_meta[[3]])[4] <- "Meta for eta"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[4]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[4]])

df_meta[[9]][[1]][[4]] <- data.frame(
  Indice = "eta",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[5]] <- metafor::escalc(
  measure = "SMD", 
  m1i = ez_v_mean_Self,
  m2i = ez_v_mean_Celebrity,
  sd1i = ez_v_sd_Self,
  sd2i = ez_v_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM v",
    Target = "Celebrity"
  )

names(res_meta[[3]])[5] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[5]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[5]])

df_meta[[9]][[1]][[5]] <- data.frame(
  Indice = "ezDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[6]] <- metafor::escalc(
  measure = "SMD", 
  m1i = ez_z_mean_Self,
  m2i = ez_z_mean_Celebrity,
  sd1i = ez_z_sd_Self,
  sd2i = ez_z_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM z",
    Target = "Celebrity"
  )

names(res_meta[[3]])[6] <- "Meta for ezDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[6]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[6]])

df_meta[[9]][[1]][[6]] <- data.frame(
  Indice = "ezDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[7]] <- metafor::escalc(
  measure = "SMD", 
  m1i = rw_v_mean_Self,
  m2i = rw_v_mean_Celebrity,
  sd1i = rw_v_sd_Self,
  sd2i = rw_v_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM v",
    Target = "Celebrity"
  )

names(res_meta[[3]])[7] <- "Meta for rwDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[7]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[7]])

df_meta[[9]][[1]][[7]] <- data.frame(
  Indice = "rwDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[3]][[8]] <- metafor::escalc(
  measure = "SMD", 
  m1i = rw_z_mean_Self,
  m2i = rw_z_mean_Celebrity,
  sd1i = rw_z_sd_Self,
  sd2i = rw_z_sd_Celebrity,
  n1i = Sample_Size,
  n2i = Sample_Size,
  data = df_meta[[7]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM z",
    Target = "Celebrity"
  )

names(res_meta[[3]])[8] <- "Meta for rwDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[3]][[8]])
)

smr <- metafor::rma(yi, vi, data = res_meta[[3]][[8]])

df_meta[[9]][[1]][[8]] <- data.frame(
  Indice = "rwDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```


## NonPerson
```{r}
res_meta[[4]][[1]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = RT_mean_Self,
  m2i = RT_mean_NonPerson,
  sd1i = RT_sd_Self,
  sd2i = RT_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "RT",
    Target = "NonPerson"
  )

names(res_meta[[4]])[1] <- "Meta for RT"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[1]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[1]])

df_meta[[9]][[2]][[1]] <- data.frame(
  Indice = "RT",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[2]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ACC_mean_Self,
  m2i = ACC_mean_NonPerson,
  sd1i = ACC_sd_Self,
  sd2i = ACC_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "ACC",
    Target = "NonPerson"
  )

names(res_meta[[4]])[2] <- "Meta for ACC"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[2]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[2]])

df_meta[[9]][[2]][[2]] <- data.frame(
  Indice = "ACC",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[3]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = d_mean_Self,
  m2i = d_mean_NonPerson,
  sd1i = d_sd_Self,
  sd2i = d_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "d",
    Target = "NonPerson"
  )

names(res_meta[[4]])[3] <- "Meta for d"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[3]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[3]])

df_meta[[9]][[2]][[3]] <- data.frame(
  Indice = "d",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[4]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = eta_mean_Self,
  m2i = eta_mean_NonPerson,
  sd1i = eta_sd_Self,
  sd2i = eta_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "eta",
    Target = "NonPerson"
  )

names(res_meta[[4]])[4] <- "Meta for eta"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[4]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[4]])

df_meta[[9]][[2]][[4]] <- data.frame(
  Indice = "eta",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[5]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_v_mean_Self,
  m2i = ez_v_mean_NonPerson,
  sd1i = ez_v_sd_Self,
  sd2i = ez_v_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM v",
    Target = "NonPerson"
  )

names(res_meta[[4]])[5] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[5]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[5]])

df_meta[[9]][[2]][[5]] <- data.frame(
  Indice = "ezDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[6]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_z_mean_Self,
  m2i = ez_z_mean_NonPerson,
  sd1i = ez_z_sd_Self,
  sd2i = ez_z_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM z",
    Target = "NonPerson"
  )

names(res_meta[[4]])[6] <- "Meta for ezDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[6]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[6]])

df_meta[[9]][[2]][[6]] <- data.frame(
  Indice = "ezDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[7]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_v_mean_Self,
  m2i = rw_v_mean_NonPerson,
  sd1i = rw_v_sd_Self,
  sd2i = rw_v_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM v",
    Target = "NonPerson"
  )

names(res_meta[[4]])[7] <- "Meta for rwDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[7]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[7]])

df_meta[[9]][[2]][[7]] <- data.frame(
  Indice = "rwDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```

```{r}
res_meta[[4]][[8]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_z_mean_Self,
  m2i = rw_z_mean_NonPerson,
  sd1i = rw_z_sd_Self,
  sd2i = rw_z_sd_NonPerson,
  ni = Trials,
  ri = ri,
  data = df_meta[[8]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM z",
    Target = "NonPerson"
  )

names(res_meta[[4]])[8] <- "Meta for rwDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[4]][[8]])
)
smr <- metafor::rma(yi, vi, data = res_meta[[4]][[8]])

df_meta[[9]][[2]][[8]] <- data.frame(
  Indice = "rwDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub,
  Q = smr$QE, p = smr$pval, I2 = smr$I2
)

smr

rm(prd, smr)
```



# Result
```{r}
df_meta[[6]] <- list(list(), list())

df_meta[[6]][[1]] <- dplyr::bind_rows(
  df_meta[[5]][[1]]
)

df_meta[[6]][[2]] <- dplyr::bind_rows(
  df_meta[[5]][[2]]
)


names(df_meta)[5] <- "Process of Meta Analysis"
names(df_meta)[6] <- "Result of Meta Analysis"

names(df_meta[[6]])[1] <- "Self - Close"
names(df_meta[[6]])[2] <- "Self - Stranger"

write.csv(x = df_meta[[6]][[1]], file = "./OUTPUT/meta/meta_close.csv")
write.csv(x = df_meta[[6]][[2]], file = "./OUTPUT/meta/meta_stranger.csv")
```

## for Close & Stranger
```{r}
res_meta[[3]] <- dplyr::bind_rows(
  res_meta[[1]]
) %>%
  dplyr::select(
    Target,
    Indice,
    Paper_ID,
    yi,
  ) %>%
  dplyr::left_join(
    desc[[1]],
    by = "Paper_ID"
  )

res_meta[[4]] <- dplyr::bind_rows(
  res_meta[[2]]
) %>%
  dplyr::select(
    Target,
    Indice,
    Paper_ID,
    yi,
  ) %>%
  dplyr::left_join(
    desc[[1]],
    by = "Paper_ID"
  )

write.csv(
  x = res_meta[[3]],
  file = "./OUTPUT/meta/meta_close_FEP.csv"
)
write.csv(
  x = res_meta[[4]],
  file = "./OUTPUT/meta/meta_stranger_FEP.csv"
)
```


## for Celebrity & NonPerson
# Result
```{r}
df_meta[[10]] <- list(list(), list())

df_meta[[10]][[1]] <- dplyr::bind_rows(
  df_meta[[9]][[1]]
)

df_meta[[10]][[2]] <- dplyr::bind_rows(
  df_meta[[9]][[2]]
)


names(df_meta)[9] <- "Process of Meta Analysis"
names(df_meta)[10] <- "Result of Meta Analysis"

names(df_meta[[10]])[1] <- "Self - Celebrity"
names(df_meta[[10]])[2] <- "Self - NonPerson"

write.csv(x = df_meta[[10]][[1]], file = "./OUTPUT/meta/meta_celebrity.csv")
write.csv(x = df_meta[[10]][[2]], file = "./OUTPUT/meta/meta_nonperson.csv")
```

