---
title: "5_Plot"
author: "yuki"
date: "2023-05-04"
output: html_document
---
# Create NULL List
```{r Create NULL List}
plot <- list()
meta <- list()
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# Normal SHR
```{r Read OUTPUT}
# 获取所有的nmshr
plot[[1]] <- list.files(file.path("./OUTPUT/nmshr/"),
                            pattern = "nmshr_.*\\.csv$",
                            ) %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x) read.csv(file.path("./OUTPUT/nmshr/", x), header = TRUE)) %>% # nolint
  # 对所有被read.table处理过的数据执行dplyr的清洗
  lapply(function(df) dplyr::filter(df, Indice != "Indice")) %>%
  bind_rows() %>%
  dplyr::mutate(Target = case_when(Target == "Friend" ~ "Close",
                                   Target == "Partner" ~ "Close",
                                   Target == "Mother" ~ "Close",
                                   Target == "Father" ~ "Close",
                                   Target == "Acquaintance" ~ "Stranger",
                                   Target == "Stranger" ~ "Stranger",
                                   Target == "Celebrity" ~ "Celebrity",
                                   Target == "none" ~ "NonPerson",
                                   )
                ) %>%
  dplyr::mutate(Target = factor(Target,
                                levels = c("Close", "Stranger", "Celebrity", "NonPerson"), # nolint
                                ),
                Indice = factor(Indice,
                                levels = c("rwDDM z", "rwDDM v", "ezDDM z", "ezDDM v", "Efficiency", "d Prime", "ACC", "RT") # nolint
                                )
                ) %>%
  dplyr::filter(!(Paper_ID %in% c("P51E1"))) 
names(plot)[1] <- "Normal SHR"
```

```{r}
meta[[1]] <- plot[[1]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(unique_ID = paste(Target, Indice, Method, sep="_")) %>%
  metafor::escalc(data = ., measure = "COR", ni = Trials, ri = r) %>%
  metafor::aggregate.escalc(x = ., cluster = unique_ID, rho = 0) %>%
  base::summary() %>%
  dplyr::select(Target, Indice, Method, yi, vi, sei, zi, pval, ci.lb, ci.ub) %>%
  dplyr::mutate(pval = ifelse(pval < 0.001, "<.001", 
                       ifelse(pval < 0.05, sprintf("%.3f", pval), sprintf("%.2f", pval)))) %>% 
  dplyr::mutate(yi_r = round(yi, 2),
                ci.lb = round(ci.lb, 2),
                ci.ub = round(ci.ub, 2)) %>%
  dplyr::mutate(CI = paste(yi_r, "(", ci.lb, ", ", ci.ub, ")", sep = ""))  %>% # 得到CI
  dplyr::mutate(.,
                Indice = case_when(Indice == "Efficiency" ~ "η",
                                   Indice == "d Prime" ~ "d'",
                                   #Indice == "rwDDM v" ~ "v",
                                   #Indice == "rwDDM z" ~ "z",
                                   Indice == "rwDDM v" ~ "v(RWiener)",
                                   Indice == "rwDDM z" ~ "z(RWiener)",
                                   Indice == "ezDDM v" ~ "v(hausekeep)",
                                   Indice == "ezDDM z" ~ "z(hausekeep)",
                                   TRUE ~ Indice),
                Target_Indice = paste(Target, Indice, sep = "_"), 
                Target_Indice = factor(Target_Indice)
                ) 
                
names(meta)[1] <- "Normal SHR"
```

```{r}
p1 <- meta[[1]] %>%
  dplyr::filter(Method == "First-Second") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), size = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-1, 1),
                              breaks = c(-1, 0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p2 <- meta[[1]] %>%
  dplyr::filter(Method == "Odd-Even") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), size = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-1, 1),
                              breaks = c(-1, 0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p3 <- meta[[1]] %>%
  dplyr::filter(Method == "Permuted") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), size = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-1, 1),
                              breaks = c(-1, 0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p <- p1 + p2 + p3 + plot_layout(ncol = 1, guides = 'collect')

ggsave(plot = p,
       filename = "./FIGURE/Fig1_meta_nmshr.png",
       width = 9,
       height = 20,
       )
ggsave(plot = p1,
       filename = "./FIGURE/Fig1_meta_fs.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p2,
       filename = "./FIGURE/Fig1_meta_od.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p3,
       filename = "./FIGURE/Fig1_meta_per.png",
       width = 10,
       height = 8,
       )

rm(p, p1, p2, p3)
```


```{r Plot nmshr, warning=FALSE}
ggplot2::ggplot(plot[[1]],aes(x = Indice, y = r, fill = interaction(Indice, Target))) + 
  ggplot2::geom_boxplot(width = 0.1, position = position_nudge(x = -0.05), color = "grey", alpha = 0.5, outlier.color = NA,) +  
  see::geom_violinhalf(color = "grey", alpha = 0.5, position = position_nudge(x = 0.1)) + 
  ggdist::stat_dots(side = "left", justification = 1.2, alpha = 0.5) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_y_continuous(limits = c(-0.1, 1.1),
                              breaks = c(0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::labs(y = "", x = "") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none") +
  ggplot2::facet_wrap(~Target + Method, ncol = 3)

ggsave(filename = "./FIGURE/Fig1_nmshr.png",
       width = 20,
       height = 20,
       )
```





################################################################################
--------------------------------------------------------------------------------
################################################################################


# Monte Carlo SHR
```{r Read OUTPUT}
# 获取所有的mcshr
plot[[2]] <- list.files(file.path("./OUTPUT/mcshr_5k/"),
                        pattern = "mcshr_.*\\.csv$",
                        ) %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x) read.csv(file.path("./OUTPUT/mcshr_5k/", x), header = TRUE)) %>% # nolint
  # 对所有被read.table处理过的数据执行dplyr的清洗
  lapply(function(df) dplyr::filter(df, Indice != "Indice")) %>%
  bind_rows() %>%
  dplyr::mutate(Target = case_when(Target == "Friend" ~ "Close",
                                   Target == "Partner" ~ "Close",
                                   Target == "Mother" ~ "Close",
                                   Target == "Father" ~ "Close",
                                   Target == "Acquaintance" ~ "Stranger",
                                   Target == "Stranger" ~ "Stranger",
                                   Target == "Celebrity" ~ "Celebrity",
                                   Target == "none" ~ "NonPerson",
                                   )
                ) %>%
  #dplyr::filter(!stringr::str_detect(Indice, "ez")) %>%
  dplyr::mutate(Target = factor(Target,levels = c("Close", "Stranger", "Celebrity", "NonPerson")),
                Indice = factor(Indice,levels = c("rwDDM z", "rwDDM v", "ezDDM z", "ezDDM v", "Efficiency", "d Prime", "ACC", "RT"))) %>%
  dplyr::filter(!(Paper_ID %in% c("P51E1"))) 
names(plot)[2] <- "Monte Carlo SHR"
```

```{r}
meta[[2]] <- plot[[2]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(unique_ID = paste(Target, Indice, sep="_")) %>%
  metafor::escalc(data = ., measure = "COR", ni = Trials, ri = r) %>%
  metafor::aggregate.escalc(x = ., cluster = unique_ID, rho = 0) %>%
  base::summary() %>%
  dplyr::select(Target, Indice, yi, vi, sei, zi, pval, ci.lb, ci.ub) %>%
  dplyr::mutate(pval = ifelse(pval < 0.001, "<.001", 
                       ifelse(pval < 0.05, sprintf("%.3f", pval), sprintf("%.2f", pval)))) %>% 
  dplyr::mutate(yi_r = round(yi, 2),
                ci.lb = round(ci.lb, 2),
                ci.ub = round(ci.ub, 2)) %>%
  dplyr::mutate(CI = paste(yi_r, "(", ci.lb, ", ", ci.ub, ")", sep = ""))  %>% # 得到CI
  dplyr::filter(!stringr::str_detect(Indice, "ez")) %>%
  dplyr::mutate(.,
                #Target = factor(Target,levels = c("Close", "Stranger", "Celebrity", "NonPerson")),
                #Indice = factor(Indice,levels = c("rwDDM z", "rwDDM v", "ezDDM z", "ezDDM v", "Efficiency", "d Prime", "ACC", "RT")),
                Indice = case_when(Indice == "Efficiency" ~ "η",
                                   Indice == "d Prime" ~ "d'",
                                   Indice == "rwDDM v" ~ "v",
                                   Indice == "rwDDM z" ~ "z",
                                   #Indice == "rwDDM v" ~ "v(RWiener)",
                                   #Indice == "rwDDM z" ~ "z(RWiener)",
                                   #Indice == "ezDDM v" ~ "v(hausekeep)",
                                   #Indice == "ezDDM z" ~ "z(hausekeep)",
                                   TRUE ~ Indice),
                #Indice = factor(Indice,levels = c("RT", "Efficiency", "ACC", "d'", "v", "z")),
                Target_Indice = paste(Target, Indice, sep = "_"), 
                Target_Indice = factor(Target_Indice)
                ) %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number())
names(meta)[2] <- "Monte Carlo SHR"
```

```{r}
ggplot2::ggplot(meta[[2]], aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), size = 1, color = "black") +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-1, 1),
                              breaks = c(-1, 0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Target, ncol = 2) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme()

ggsave(filename = "./FIGURE/Fig2_meta_mcshr_unite.png",
       width = 10,
       height = 8,
       )
```


```{r Plot SHR for Simulated Data, message= FALSE, warning = FALSE}
ggplot(plot[[2]], aes(x = Indice, y = r, group = Paper_ID, color = interaction(Indice, Target))) + # nolint
  ggplot2::geom_errorbar(aes(color = interaction(Indice, Target), ymin = LLCI, ymax = ULCI), width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_y_continuous(limits = c(-0.1, 1.1),
                              breaks = c(0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::labs(y = "", x = "") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.title = element_blank(),
                 ) +
  ggplot2::facet_wrap(~Target, ncol = 4)

ggsave(filename = "./FIGURE/Fig2_mcshr_supp.png",
       width = 20,
       height = 20,
       )
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# ICC
```{r Read OUTPUT}
# 获取所有的icc
plot[[3]] <- list.files(file.path("./OUTPUT/icc/"),
                        pattern = "icc_.*\\.csv$") %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x) read.csv(file.path("./OUTPUT/icc/", x), header = TRUE)) %>% # nolint
  # 对所有被read.table处理过的数据执行dplyr的清洗
  lapply(function(df) dplyr::filter(df, type != "type")) %>%
  bind_rows() %>%
  dplyr::mutate(Target = case_when(Target == "Friend" ~ "Close",
                                   Target == "Partner" ~ "Close",
                                   Target == "Mother" ~ "Close",
                                   Target == "Father" ~ "Close",
                                   Target == "Acquaintance" ~ "Stranger",
                                   Target == "Stranger" ~ "Stranger",
                                   Target == "Celebrity" ~ "Celebrity",
                                   Target == "none" ~ "NonPerson",
                                   )
                ) %>%
  dplyr::filter(!stringr::str_detect(ICC_type, "ez")) %>%
  dplyr::mutate(type = factor(type, levels = c("ICC2", "ICC2k")),
                #Target = factor(Target,levels = c("Close", "Stranger", "Celebrity", "NonPerson")),
                #ICC_type = factor(ICC_type,
                                  #levels = c("rwDDM z", "rwDDM v", "ezDDM z", "ezDDM v", "Efficiency", "d Prime", "ACC", "RT") 
                                  #),
                ICC_type = case_when(ICC_type == "Efficiency" ~ "η",
                                     ICC_type == "d Prime" ~ "d'",
                                     ICC_type == "rwDDM v" ~ "v",
                                     ICC_type == "rwDDM z" ~ "z",
                                     #ICC_type == "rwDDM v" ~ "v(RWiener)",
                                     #ICC_type == "rwDDM z" ~ "z(RWiener)",
                                     #ICC_type == "ezDDM v" ~ "v(hausekeep)",
                                     #ICC_type == "ezDDM z" ~ "z(hausekeep)",
                                     TRUE ~ ICC_type
                                     ),
                Target_Type = paste(Target, ICC_type, sep = "_"), 
                ) 
names(plot)[3] <- "ICC"
```

```{r}
p0 <- plot[[3]] %>%
  dplyr::filter((Paper_ID %in% c("P0E1"))) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(Order = row_number(),
                ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC, group = Paper_ID, color = type)) + # nolint
  ggplot2::geom_errorbar(aes(color = type, ymin = LLCI, ymax = ULCI),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.22, 1.22),
                              breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
                              sec.axis = sec_axis(~., breaks = c(0.25, 0.625, 0.825, 0.95),
                                                  labels = c("Poor", "Moderate", "Good", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  #ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.title = element_blank(),
                 axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 ) 

p1 <- plot[[3]] %>%
  dplyr::filter((Paper_ID %in% c("P0E1"))) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(Order = row_number(),
                Outliar = case_when(LLCI <= 0 ~ FALSE, 
                                    LLCI > 0 ~TRUE),
                LLCI = ifelse(LLCI < -0.22, -0.22, LLCI), 
                ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC, group = Paper_ID, color = type)) + # nolint
  ggplot2::geom_errorbar(aes(color = type, ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.22, 1.22),
                              breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
                              sec.axis = sec_axis(~., breaks = c(0.25, 0.625, 0.825, 0.95),
                                                  labels = c("Poor", "Moderate", "Good", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.title = element_blank(),
                 axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 ) 
  
p2 <- plot[[3]] %>%
  dplyr::filter((Paper_ID %in% c("Ps2E1"))) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(Order = row_number(),
                Outliar = case_when(LLCI <= 0 ~ FALSE, 
                                    LLCI > 0 ~TRUE),
                LLCI = ifelse(LLCI < -0.22, -0.22, LLCI), 
                ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC, group = Paper_ID, color = type)) + # nolint
  ggplot2::geom_errorbar(aes(color = type, ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.22, 1.22),
                              breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
                              sec.axis = sec_axis(~., breaks = c(0.25, 0.625, 0.825, 0.95),
                                                  labels = c("Poor", "Moderate", "Good", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.title = element_blank(),
                 axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 ) 
ggsave(plot = p0,
       filename = "./FIGURE/Fig3_icc.png",
       width = 10,
       height = 8,
       )

  
ggsave(plot = p1,
       filename = "./FIGURE/Fig3_icc_P0.png",
       width = 10,
       height = 8,
       )

ggsave(plot = p2,
       filename = "./FIGURE/Fig3_icc_Ps2.png",
       width = 10,
       height = 8,
       )
```

# Trials Number
```{r}
plot[[4]] <- plot[[2]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::group_by(Target, Indice) %>%
  dplyr::mutate(cor = cor(r, Trials)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(Target, Indice, cor)  %>%
  dplyr::mutate(Target = factor(Target,levels = c("Close", "Stranger")),
                Indice = factor(Indice,levels = c("RT", "ACC", "d Prime", "Efficiency", "ezDDM v", "ezDDM z", "rwDDM v", "rwDDM z")))
```

```{r}
ggplot2::ggplot(plot[[4]], aes(x = Indice, y = cor)) +
  ggplot2::geom_bar(data = plot[[4]], aes(fill = Indice), alpha = 0.7, stat = "identity") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0, 1),
                              breaks = c(0.3, 0.7, 0.9),
                              sec.axis = sec_axis(~., breaks = c(0.3, 0.7, 0.9),
                                                  labels = c("Low", "Medium", "High"),
                                                  ),
                              ) +
  ggplot2::geom_hline(yintercept = 0.3, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::facet_wrap(~Target, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

ggsave(filename = "./FIGURE/Fig4_trails.png",
       width = 7,
       height = 7,
       )
```

```{r}
plot[[5]] <- plot[[2]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::filter(!(Paper_ID %in% c("P51E1"))) %>%
  dplyr::mutate(r_8 = case_when(Target == "Close" & Indice == "RT" ~ 120,
                                Target == "Stranger" & Indice == "RT" ~ 72,
                                Target == "Close" & Indice == "ACC" ~ 127,
                                Target == "Close" & Indice == "Efficiency" ~ 107,
                                Target == "Stranger" & Indice == "Efficiency" ~ 80,
                                Target == "Close" & Indice == "ezDDM v" ~ 125,
                                Target == "Stranger" & Indice == "ezDDM v" ~ 110,
                                Target == "Close" & Indice == "rwDDM v" ~ 130,
                                TRUE ~ NA),
                ) %>%
  dplyr::mutate(Indice = case_when(Indice == "d Prime" ~ "d'",
                                   Indice == "rwDDM v" ~ "v(RWiener)",
                                   Indice == "rwDDM z" ~ "z(RWiener)",
                                   Indice == "ezDDM v" ~ "v(hausekeep)",
                                   Indice == "ezDDM z" ~ "z(hausekeep)",
                                   TRUE ~ Indice),
                Target = factor(Target,levels = c("Close", "Stranger")),
                Indice = factor(Indice, levels = c("RT", "ACC", "d'", "Efficiency", "v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)")))
```

```{r}
p1 <- plot[[5]] %>%
  dplyr::filter((Indice %in% c("RT", "ACC", "d'", "Efficiency"))) %>%
  ggplot2::ggplot(data = ., aes(x = Trials, y = r, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 3, label.y = 1.1, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(limits = c(0, 140),
                              breaks = c(0, 30, 60, 100, 130),
                              ) +
  ggplot2::scale_y_continuous(limits = c(-0.1, 1.1),
                              breaks = c(0, 0.5, 0.8, 1),
                              ) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Close" & Indice == "RT"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Stranger" & Indice == "RT"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Close" & Indice == "ACC"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Close" & Indice == "Efficiency"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Stranger" & Indice == "Efficiency"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::facet_grid(cols = vars(Target), 
                      rows = vars(Indice)) +
  ggplot2::labs(y = "Monte-Carlo Split-Half Reliability", x = "Trial Numbers") +
  #ggplot2::scale_color_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  #ggplot2::scale_fill_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  ggplot2::scale_color_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::scale_fill_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p2 <- plot[[5]] %>%
  dplyr::filter((Indice %in% c("v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)"))) %>%
  ggplot2::ggplot(data = ., aes(x = Trials, y = r, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 3, label.y = 1.1, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(limits = c(0, 140),
                              breaks = c(0, 30, 60, 100, 130),
                              ) +
  ggplot2::scale_y_continuous(limits = c(-0.1, 1.1),
                              breaks = c(0, 0.5, 0.8, 1),
                              ) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Close" & Indice == "v(hausekeep)"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Stranger" & Indice == "v(hausekeep)"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_vline(data = subset(plot[[5]], Target == "Close" & Indice == "v(RWiener)"),
                      aes(xintercept = r_8),
                      linetype = "dotted", color = "black", size = 1, alpha = 0.5) +
  ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", size = 1, alpha = 0.5) + # nolint
  ggplot2::facet_grid(cols = vars(Target), 
                      rows = vars(Indice)) +
  ggplot2::labs(y = "", x = "Trial Numbers") +
  #ggplot2::scale_color_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  #ggplot2::scale_fill_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  ggplot2::scale_color_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::scale_fill_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p3 <- p1 + p2+plot_layout(guides = 'collect')

ggsave(filename = "./FIGURE/Fig5_regression.png",
       width = 10,
       height = 8,
       )
rm(p1, p2, p3)
```


