---
title: "8_Meta_Plot"
author: "yuki"
date: "2023-09-07"
output: html_document
---
```{r}
out <- list(
  list(),
  list()
)

names(out)[1] <- "Self - Close"
names(out)[2] <- "Self - Stranger"

plot_forest <- list(
  list(),
  list()
)
```

```{r}
df_close <- utils::read.csv("./OUTPUT/meta/meta_close.csv") %>%
  dplyr::mutate(Target = "Close") 

df_stranger <- utils::read.csv("./OUTPUT/meta/meta_stranger.csv") %>%
  dplyr::mutate(Target = "Stranger") 

df_meta_bind <- dplyr::bind_rows(df_close, df_stranger) %>%
  dplyr::mutate(
    Indice = case_when(
    Indice == "eta" ~ "η",
    Indice == "d" ~ "d'",
    #Indice == "rwDDM v" ~ "v",
    #Indice == "rwDDM z" ~ "z",
    Indice == "rwDDM v" ~ "v(RWiener)",
    Indice == "rwDDM z" ~ "z(RWiener)",
    Indice == "ezDDM v" ~ "v(hausekeep)",
    Indice == "ezDDM z" ~ "z(hausekeep)",
    TRUE ~ Indice
    ),
    Target_Indice = paste(Target, Indice, sep = "_"),
    g = case_when(
      Indice %in% c("RT", "η") ~ g * -1,
      TRUE ~ g
    ),
    temp_LLCI = LLCI,
    temp_ULCI = ULCI,
    LLCI = case_when(
      Indice %in% c("RT", "η") ~ temp_ULCI * -1,
      TRUE ~ temp_LLCI
    ),
    ULCI = case_when(
      Indice %in% c("RT", "η") ~ temp_LLCI * -1,
      TRUE ~ temp_ULCI
    ),
    Outliar = case_when(
      LLCI <= 0 ~ TRUE, 
      ULCI > 0 ~ FALSE,
    )
  )

df_close <- df_meta_bind %>% dplyr::filter(Target == "Close") %>%
  dplyr::arrange(g) %>%
  dplyr::mutate(Order = row_number()) %>%
  dplyr::select(Target, Indice, Target_Indice, g, LLCI, ULCI, Order, Outliar)

df_stranger <- df_meta_bind %>% dplyr::filter(Target == "Stranger") %>%
  dplyr::arrange(g) %>%
  dplyr::mutate(Order = row_number()) %>%
  dplyr::select(Target, Indice, Target_Indice, g, LLCI, ULCI, Order, Outliar)
```

```{r}
p1 <- ggplot2::ggplot(df_close, aes(x = Order, y = g)) +
  ggplot2::geom_errorbar(aes(ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, linewidth = 1, position = position_dodge(width = 1)) + # nolint
  #ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1, color = "black", linetype = Outliar) +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1.5, 2.2), 
    breaks = seq(-0.5,2.2, by = 0.5),
    sec.axis = sec_axis(~., breaks = c(0.2, 0.5, 0.8),
                    labels = c("Small", "Medium", "Large")),
  ) +
  #ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.2, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -1.5, x = reorder(Indice, Order), label = Indice),
                     hjust = 0, size = 5, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(a) Self - Close") +
  ggplot2::labs(y = expression("Hedges' " * italic(g)), x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    plot.title = element_text(size = 15, family = 'serif', hjust = 0),
    axis.text.x.top = element_text(size = 10, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    axis.title.x = element_text(size = 15, family='serif')
  )

p2 <- ggplot2::ggplot(df_stranger, aes(x = Order, y = g)) +
  ggplot2::geom_errorbar(aes(ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, linewidth = 1, position = position_dodge(width = 1)) + # nolint
  #ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1, color = "black", linetype = Outliar) +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1.5, 2.2), 
    breaks = seq(-0.5,2.2, by = 0.5),
    sec.axis = sec_axis(~., breaks = c(0.2, 0.5, 0.8),
                    labels = c("Small", "Medium", "Large")),
  ) +
  #ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.2, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -1.5, x = reorder(Indice, Order), label = Indice),
                     hjust = 0, size = 5, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(b) Self - Stranger") +
  ggplot2::labs(y = expression("Hedges' " * italic(g)), x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    plot.title = element_text(size = 15, family = 'serif', hjust = 0),
    axis.text.x.top = element_text(size = 10, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    axis.title.x = element_text(size = 15, family='serif')
  )

p_meta_bind <- p1 + p2 + plot_layout(nrow = 1, guides = 'collect')

ggsave(
  plot = p_meta_bind,
  filename = "./FIGURE/meta_bind.png",
  width = 15,
  height = 6,
)

p_meta_bind

#rm(df_close, df_stranger, p_meta_bind, p1, p2)
```

# Close
## RT
```{r}
out[[1]][[1]] <- res_meta[[1]][[1]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = c("Paper_ID", "Author", "Year")) %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi*-1, 2),
    ci.lb = round(ci.lb*-1, 2),
    ci.ub = round(ci.ub*-1, 2),
    zi = round(zi*-1, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[1]])[1] <- "RT"
```

```{r}
plot_forest[[1]][[1]] <- ggplot2::ggplot(out[[1]][[1]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-3.5, 3), 
    breaks = seq(-0.5,2.5, by = 0.5),
    sec.axis = sec_axis(
      ~., 
      breaks = c(-2.9, -1.2, 3),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -3.5, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.2, y = reorder(Unique_ID, Order), label = CI), size = 7, hjust = 0.5, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 3, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(a) RT for [Self - Close]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.66),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Close_RT.png", width = 24, height = 18, limitsize = FALSE)
```

## ACC
```{r}
out[[1]][[2]] <- res_meta[[1]][[2]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[1]])[2] <- "ACC"
```

```{r}
plot_forest[[1]][[2]] <- ggplot2::ggplot(out[[1]][[2]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-3.7, 6), 
    breaks = seq(-0.5,5.5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-3, -1.3, 6),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -3.7, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.3, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 6, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(c) ACC for [Self - Close]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.66),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Close_ACC.png", width = 24, height = 18, limitsize = FALSE)
```

## d
```{r}
out[[1]][[3]] <- res_meta[[1]][[3]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[1]])[3] <- "d"
```

```{r}
plot_forest[[1]][[3]] <- ggplot2::ggplot(out[[1]][[3]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-2.6, 2.5), 
    breaks = seq(-0.5,2, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.17, -1, 2.5),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -2.6, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 2.5, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(e) d' for [Self - Close]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.66),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Close_d.png", width = 24, height = 18, limitsize = FALSE)
```

## eta
```{r}
out[[1]][[4]] <- res_meta[[1]][[4]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi*-1, 2),
    ci.lb = round(ci.lb*-1, 2),
    ci.ub = round(ci.ub*-1, 2),
    zi = round(zi*-1, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[1]])[4] <- "eta"
```

```{r}
plot_forest[[1]][[4]] <- ggplot2::ggplot(out[[1]][[4]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-4.5, 4), 
    breaks = seq(-0.5,3.5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-3.7, -2.0, 4),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -4.5, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -2.0, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 4, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(g) η for [Self - Close]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.75),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Close_eta.png", width = 24, height = 18, limitsize = FALSE)
```

## v
```{r}
out[[1]][[5]] <- res_meta[[1]][[5]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[1]])[5] <- "v"
```

```{r}
plot_forest[[1]][[5]] <- ggplot2::ggplot(out[[1]][[5]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-2.6, 2.7), 
    breaks = seq(-0.5,2.5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.17, -1, 2.6),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -2.6, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 2.6, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(i) v for [Self - Close]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.73),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Close_v.png", width = 24, height = 18, limitsize = FALSE)
```

## z
```{r}
out[[1]][[6]] <- res_meta[[1]][[6]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi*-1, 2),
    ci.lb = round(ci.lb*-1, 2),
    ci.ub = round(ci.ub*-1, 2),
    zi = round(zi*-1, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[1]])[6] <- "z"
```

```{r}
plot_forest[[1]][[6]] <- ggplot2::ggplot(out[[1]][[6]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-3.2, 1.3), 
    breaks = seq(-1.5,1, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.8, -1.9, 1.2),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -3.2, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.9, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 1.2, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(k) z for [Self - Close]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.73),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Close_z.png", width = 24, height = 18, limitsize = FALSE)
```

# Stranger
## RT
```{r}
out[[2]][[1]] <- res_meta[[2]][[1]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi*-1, 2),
    ci.lb = round(ci.lb*-1, 2),
    ci.ub = round(ci.ub*-1, 2),
    zi = round(zi*-1, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[2]])[1] <- "RT"
```

```{r}
plot_forest[[2]][[1]] <- ggplot2::ggplot(out[[2]][[1]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-3.5, 3), 
    breaks = seq(-0.5,2.5, by = 0.5),
    sec.axis = sec_axis(
      ~., 
      breaks = c(-2.9, -1.2, 3),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -3.5, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.2, y = reorder(Unique_ID, Order), label = CI), size = 7, hjust = 0.5, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 3, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(b) RT for [Self - Stranger]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.75),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Stranger_RT.png", width = 24, height = 18, limitsize = FALSE)
```

## ACC
```{r}
out[[2]][[2]] <- res_meta[[2]][[2]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[2]])[2] <- "ACC"
```

```{r}
plot_forest[[2]][[2]] <- ggplot2::ggplot(out[[2]][[2]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-3.6, 5.5), 
    breaks = seq(-0.5,5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.9, -1.4, 5.5),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -3.6, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.4, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 5.5, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(d) ACC for [Self - Stranger]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.75),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Stranger_ACC.png", width = 24, height = 18, limitsize = FALSE)
```

## d
```{r}
out[[2]][[3]] <- res_meta[[2]][[3]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[2]])[3] <- "d"
```

```{r}
plot_forest[[2]][[3]] <- ggplot2::ggplot(out[[2]][[3]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-2.6, 3), 
    breaks = seq(-0.5,2.5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.17, -1.2, 2.7),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -2.6, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.2, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 2.7, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(f) d' for [Self - Stranger]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.65),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Stranger_d.png", width = 24, height = 18, limitsize = FALSE)
```

## eta
```{r}
out[[2]][[4]] <- res_meta[[2]][[4]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi*-1, 2),
    ci.lb = round(ci.lb*-1, 2),
    ci.ub = round(ci.ub*-1, 2),
    zi = round(zi*-1, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[2]])[4] <- "eta"
```

```{r}
plot_forest[[2]][[4]] <- ggplot2::ggplot(out[[2]][[4]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-4.7, 5.2), 
    breaks = seq(-0.5,5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-3.7, -1.3, 5),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -4.7, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.3, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 5, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(h) η for [Self - Stranger]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.75),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Stranger_eta.png", width = 24, height = 18, limitsize = FALSE)
```

## v
```{r}
out[[2]][[5]] <- res_meta[[2]][[5]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[2]])[5] <- "v"
```

```{r}
plot_forest[[2]][[5]] <- ggplot2::ggplot(out[[2]][[5]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-2.6, 3.5), 
    breaks = seq(-0.5,3, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.17, -1.2, 3.3),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -2.6, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.2, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 3.3, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(j) v for [Self - Stranger]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.65),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Stranger_v.png", width = 24, height = 18, limitsize = FALSE)
```

## z
```{r}
out[[2]][[6]] <- res_meta[[2]][[6]] %>%
  base::summary() %>% # 得到yi, vi, sei, zi, ci.lb, ci.ub这些变量
  #dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(
    ############################################################################
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2),
    zi = round(zi, 2),
    ############################################################################
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(
        pval < 0.05,
        sub("^0+", "", sprintf("%.3f", pval)),
        sub("^0+", "", sprintf("%.3f", pval))
      )
    ),
    LLCI = case_when(
      ci.lb < ci.ub ~ ci.lb,
      ci.lb > ci.ub ~ ci.ub,
    ),
    ULCI = case_when(
      ci.ub > ci.lb ~ ci.ub,
      ci.ub < ci.lb ~ ci.lb,
    ),
    CI = paste0(
      format(yi_r, nsmall = 2),
      "[", format(LLCI, nsmall = 2), ", ", format(ULCI, nsmall = 2), "]",
      sep = ""
    ),
    ############################################################################
    Unique_ID = paste0(Author," (",Year,")",", S",Exp),
    ############################################################################
  ) %>%
  dplyr::arrange(yi_r) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
  dplyr::select(
    Paper_ID, Author, Year, Exp,
    Unique_ID, Order,
    yi_r, vi, sei, zi, 
    LLCI, ULCI, CI, pval
  ) 

names(out[[2]])[6] <- "z"
```

```{r}
plot_forest[[2]][[6]] <- ggplot2::ggplot(out[[2]][[6]], aes(x = yi_r , y = reorder(Unique_ID, Order))) +
  ggplot2::geom_linerange(aes(xmin = LLCI, xmax = ULCI), linewidth = 1.5) +
  ggplot2::geom_point(shape=15, size = 5) +
  #ggplot2::geom_linerange(aes(xmin = fix_ci.lb, xmax = fix_ci.ub, y = 1.5), linewidth = 3, color = "grey") + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = fix_yi, y = 1.5), shape=15, size = 7, color = "grey") + # Fixed Effect Point
  ggplot2::scale_x_continuous(
    limits = c(-2.8, 1.8), 
    breaks = seq(-0.5,1.5, by = 0.5),
    sec.axis = sec_axis(
      ~., breaks = c(-2.4, -1.3, 1.7),
      labels = c("Author(s), Year and Study", "SMD (95%-CI)", expression(italic(p) * "-value"))
    ),
  ) +
  ggplot2::geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 3, alpha = 0.5) +
  ggplot2::geom_text(aes(x = -2.8, y = reorder(Unique_ID, Order), label = reorder(Unique_ID, Order)), size = 7, hjust = 0, family='serif',) + # Author_Year_Study
  ggplot2::geom_text(aes(x = -1.3, y = reorder(Unique_ID, Order), label = CI),hjust = 0.5, size = 7, family='serif',) + # CI
  ggplot2::geom_text(aes(x = 1.7, y = reorder(Unique_ID, Order), label = pval), size = 7, hjust = 0.5, family='serif',) + # Right: P-value
  #ggplot2::annotate("text", x = -3.5, y = 1 ,label = "Q (161) = 1426.33, p <.0001, I2 = 90.90%", size = 16, family='serif', color = "black") +
  #ggplot2::annotate("text", x = -3, y = 2 ,label = "Random Effect = -0.88, SE = 0.05, p <.01, 95% CI [-.97, -.79]", size = 16, family='serif', color = "black") +
  ggplot2::labs(x = expression("Hedges' " * italic(g))) +
  ggplot2::ggtitle("(l) z for [Self - Stranger]") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 axis.text.x.top = element_text(size = 25, family='serif'),
                 axis.text.x.bottom = element_text(size = 25, family='serif'),
                 axis.title.x = element_text(size = 25, hjust = 0.65),
                 plot.title = element_text(size = 30, family = 'serif', hjust = 0),
                 legend.title = element_blank(),
                 axis.line.y = element_blank(),
                 axis.ticks.x.top = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 axis.ticks.y= element_blank(),
                 axis.text.y= element_blank(),
                 axis.title.y= element_blank(),
                 ) 

ggsave(filename = "./FIGURE/Forest_Stranger_z.png", width = 24, height = 18, limitsize = FALSE)
```

# Combine
```{r}
temp_p <- plot_forest[[1]][[1]] + plot_forest[[2]][[1]] +
  plot_layout(guides = 'collect', ncol = 1)

ggsave(
  plot = last_plot(),
  filename = "./FIGURE/Forest_RT.png",
  width = 24, height = 36, 
  limitsize = FALSE
)

rm(temp_p)
```

```{r}
temp_p <- plot_forest[[1]][[1]] + 
  plot_forest[[1]][[2]] +
  plot_forest[[1]][[3]] +
  plot_forest[[1]][[4]] +
  plot_forest[[1]][[5]] +
  plot_forest[[1]][[6]] +
  plot_forest[[2]][[1]] +
  plot_forest[[2]][[2]] +
  plot_forest[[2]][[3]] +
  plot_forest[[2]][[4]] +
  plot_forest[[2]][[5]] +
  plot_forest[[2]][[6]] +
  plot_layout(guides = 'collect', ncol = 3)

ggsave(
  plot = last_plot(),
  filename = "./FIGURE/Forest_Supp.png",
  width = 72, height = 72, 
  limitsize = FALSE
)

rm(temp_p)
```