---
title: "7_Meta"
author: "yuki"
date: "2023-08-24"
output: html_document
---
# Create NULL List
```{r Create NULL List}
meta <- list()
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# Normal SHR
```{r}
meta[[1]] <- plot[[1]] %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    unique_ID = paste(Target, Indice, Method, sep="_")
  ) %>%
  metafor::escalc(
    data = ., measure = "COR", ni = Trials, ri = r
  ) %>%
  metafor::aggregate.escalc(
    x = ., cluster = unique_ID, rho = 0
  ) %>%
  base::summary(
    
  ) %>%
  dplyr::select(
    Target, Indice, Method,
    yi, vi, sei, zi, pval,
    ci.lb, ci.ub
  ) %>%
  dplyr::mutate(
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(pval < 0.05, sprintf("%.3f", pval), sprintf("%.2f", pval))
    )
  ) %>% 
  dplyr::mutate(
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2)
  ) %>%
  dplyr::mutate(
    CI = paste(yi_r, "(", ci.lb, ", ", ci.ub, ")", sep = "")
  )  %>% # 得到CI
  dplyr::mutate(
    .,
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target_Indice = paste(Target, Indice, sep = "_"), 
    Target_Indice = factor(Target_Indice)
  ) 
                
names(meta)[1] <- "Normal SHR"
```

```{r}
p1 <- meta[[1]] %>%
  dplyr::filter(Method == "First-Second") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p2 <- meta[[1]] %>%
  dplyr::filter(Method == "Odd-Even") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
    ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p3 <- meta[[1]] %>%
  dplyr::filter(Method == "Permuted") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p0 <- p1 + p2 + p3 + plot_layout(ncol = 1, guides = 'collect')

ggsave(plot = p0,
       filename = "./FIGURE/Fig1_meta_nmshr.png",
       width = 9,
       height = 20,
       )
ggsave(plot = p1,
       filename = "./FIGURE/Fig1_meta_fs.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p2,
       filename = "./FIGURE/Fig1_meta_od.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p3,
       filename = "./FIGURE/Fig1_meta_per.png",
       width = 10,
       height = 8,
       )

rm(p0, p1, p2, p3)
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# Monte Carlo SHR
```{r}
meta[[2]] <- plot[[2]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(unique_ID = paste(Target, Indice, sep="_")) %>%
  #dplyr::filter(!(Trials < 60 & grepl("DDM", Indice))) %>%
  metafor::escalc(data = ., measure = "COR", ni = Trials, ri = r) %>%
  metafor::aggregate.escalc(x = ., cluster = unique_ID, rho = 0) %>%
  base::summary() %>%
  dplyr::select(Target, Indice, yi, vi, sei, zi, pval, ci.lb, ci.ub) %>%
  dplyr::mutate(pval = ifelse(pval < 0.001, "<.001", 
                       ifelse(pval < 0.05, sprintf("%.3f", pval), sprintf("%.2f", pval)))) %>% 
  dplyr::mutate(yi_r = round(yi, 2),
                ci.lb = round(ci.lb, 2),
                ci.ub = round(ci.ub, 2)) %>%
  dplyr::mutate(CI = paste(yi_r, "(", ci.lb, ", ", ci.ub, ")", sep = ""))  %>% # 得到CI
  dplyr::filter(!stringr::str_detect(Indice, "ez")) %>%
  dplyr::mutate(.,
                #Target = factor(Target,levels = c("Close", "Stranger", "Celebrity", "NonPerson")),
                #Indice = factor(Indice,levels = c("rwDDM z", "rwDDM v", "ezDDM z", "ezDDM v", "Efficiency", "d Prime", "ACC", "RT")),
                Indice = case_when(Indice == "Efficiency" ~ "η",
                                   Indice == "d Prime" ~ "d'",
                                   #Indice == "rwDDM v" ~ "v",
                                   #Indice == "rwDDM z" ~ "z",
                                   Indice == "rwDDM v" ~ "v(RWiener)",
                                   Indice == "rwDDM z" ~ "z(RWiener)",
                                   Indice == "ezDDM v" ~ "v(hausekeep)",
                                   Indice == "ezDDM z" ~ "z(hausekeep)",
                                   TRUE ~ Indice),
                #Indice = factor(Indice,levels = c("RT", "Efficiency", "ACC", "d'", "v", "z")),
                Target_Indice = paste(Target, Indice, sep = "_"), 
                Target_Indice = factor(Target_Indice)
                ) %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number())

names(meta)[2] <- "Monte Carlo SHR"
```

```{r}
ggplot2::ggplot(meta[[2]], aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1, color = "black") +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-1, 1),
                              breaks = c(-1, 0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Target, ncol = 2) +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme()

ggsave(filename = "./FIGURE/Fig2_meta_mcshr_unite.png",
       width = 10,
       height = 8,
       )
```

```{r}
p_shr <- meta[[2]] %>%
  dplyr::filter(
    Target %in% c("Close", "Stranger")
  ) %>%
  dplyr::mutate(
    Outliar = case_when(ci.lb <= 0 ~ TRUE, 
                        ci.lb > 0 ~FALSE),
    ci.lb = ifelse(ci.lb < -0.10, -0.10, ci.lb), 
  ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  #ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1, color = "black", linetype = Outliar) +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.1, 1.1),
                              breaks = c(0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  #ggplot2::facet_wrap(~Target, ncol = 2) +
  ggplot2::labs(y = "Split-Half Reliability", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

ggsave(filename = "./FIGURE/Fig2_meta_mcshr_unite.png",
       width = 10,
       height = 8,
       )
```


```{r}
p_icc <- plot[[3]] %>%
  dplyr::filter(
    !stringr::str_detect(ICC_type, "ez")
  ) %>%
  dplyr::mutate(
    ICC_type = case_when(
      ICC_type == "Efficiency" ~ "η",
      ICC_type == "d Prime" ~ "d'",
      ICC_type == "rwDDM v" ~ "v",
      ICC_type == "rwDDM z" ~ "z",
      TRUE ~ ICC_type
    ),
    Target_Type = paste(
      Target, ICC_type, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("P0E1")),
    type == "ICC2"
  ) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(
    Order = row_number(),
    Outliar = case_when(LLCI <= 0 ~ TRUE, 
                        LLCI > 0 ~FALSE),
    LLCI = ifelse(LLCI < -0.10, -1.1, LLCI), 
  ) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC, group = Paper_ID, color = type)) + # nolint
  ggplot2::geom_errorbar(aes(color = type, ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.10, 1.10),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0.25, 0.625, 0.825, 0.95),
      labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  #ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "Intraclass Correlation Coefficient 2", x = "") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 #axis.title = element_blank(),
                 axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 ) 
```

```{r}
p_shr_icc <- p_shr + p_icc + plot_layout(ncol = 1, guides = 'collect')

ggsave(plot = p_shr_icc,
       filename = "./FIGURE/Fig34_shr_icc.png",
       width = 9,
       height = 12,
       )
rm(p_shr_icc, p_shr, p_icc)
```

# Meta Analysis
```{r List for Paper ID}
p <- list()
p[[1]] <- "P0E1"
p[[2]] <- "P6E1"
p[[3]] <- "P46E2"
p[[4]] <- "P51E1"
p[[5]] <- "P51E2"
p[[6]] <- "P54E1"
p[[7]] <- "P54E3"
p[[8]] <- "Pn4E1"
p[[9]] <- "Pn13E1"
p[[10]] <- "Pn13E3"
p[[11]] <- "Pn13E4"
p[[12]] <- "Pn16E1"
p[[13]] <- "Pn16E2"
p[[14]] <- "Pn16E3"
p[[15]] <- "Pn23E1"
p[[16]] <- "P95E1"
p[[17]] <- "P95E2"
p[[18]] <- "Ps1E1"
p[[19]] <- "Ps2E1"
p[[20]] <- "Ps3E1"
p[[21]] <- "Ps4E1"
p[[22]] <- "Ps4E2"
```

```{r}
raw_meta <- list()
for (i in 1:18) {
  raw_meta[[i]] <- list()
}
```

```{r, message=FALSE}
for (i in 1:18) {
  raw_meta[[i]][[1]] <-yukiBP::df(df = df[[i]], i = i, Indice = "rt")
  raw_meta[[i]][[2]] <-yukiBP::df(df = df[[i]], i = i, Indice = "acc")
  raw_meta[[i]][[3]] <-yukiBP::df(df = df[[i]], i = i, Indice = "dp")
  raw_meta[[i]][[4]] <-yukiBP::df(df = df[[i]], i = i, Indice = "eta")
  raw_meta[[i]][[5]] <-yukiBP::df(df = df[[i]], i = i, Indice = "ezddm")
  raw_meta[[i]][[6]] <-yukiBP::df(df = df[[i]], i = i, Indice = "rwddm")
  
  raw_meta[[i]] <- base::Reduce(
    function(x, y)
      left_join(x, y, by = c("Identity", "Paper_ID")),
    raw_meta[[i]]
  )
}

raw_meta <- bind_rows(raw_meta)
```

```{r Raw Meta Data}
df_meta <- list()
df_meta[[1]] <- raw_meta %>%
  dplyr::filter(
    # 被认为是在原范式上有较大修改(4 session 4 mood)
    !(Paper_ID %in% c("P51E1")) 
  ) 

rm(raw_meta)
names(df_meta)[1] <- "Raw Meta Data"
```

```{r Convert Identity to STD}
df_meta[[2]] <- df_meta[[1]] %>%
  dplyr::mutate(
    Identity = case_when(
      Identity == "Self" ~ "Self",
      Identity == "Friend" ~ "Close",
      Identity == "Partner" ~ "Close",
      Identity == "Mother" ~ "Close",
      Identity == "Father" ~ "Close",
      Identity == "Acquaintance" ~ "Stranger",
      Identity == "Stranger" ~ "Stranger",
      Identity == "Celebrity" ~ "Celebrity",
      Identity == "none" ~ "NonPerson",
    )
  ) %>%
  dplyr::rename(
    ez_v_mean = v_mean.x,
    ez_v_sd = v_sd.x,
    ez_z_mean = z_mean.x,
    ez_z_sd = z_sd.x,
    rw_v_mean = v_mean.y,
    rw_v_sd = v_sd.y,
    rw_z_mean = z_mean.y,
    rw_z_sd = z_sd.y,
  )

names(df_meta)[2] <- "Convert Identity to STD"
```

```{r Self - Close}
df_meta[[3]] <- df_meta[[2]] %>%
  dplyr::filter(
    Identity %in% c("Self", "Close")
  ) %>%
  tidyr::pivot_wider(
    id_cols = Paper_ID,
    names_from = Identity,
    values_from = c(
      RT_mean, RT_sd,
      ACC_mean, ACC_sd,
      d_mean, d_sd,
      eta_mean, eta_sd,
      ez_v_mean , ez_v_sd,
      ez_z_mean, ez_z_sd,
      rw_v_mean, rw_v_sd,
      rw_z_mean, rw_z_sd,
    ),
    names_glue = "{.value}_{Identity}"
  ) %>%
  tidyr::drop_na(
    
  ) %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    ri = 0.7
  )

names(df_meta)[3] <- "Self - Close"
```

```{r Self - Stranger}
df_meta[[4]] <- df_meta[[2]] %>%
  dplyr::filter(
    Identity %in% c("Self", "Stranger")
  ) %>%
  tidyr::pivot_wider(
    id_cols = Paper_ID,
    names_from = Identity,
    values_from = c(
      RT_mean, RT_sd,
      ACC_mean, ACC_sd,
      d_mean, d_sd,
      eta_mean, eta_sd,
      ez_v_mean , ez_v_sd,
      ez_z_mean, ez_z_sd,
      rw_v_mean, rw_v_sd,
      rw_z_mean, rw_z_sd,
    ),
    names_glue = "{.value}_{Identity}"
  ) %>%
  tidyr::drop_na(
    
  ) %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    ri = 0.7
  )

names(df_meta)[4] <- "Self - Stranger"
```

```{r res_meta}
res_meta <- list(
  list(),
  list()
)

res_meta[[1]] <- list()
res_meta[[2]] <- list()

df_meta[[5]] <- list(
  list(),
  list()
)
```

## Close

```{r}
res_meta[[1]][[1]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = RT_mean_Self,
  m2i = RT_mean_Close,
  sd1i = RT_sd_Self,
  sd2i = RT_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "RT",
    Target = "Close"
  )

names(res_meta[[1]])[1] <- "Meta for RT"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[1]])
)
df_meta[[5]][[1]][[1]] <- data.frame(Indice = "RT",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[1]])
```

```{r}
res_meta[[1]][[2]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ACC_mean_Self,
  m2i = ACC_mean_Close,
  sd1i = ACC_sd_Self,
  sd2i = ACC_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "ACC",
    Target = "Close"
  )

names(res_meta[[1]])[2] <- "Meta for ACC"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[2]])
)
df_meta[[5]][[1]][[2]] <- data.frame(Indice = "ACC",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[2]])
```

```{r}
res_meta[[1]][[3]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = d_mean_Self,
  m2i = d_mean_Close,
  sd1i = d_sd_Self,
  sd2i = d_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "d",
    Target = "Close"
  )

names(res_meta[[1]])[3] <- "Meta for d"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[3]])
)
df_meta[[5]][[1]][[3]] <- data.frame(Indice = "d",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[3]])
```

```{r}
res_meta[[1]][[4]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = eta_mean_Self,
  m2i = eta_mean_Close,
  sd1i = eta_sd_Self,
  sd2i = eta_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "eta",
    Target = "Close"
  )

names(res_meta[[1]])[4] <- "Meta for eta"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[4]])
)
df_meta[[5]][[1]][[4]] <- data.frame(Indice = "eta",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[4]])
```

```{r}
res_meta[[1]][[5]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_v_mean_Self,
  m2i = ez_v_mean_Close,
  sd1i = ez_v_sd_Self,
  sd2i = ez_v_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM v",
    Target = "Close"
  )

names(res_meta[[1]])[5] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[5]])
)
df_meta[[5]][[1]][[5]] <- data.frame(Indice = "ezDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[5]])
```

```{r}
res_meta[[1]][[6]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_z_mean_Self,
  m2i = ez_z_mean_Close,
  sd1i = ez_z_sd_Self,
  sd2i = ez_z_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM z",
    Target = "Close"
  )

names(res_meta[[1]])[6] <- "Meta for ezDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[6]])
)
df_meta[[5]][[1]][[6]] <- data.frame(Indice = "ezDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[6]])
```

```{r}
res_meta[[1]][[7]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_v_mean_Self,
  m2i = rw_v_mean_Close,
  sd1i = rw_v_sd_Self,
  sd2i = rw_v_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM v",
    Target = "Close"
  )

names(res_meta[[1]])[7] <- "Meta for rwDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[7]])
)
df_meta[[5]][[1]][[7]] <- data.frame(Indice = "rwDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[7]])
```

```{r}
res_meta[[1]][[8]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_z_mean_Self,
  m2i = rw_z_mean_Close,
  sd1i = rw_z_sd_Self,
  sd2i = rw_z_sd_Close,
  ni = Trials,
  ri = ri,
  data = df_meta[[3]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM z",
    Target = "Close"
  )

names(res_meta[[1]])[8] <- "Meta for rwDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[1]][[8]])
)
df_meta[[5]][[1]][[8]] <- data.frame(Indice = "rwDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[1]][[8]])
```

## Stranger
```{r}
res_meta[[2]][[1]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = RT_mean_Self,
  m2i = RT_mean_Stranger,
  sd1i = RT_sd_Self,
  sd2i = RT_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "RT",
    Target = "Stranger"
  )

names(res_meta[[2]])[1] <- "Meta for RT"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[1]])
)
df_meta[[5]][[2]][[1]] <- data.frame(Indice = "RT",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[1]])
```

```{r}
res_meta[[2]][[2]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ACC_mean_Self,
  m2i = ACC_mean_Stranger,
  sd1i = ACC_sd_Self,
  sd2i = ACC_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "ACC",
    Target = "Stranger"
  )

names(res_meta[[2]])[2] <- "Meta for ACC"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[2]])
)
df_meta[[5]][[2]][[2]] <- data.frame(Indice = "ACC",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[2]])
```

```{r}
res_meta[[2]][[3]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = d_mean_Self,
  m2i = d_mean_Stranger,
  sd1i = d_sd_Self,
  sd2i = d_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "d",
    Target = "Stranger"
  )

names(res_meta[[2]])[3] <- "Meta for d"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[3]])
)
df_meta[[5]][[2]][[3]] <- data.frame(Indice = "d",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[3]])
```

```{r}
res_meta[[2]][[4]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = eta_mean_Self,
  m2i = eta_mean_Stranger,
  sd1i = eta_sd_Self,
  sd2i = eta_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "eta",
    Target = "Stranger"
  )

names(res_meta[[2]])[4] <- "Meta for eta"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[4]])
)
df_meta[[5]][[2]][[4]] <- data.frame(Indice = "eta",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[4]])
```

```{r}
res_meta[[2]][[5]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_v_mean_Self,
  m2i = ez_v_mean_Stranger,
  sd1i = ez_v_sd_Self,
  sd2i = ez_v_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM v",
    Target = "Stranger"
  )

names(res_meta[[2]])[5] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[5]])
)
df_meta[[5]][[2]][[5]] <- data.frame(Indice = "ezDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[5]])
```

```{r}
res_meta[[2]][[6]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = ez_z_mean_Self,
  m2i = ez_z_mean_Stranger,
  sd1i = ez_z_sd_Self,
  sd2i = ez_z_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "ezDDM z",
    Target = "Stranger"
  )

names(res_meta[[2]])[6] <- "Meta for z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[6]])
)
df_meta[[5]][[2]][[6]] <- data.frame(Indice = "z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[6]])
```

```{r}
res_meta[[2]][[7]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_v_mean_Self,
  m2i = rw_v_mean_Stranger,
  sd1i = rw_v_sd_Self,
  sd2i = rw_v_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM v",
    Target = "Stranger"
  )

names(res_meta[[2]])[7] <- "Meta for ezDDM v"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[7]])
)
df_meta[[5]][[2]][[7]] <- data.frame(Indice = "ezDDM v",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[7]])
```

```{r}
res_meta[[2]][[8]] <- metafor::escalc(
  measure = "SMCRH",
  m1i = rw_z_mean_Self,
  m2i = rw_z_mean_Stranger,
  sd1i = rw_z_sd_Self,
  sd2i = rw_z_sd_Stranger,
  ni = Trials,
  ri = ri,
  data = df_meta[[4]]
) %>%
  dplyr::mutate(
    Indice = "rwDDM z",
    Target = "Stranger"
  )

names(res_meta[[2]])[8] <- "Meta for rwDDM z"

prd <- metafor::predict.rma(
  metafor::rma(yi, vi, data = res_meta[[2]][[8]])
)
df_meta[[5]][[2]][[8]] <- data.frame(Indice = "rwDDM z",g = prd$pred, SE = prd$se, LLCI = prd$ci.lb, ULCI = prd$ci.ub)
rm(prd)

metafor::rma(yi, vi, data = res_meta[[2]][[8]])
```


```{r}
df_meta[[6]] <- list(list(), list())

df_meta[[6]][[1]] <- dplyr::bind_rows(
  df_meta[[5]][[1]]
)

df_meta[[6]][[2]] <- dplyr::bind_rows(
  df_meta[[5]][[2]]
)


names(df_meta)[5] <- "Process of Meta Analysis"
names(df_meta)[6] <- "Result of Meta Analysis"

names(df_meta[[6]])[1] <- "Self - Close"
names(df_meta[[6]])[2] <- "Self - Stranger"

write.csv(x = df_meta[[6]][[1]], file = "./OUTPUT/meta/meta_close.csv")
write.csv(x = df_meta[[6]][[2]], file = "./OUTPUT/meta/meta_stranger.csv")
```

```{r}
res_meta[[3]] <- dplyr::bind_rows(
  res_meta[[1]]
) %>%
  dplyr::select(
    Target,
    Indice,
    Paper_ID,
    yi,
  ) %>%
  dplyr::left_join(
    desc[[1]],
    by = "Paper_ID"
  )

res_meta[[4]] <- dplyr::bind_rows(
  res_meta[[2]]
) %>%
  dplyr::select(
    Target,
    Indice,
    Paper_ID,
    yi,
  ) %>%
  dplyr::left_join(
    desc[[1]],
    by = "Paper_ID"
  )

write.csv(
  x = res_meta[[3]],
  file = "./OUTPUT/meta/meta_close_FEP.csv"
)
write.csv(
  x = res_meta[[4]],
  file = "./OUTPUT/meta/meta_stranger_FEP.csv"
)
```

