---
title: "7_Weighted Plot"
author: "yuki"
date: "2023-09-28"
output: html_document
---
# Create NULL List
```{r Create NULL List}
meta <- list()
```


################################################################################
--------------------------------------------------------------------------------
################################################################################


# DF
# Normal SHR
```{r}
meta[[1]] <- plot[[1]] %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  dplyr::mutate(
    unique_ID = paste(Target, Indice, Method, sep="_")
  ) %>%
  metafor::escalc(
    data = ., measure = "COR", ni = Trials, ri = r
  ) %>%
  metafor::aggregate.escalc(
    x = ., cluster = unique_ID, rho = 0
  ) %>%
  base::summary(
    
  ) %>%
  dplyr::select(
    Target, Indice, Method,
    yi, vi, sei, zi, pval,
    ci.lb, ci.ub
  ) %>%
  dplyr::mutate(
    pval = ifelse(
      pval < 0.001, "<.001", 
      ifelse(pval < 0.05, sprintf("%.3f", pval), sprintf("%.2f", pval))
    )
  ) %>% 
  dplyr::mutate(
    yi_r = round(yi, 2),
    ci.lb = round(ci.lb, 2),
    ci.ub = round(ci.ub, 2)
  ) %>%
  dplyr::mutate(
    CI = paste(yi_r, "(", ci.lb, ", ", ci.ub, ")", sep = "")
  )  %>% # 得到CI
  dplyr::mutate(
    .,
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target_Indice = paste(Target, Indice, sep = "_"), 
    Target_Indice = factor(Target_Indice)
  ) 
                
names(meta)[1] <- "Normal SHR"
```

## Permuted SHR
```{r}
meta[[2]] <- plot[[2]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::mutate(unique_ID = paste(Target, Indice, sep="_")) %>%
  #dplyr::filter(!(Trials < 60 & grepl("DDM", Indice))) %>%
  metafor::escalc(data = ., measure = "COR", ni = Trials, ri = r) %>%
  metafor::aggregate.escalc(x = ., cluster = unique_ID, rho = 0) %>%
  base::summary() %>%
  dplyr::select(Target, Indice, yi, vi, sei, zi, pval, ci.lb, ci.ub) %>%
  dplyr::mutate(pval = ifelse(pval < 0.001, "<.001", 
                       ifelse(pval < 0.05, sprintf("%.3f", pval), sprintf("%.2f", pval)))) %>% 
  dplyr::mutate(yi_r = round(yi, 2),
                ci.lb = round(ci.lb, 2),
                ci.ub = round(ci.ub, 2)) %>%
  dplyr::mutate(CI = paste(yi_r, "(", ci.lb, ", ", ci.ub, ")", sep = ""))  %>% # 得到CI
  dplyr::filter(!stringr::str_detect(Indice, "ez")) %>%
  dplyr::mutate(.,
                #Target = factor(Target,levels = c("Close", "Stranger", "Celebrity", "NonPerson")),
                #Indice = factor(Indice,levels = c("rwDDM z", "rwDDM v", "ezDDM z", "ezDDM v", "Efficiency", "d Prime", "ACC", "RT")),
                Indice = case_when(Indice == "Efficiency" ~ "η",
                                   Indice == "d Prime" ~ "d'",
                                   Indice == "rwDDM v" ~ "v",
                                   Indice == "rwDDM z" ~ "z",
                                   #Indice == "rwDDM v" ~ "v(RWiener)",
                                   #Indice == "rwDDM z" ~ "z(RWiener)",
                                   #Indice == "ezDDM v" ~ "v(hausekeep)",
                                   #Indice == "ezDDM z" ~ "z(hausekeep)",
                                   TRUE ~ Indice),
                #Indice = factor(Indice,levels = c("RT", "Efficiency", "ACC", "d'", "v", "z")),
                Target_Indice = paste(Target, Indice, sep = "_"), 
                Target_Indice = factor(Target_Indice)
                ) %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number())

names(meta)[2] <- "Permuted SHR"
```


################################################################################
--------------------------------------------------------------------------------
################################################################################

#Plot
## Main Plot
### Plot SHR
#### old
```{r}
p_shr <- meta[[2]] %>%
  dplyr::filter(
    Target %in% c("Close", "Stranger")
  ) %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(
    Outliar = case_when(ci.lb <= 0 ~ TRUE, 
                        ci.lb > 0 ~FALSE),
    ci.lb = ifelse(ci.lb < -0.10, -0.10, ci.lb), 
    Order = row_number()
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  #ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1, color = "black", linetype = Outliar) +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.3, 1.1),
                              breaks = c(0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -0.3, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Target, ncol = 2) +
  ggplot2::labs(y = "Split-Half Reliability", x = "") +
  ggplot2::ggtitle("(a)") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 15, family='serif'),
                 axis.text.x.bottom = element_text(size = 15, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 15, family='serif')
                 )

ggsave(filename = "./FIGURE/Fig2a_meta_shr.png",
       width = 10,
       height = 8,
       )
```

#### new
```{r}
p_shr <- meta[[2]] %>%
  dplyr::filter(
    Target %in% c("Close", "Stranger")
  ) %>%
  dplyr::arrange(wtmr) %>%
  dplyr::mutate(
    Order = row_number(),
    Target_Indice = paste(Target, Indice, sep="_")
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = wtmr)) +
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(limits = c(-0.3, 1.1),
                              breaks = c(0, 0.5, 0.7, 1),
                              sec.axis = sec_axis(~., breaks = c(0, 0.5, 0.7, 1),
                                                  labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
                              ) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -0.3, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Target, ncol = 2) +
  ggplot2::labs(y = "Split-Half Reliability", x = "") +
  ggplot2::ggtitle("(a)") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 15, family='serif'),
                 axis.text.x.bottom = element_text(size = 15, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 15, family='serif')
                 )

ggsave(filename = "./FIGURE/Fig2a_meta_shr(bar).png",
       width = 10,
       height = 8,
       )
```

### Plot ICC
#### old
```{r}
p_icc <- plot[[3]] %>%
  dplyr::filter(
    !stringr::str_detect(ICC_type, "ez")
  ) %>%
  dplyr::mutate(
    ICC_type = case_when(
      ICC_type == "Efficiency" ~ "η",
      ICC_type == "d Prime" ~ "d'",
      ICC_type == "rwDDM v" ~ "v",
      ICC_type == "rwDDM z" ~ "z",
      TRUE ~ ICC_type
    ),
    Target_Type = paste(
      Target, ICC_type, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("P0E1")),
    type == "ICC2"
  ) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(
    Order = row_number(),
    Outliar = case_when(LLCI <= 0 ~ TRUE, 
                        LLCI > 0 ~FALSE),
    LLCI = ifelse(LLCI < -0.10, -1.1, LLCI), 
  ) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC, group = Paper_ID, color = type)) + # nolint
  ggplot2::geom_errorbar(aes(color = type, ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.30, 1.10),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0.25, 0.625, 0.825, 0.95),
      labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.3, x = reorder(Target_Type, Order), label = Target_Type),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "Intraclass Correlation Coefficient 2", x = "") +
  ggplot2::ggtitle("(b)") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 #axis.title = element_blank(),
                 axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 15, family='serif'),
                 axis.text.x.bottom = element_text(size = 15, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 15, family='serif')
                 ) 
ggsave(filename = "./FIGURE/Fig2b_meta_icc.png",
       width = 10,
       height = 8,
       )
```

#### new
```{r}
p_icc <- plot[[3]] %>%
  dplyr::filter(
    !stringr::str_detect(ICC_type, "ez")
  ) %>%
  dplyr::mutate(
    ICC_type = case_when(
      ICC_type == "Efficiency" ~ "η",
      ICC_type == "d Prime" ~ "d'",
      ICC_type == "rwDDM v" ~ "v",
      ICC_type == "rwDDM z" ~ "z",
      TRUE ~ ICC_type
    ),
    Target_Type = paste(
      Target, ICC_type, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("P0E1")),
    type == "ICC2"
  ) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(
    Order = row_number(),
    Outliar = case_when(LLCI <= 0 ~ TRUE, 
                        LLCI > 0 ~FALSE),
    LLCI = ifelse(LLCI < -0.10, -1.1, LLCI), 
  ) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC, group = Paper_ID, color = type)) + # nolint
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.30, 1.10),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0.25, 0.625, 0.825, 0.95),
      labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.3, x = reorder(Target_Type, Order), label = Target_Type),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "Intraclass Correlation Coefficient 2", x = "") +
  ggplot2::ggtitle("(b)") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 #axis.title = element_blank(),
                 axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 15, family='serif'),
                 axis.text.x.bottom = element_text(size = 15, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 15, family='serif')
                 ) 
ggsave(filename = "./FIGURE/Fig2b_meta_icc(bar).png",
       width = 10,
       height = 8,
       )
```

### SHR + ICC
```{r}
p_shr_icc <- p_shr + p_icc + plot_layout(ncol = 1, guides = 'collect')

ggsave(plot = p_shr_icc,
       filename = "./FIGURE/Fig2_shr_icc.png",
       width = 10,
       height = 16,
       )
rm(p_shr_icc, p_shr, p_icc)
```

```{r}
p_shr_icc <- p_shr + p_icc + plot_layout(ncol = 1, guides = 'collect')

ggsave(plot = p_shr_icc,
       filename = "./FIGURE/Fig2_shr_icc(bar).png",
       width = 10,
       height = 16,
       )
rm(p_shr_icc, p_shr, p_icc)
```

## Supp. Plot (4 SHR)
```{r}
p1 <- meta[[1]] %>%
  dplyr::filter(Method == "First-Second") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1.5, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -1.5, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(a) First-Second Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

p2 <- meta[[1]] %>%
  dplyr::filter(Method == "Odd-Even") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1.5, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -1.5, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(b) Odd-Even Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

p3 <- meta[[1]] %>%
  dplyr::filter(Method == "Permuted") %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1.5, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -1.5, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(c) Permuted Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

p4 <- meta[[2]] %>%
  dplyr::arrange(yi) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = yi)) +
  ggplot2::geom_linerange(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1) +
  ggplot2::geom_point(shape=15, size = 2) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-1.5, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -1.5, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(d) Monte Carlo Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

p0 <- p1 + p2 + p3 + p4 + plot_layout(nrow = 2, guides = 'collect')

ggsave(plot = p0,
       filename = "./FIGURE/Fig1_meta.png",
       width = 20,
       height = 16,
       )
ggsave(plot = p1,
       filename = "./FIGURE/Fig1_meta_fs.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p2,
       filename = "./FIGURE/Fig1_meta_od.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p3,
       filename = "./FIGURE/Fig1_meta_per.png",
       width = 10,
       height = 8,
       )
ggsave(plot = p4,
       filename = "./FIGURE/Fig1_meta_mc.png",
       width = 10,
       height = 8,
       )

rm(p0, p1, p2, p3, p4)
```
