---
title: "5_Plot"
author: "yuki"
date: "2023-05-04"
output: html_document
---
## Figure S2: DDM Packages Comparison
### [./DDM_Packages_Comparison/DDM_Pack_Comp.Rmd]

## Figure S3: Meta Plot
### [./Meta_Plot.Rmd]

# Supp Plot
## Figure S4: Supp. SHR (per, fs, od)
```{r Aggregate Plot1}
aggr[[1]] <- plot[[1]] %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  #dplyr::filter(Paper_ID != "Ps1E1") %>%
  dplyr::mutate(
    .,
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target = factor(Target),
    Indice = factor(Indice),
    unique_ID = paste(Target, Indice, sep="_")
  ) 

temp <- base::split(x = aggr[[1]], f = list(aggr[[1]]$unique_ID))

result_df <- data.frame(
  unique_ID = character(0), 
  wtmr = numeric(0), 
  LLCI = numeric(0), 
  ULCI = numeric(0)
)

for (i in seq_along(temp)) {
  # 计算AATtools::cormean
  wtmr <- AATtools::cormean(r = temp[[i]]$r, n = temp[[i]]$Sample_Size, wts = "df")
  LLCI <- AATtools::cormean(r = temp[[i]]$LLCI, n = temp[[i]]$Sample_Size, wts = "df")
  ULCI <- AATtools::cormean(r = temp[[i]]$ULCI, n = temp[[i]]$Sample_Size, wts = "df")
  
  # 获取子集的元素名
  element_name <- names(temp)[i]
  
  # 将结果添加到数据框中
  result_df <- rbind(result_df, data.frame(
    unique_ID = element_name, 
    wtmr = wtmr,
    LLCI = LLCI,
    ULCI = ULCI
    )
  )
}

aggr[[1]] <- result_df %>%
  tidyr::separate(.,unique_ID, into = c("Target", "Indice"), sep = "_")

rm(temp, result_df, element_name, i, wtmr, LLCI, ULCI)
```

```{r Aggregate Plot2}
aggr[[2]] <- plot[[2]] %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  #dplyr::filter(Paper_ID != "Ps1E1") %>%
  dplyr::mutate(
    .,
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Method = factor(Method),
    Target = factor(Target),
    Indice = factor(Indice),
    unique_ID = paste(Target, Indice, Method, sep="_")
  ) 

temp <- base::split(x = aggr[[2]], f = list(aggr[[2]]$unique_ID))

result_df <- data.frame(unique_ID = character(0), wtmr = numeric(0))

for (i in seq_along(temp)) {
  # 计算AATtools::cormean
  wtmr <- AATtools::cormean(r = temp[[i]]$r, n = temp[[i]]$Sample_Size, wts = "df")
  
  # 获取子集的元素名
  element_name <- names(temp)[i]
  
  # 将结果添加到数据框中
  result_df <- rbind(result_df, data.frame(unique_ID = element_name, wtmr = wtmr))
}

aggr[[2]] <- result_df %>%
  tidyr::separate(.,unique_ID, into = c("Target", "Indice", "Method"), sep = "_")

rm(temp, result_df, element_name, i, wtmr)
```

```{r Plot}
###################################[errorbar]###################################

p0 <- aggr[[1]] %>%
  dplyr::arrange(wtmr) %>%
  dplyr::mutate(
    Target_Indice = paste(Target, Indice, sep="_"),
    Outliar = case_when(
      LLCI <= 0 ~ TRUE, 
      ULCI > 0 ~FALSE
    ),
    Order = row_number()
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = wtmr)) +
  ggplot2::geom_errorbar(aes(ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  #ggplot2::geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub), linewidth = 1, color = "black", linetype = Outliar) +
  ggplot2::geom_point(shape = 15, size = 3, color = "black") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.6, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -0.6, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(a) Permutated Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

#####################################[bar]######################################

p0 <- aggr[[1]] %>%
  dplyr::arrange(wtmr) %>%
  dplyr::mutate(
    Order = row_number(),
    Target_Indice = paste(Target, Indice, sep="_")
  ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = wtmr)) +
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.6, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -0.6, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(a) Permutated Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

p1 <- aggr[[2]] %>%
  dplyr::filter(Method == "First-Second") %>%
  dplyr::arrange(wtmr) %>%
  dplyr::mutate(
    Order = row_number(),
    Target_Indice = paste(Target, Indice, sep="_")
  ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = wtmr)) +
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.6, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -0.6, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(b) First-Second Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

p2 <- aggr[[2]] %>%
  dplyr::filter(Method == "Odd-Even") %>%
  dplyr::arrange(wtmr) %>%
  dplyr::mutate(
    Order = row_number(),
    Target_Indice = paste(Target, Indice, sep="_")
  ) %>%
  ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = wtmr)) +
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.6, 1),
    breaks = c(-1, 0, 0.5, 0.7, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0, 0.5, 0.7, 1),
      labels = c("Unacceptable", "Poor", "Acceptable", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 0.7, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + 
  ggplot2::geom_text(aes(y = -0.6, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  #ggplot2::facet_wrap(~Method, ncol = 1) +
  ggplot2::ggtitle("(c) Odd-Even Split-half") +
  ggplot2::labs(y = "", x = "") +
  #ggplot2::scale_fill_manual(values = c("#FEBE8C", "#97DBAE"))+ 
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none",
                 plot.title = element_text(size = 20, family = 'serif', hjust = 0),
                 axis.text.x.top = element_text(size = 12, family='serif'),
                 axis.text.x.bottom = element_text(size = 12, family='serif'),
                 axis.text.y.left = element_blank(),
                 axis.line.y.left = element_blank(),
                 axis.ticks.y.left = element_blank(),
                 axis.title.x = element_text(size = 12, family='serif'))

################################################################################

#p <- p0 + p1  + p2 + plot_layout(nrow = 2, guides = 'collect')

p0 <- p0 + plot_layout(widths = c(0.5))

# 合并三张图
p <- p0 / (p1 + p2) 

ggsave(plot = p,
       filename = "./FIGURE/Fig1_meta(bar).png",
       width = 20,
       height = 16,
       )
ggsave(plot = p0,
       filename = "./FIGURE/Fig1_meta_per(bar).png",
       width = 10,
       height = 8,
       )
ggsave(plot = p1,
       filename = "./FIGURE/Fig1_meta_fs(bar).png",
       width = 10,
       height = 8,
       )
ggsave(plot = p2,
       filename = "./FIGURE/Fig1_meta_od(bar).png",
       width = 10,
       height = 8,
       )

rm(p, p0, p1, p2)
```

## Figure S5: Supp ICC
```{r errorbar}
p1 <- plot[[3]] %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target_Indice = paste(
      Target, Indice, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("P0E1")),
    Type == "ICC2"
  ) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(
    Order = row_number(),
    Outliar = case_when(LLCI <= 0 ~ FALSE, 
                        LLCI > 0 ~TRUE),
    LLCI = ifelse(LLCI < -0.10, -1.1, LLCI), 
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = ICC, group = Paper_ID, color = Type)) + # nolint
  ggplot2::geom_errorbar(aes(color = Type, ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.40, 1),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0.25, 0.625, 0.825, 0.95),
      labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.4, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # CREATE Y
  ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  ggplot2::ggtitle("(a)") +
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
    axis.title.x = element_text(size = 15, family='serif'),
    axis.text.x.top = element_text(size = 15, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    plot.title = element_text(size = 20, family = 'serif', hjust = 0),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
  ) 


p2 <- plot[[3]] %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target_Indice = paste(
      Target, Indice, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("Ps2E1")),
    Type == "ICC2"
  ) %>%
  dplyr::arrange(ICC) %>%
  dplyr::mutate(
    Order = row_number(),
    Outliar = case_when(LLCI <= 0 ~ FALSE, 
                        LLCI > 0 ~TRUE),
    LLCI = ifelse(LLCI < -0.10, -0.10, LLCI), 
    ICC = ifelse(ICC < 0, -10, ICC), 
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Indice, Order), y = ICC, group = Paper_ID, color = Type)) + # nolint
  ggplot2::geom_errorbar(aes(color = Type, ymin = LLCI, ymax = ULCI, linetype = Outliar),
                         width = 0.1, size = 1, position = position_dodge(width = 1)) + # nolint
  ggplot2::geom_point(shape = 15, size = 3, position = position_dodge(width = 1)) +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.40, 1),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
    ~., breaks = c(0.25, 0.625, 0.825, 0.95),
    labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.4, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "", x = "") +
  ggplot2::ggtitle("(b)") +
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
    axis.title.x = element_text(size = 15, family='serif'),
    axis.text.x.top = element_text(size = 15, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    plot.title = element_text(size = 20, family = 'serif', hjust = 0),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
  ) 


ggsave(plot = p1,
       filename = "./FIGURE/Fig3a_ICC_P0.png",
       width = 10,
       height = 8,
       )

ggsave(plot = p2,
       filename = "./FIGURE/Fig3b_ICC_P0_Ps2.png",
       width = 10,
       height = 8,
       )

p <- p1 + p2 + plot_layout(ncol = 2, guides = 'collect')

ggsave(plot = p,
       filename = "./FIGURE/Fig3_ICC.png",
       width = 20,
       height = 8,
       )

rm(p, p1, p2)
```

```{r bar}
p1 <- plot[[3]] %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "d" ~ "d'",
      Indice == "v.RWiener." ~ "v(RWiener)",
      Indice == "z.RWiener." ~ "z(RWiener)",
      Indice == "v.hausekeep." ~ "v(hausekeep)",
      Indice == "z.hausekeep." ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target_Type = paste(
      Target, Indice, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("P0E1")),
  ) %>%
  dplyr::arrange(ICC.c) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC.c, group = Paper_ID)) + # nolint
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.60, 1),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
      ~., breaks = c(0.25, 0.625, 0.825, 0.95),
      labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.6, x = reorder(Target_Type, Order), label = Target_Type),
                     hjust = 0, size = 4, family='serif',) + # CREATE Y
  ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "Intraclass Correlation Coefficient 2 (Consistency)", x = "") +
  ggplot2::ggtitle("(a)") +
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
    axis.title.x = element_text(size = 15, family='serif'),
    axis.text.x.top = element_text(size = 15, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    plot.title = element_text(size = 20, family = 'serif', hjust = 0),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
  ) 


p2 <- plot[[3]] %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "d" ~ "d'",
      Indice == "v.RWiener." ~ "v(RWiener)",
      Indice == "z.RWiener." ~ "z(RWiener)",
      Indice == "v.hausekeep." ~ "v(hausekeep)",
      Indice == "z.hausekeep." ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target_Type = paste(
      Target, Indice, sep = "_"), 
  ) %>%
  dplyr::filter(
    (Paper_ID %in% c("Ps2E1")),
  ) %>%
  dplyr::arrange(ICC.c) %>%
  dplyr::mutate(
    Order = row_number(),
  ) %>%
ggplot2::ggplot(., aes(x = reorder(Target_Type, Order), y = ICC.c, group = Paper_ID)) + # nolint
  ggplot2::geom_bar(stat = "identity", color = "black", fill = "grey") +
  ggplot2::coord_flip() + #flips the x and y axes of a plot
  ggplot2::scale_x_discrete() +
  ggplot2::scale_y_continuous(
    limits = c(-0.60, 1),
    breaks = c(-1, 0, 0.5, 0.75, 0.9, 1),
    sec.axis = sec_axis(
    ~., breaks = c(0.25, 0.625, 0.825, 0.95),
    labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = -1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.6, x = reorder(Target_Type, Order), label = Target_Type),
                     hjust = 0, size = 4, family='serif',) + # 
  ggplot2::scale_linetype_manual(values = c("dashed", "solid")) +
  ggplot2::scale_fill_manual(values = c("black", "grey60")) +
  ggplot2::scale_color_manual(values = c("black", "grey60")) +
  #ggplot2::facet_wrap(~ type, ncol = 1) +
  ggplot2::labs(y = "Intraclass Correlation Coefficient 2 (Consistency)", x = "") +
  ggplot2::ggtitle("(b)") +
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
    axis.title.x = element_text(size = 15, family='serif'),
    axis.text.x.top = element_text(size = 15, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    plot.title = element_text(size = 20, family = 'serif', hjust = 0),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
  ) 


ggsave(plot = p1,
       filename = "./FIGURE/Fig3a_ICC_P0(bar).png",
       width = 10,
       height = 8,
       )

ggsave(plot = p2,
       filename = "./FIGURE/Fig3b_ICC_Ps2(bar).png",
       width = 10,
       height = 8,
       )

p <- p1 + p2 + plot_layout(ncol = 2, guides = 'collect')

ggsave(plot = p,
       filename = "./FIGURE/Fig3_ICC(bar).png",
       width = 20,
       height = 8,
       )

rm(p, p1, p2)
```

## Figure S6: ICC with & without COV
```{r}
plot[[5]] <- read.csv("./OUTPUT/icc/icc_cov_cmp.csv") %>%
  dplyr::mutate(
    Target = case_when(
      Target == "Friend" ~ "Close",
      Target == "Stranger" ~ "Stranger",
    ),
    Target = factor(
      Target,levels = c("Close", "Stranger")
    ),
    Indice = case_when(
      Indice == "d Prime" ~ "d'",
      Indice == "Efficiency" ~ "η",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Indice = factor(
      Indice, levels = c("z(hausekeep)", "v(hausekeep)", "z(RWiener)", "v(RWiener)", "η", "d'", "ACC", "RT")
    ),
    cov = case_when(
      cov == 0 ~ "Without",
      cov == 1 ~ "With"
    ),
    cov = factor(cov),
    Target_Indice = paste(Target, Indice, sep = "_"), 
    Target_Indice = factor(Target_Indice)
  ) %>%
  dplyr::arrange(
    ICC2
  ) %>%
  dplyr::mutate(
    Order = row_number()
  ) 
```

```{r}
ggplot2::ggplot(data = plot[[5]], aes(x = reorder(Target_Indice, Order), y = ICC2, fill = cov)) +
  ggplot2::geom_bar(stat = "Identity", position = "dodge") +
  ggplot2::scale_y_continuous(
    limits = c(-0.4,1.1),
    breaks = c(0, 0.5, 0.75, 0.9, 1),
    expand = c(0,0),
    sec.axis = sec_axis(
      ~., breaks = c(0.25, 0.625, 0.825, 0.95),
      labels = c("Poor", "Moderate", "Good", "Excellent")),
  ) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.5, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 0.9, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_hline(yintercept = 1, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::geom_text(aes(y = -0.4, x = reorder(Target_Indice, Order), label = Target_Indice),
                     hjust = 0, size = 4, family='serif',) + # 
  ggplot2::scale_fill_manual(values = c("grey30", "grey70")) +
  ggplot2::guides(fill = guide_legend(reverse = TRUE)) + # 改变图例顺序
  ggplot2::facet_wrap(facets = ~Type) +
  ggplot2::labs(fill = "Covariate(BDI-II Scores)", x = "", y = "") +
  ggplot2::coord_flip() +
  papaja::theme_apa() +
  ggplot2::theme(
    #legend.position = "none",
    axis.title = element_blank(),
    axis.ticks.x = element_line(color = "transparent"), #消除坐标轴上刻度凸起
    plot.title = element_text(size = 20, family = 'serif', hjust = 0),
    axis.text.x.top = element_text(size = 15, family='serif'),
    axis.text.x.bottom = element_text(size = 15, family='serif'),
    axis.text.y.left = element_blank(),
    axis.line.y.left = element_blank(),
    axis.ticks.y.left = element_blank(),
    axis.title.x = element_text(size = 15, family='serif')
  ) 

ggsave(filename = "./FIGURE/Figure_S6_Cov.png",
       width = 12,
       height = 8,
       )
```

## Figure S7: Correlation SHR & Trials 
```{r}
plot[[6]] <- plot[[1]] %>%
  dplyr::left_join(desc[[1]], by = "Paper_ID") %>%
  dplyr::filter(Target == "Close" | Target == "Stranger") %>%
  dplyr::filter(!(Paper_ID %in% c("P51E1"))) %>%
  dplyr::mutate(
    r_8 = case_when(
      Target == "Close" & Indice == "RT" ~ 120,
      Target == "Stranger" & Indice == "RT" ~ 72,
      Target == "Close" & Indice == "ACC" ~ 127,
      Target == "Close" & Indice == "Efficiency" ~ 107,
      Target == "Stranger" & Indice == "Efficiency" ~ 80,
      Target == "Close" & Indice == "ezDDM v" ~ 125,
      Target == "Stranger" & Indice == "ezDDM v" ~ 110,
      Target == "Close" & Indice == "rwDDM v" ~ 130,
      TRUE ~ NA),
  ) %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "d Prime" ~ "d'",
      Indice == "Efficiency" ~ "η",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target = factor(
      Target,levels = c("Close", "Stranger")
    ),
    Indice = factor(
      Indice, levels = c(
        "RT", "ACC", "d'", "η", 
        "v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)"
      )
    )
  )
```

```{r}
p1 <- plot[[6]] %>%
  dplyr::filter((Indice %in% c("RT", "ACC", "d'", "η"))) %>%
  ggplot2::ggplot(data = ., aes(x = Trials, y = r, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 3, label.y = 0.9, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(
    limits = c(0, 140),
    expand = c(0, 0),
    breaks = c(0, 30, 60, 100, 130),
  ) +
  ggplot2::scale_y_continuous(
    limits = c(-0.1, 1.1),
    expand = c(0, 0),
    breaks = c(0, 0.5, 0.8, 1),
  ) +
  #ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::labs(y = "Permutated Split-Half Reliability", x = "Trial Numbers") +
  #ggplot2::scale_color_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  #ggplot2::scale_fill_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  ggplot2::scale_color_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::scale_fill_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

################################################################################
################################################################################

p2 <- plot[[6]] %>%
  dplyr::filter((Indice %in% c("v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)"))) %>%
  ggplot2::ggplot(data = ., aes(x = Trials, y = r, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 3, label.y = 0.9, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(
    limits = c(0, 140),
    expand = c(0, 0),
    breaks = c(0, 30, 60, 100, 130),
  ) +
  ggplot2::scale_y_continuous(
    limits = c(-0.1, 1.1),
    expand = c(0, 0),
    breaks = c(0, 0.5, 0.8, 1),
  ) +
  #ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::labs(y = "", x = "Trial Numbers") +
  #ggplot2::scale_color_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  #ggplot2::scale_fill_manual(values = c("grey50", "grey50", "grey50", "grey50")) +
  ggplot2::scale_color_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::scale_fill_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")


#################################### SAVE ######################################
p3 <- p1 + p2 + plot_layout(guides = 'collect')

ggsave(filename = "./FIGURE/Figure_S7_r&Trial.png",
       width = 10,
       height = 8,
       )
#################################### SAVE ######################################

rm(p1, p2, p3)
```

## Figure S8: Correlation Hedges'g & SHR
```{r}
temp_plot <- plot[[1]] %>%
  dplyr::filter(
    Target %in% c("Close", "Stranger")
  ) %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
  ) %>%
  dplyr::select(
    Target,
    Indice,
    Paper_ID,
    r
  )

close <- read.csv("./OUTPUT/meta/meta_close_FEP.csv")
stranger <- read.csv("./OUTPUT/meta/meta_stranger_FEP.csv")
temp_meta <- bind_rows(close, stranger) %>%
  dplyr::select(
    Target,
    Indice,
    Paper_ID,
    yi,
    Trials
  ) %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "eta" ~ "η",
      Indice == "d" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
  ) 

plot[[7]] <- temp_plot %>%
  dplyr::left_join(
    temp_meta,
    by = c(
      "Target",
      "Indice",
      "Paper_ID"
    )
  ) %>%
  dplyr::mutate(
    yi = case_when(
      Indice == "RT" ~ yi * -1,
      Indice == "ACC" ~ yi,
      Indice == "d'" ~ yi,
      Indice == "η" ~ yi * -1,
      Indice == "v(hausekeep)" ~ yi,
      Indice == "z(hausekeep)" ~ yi,
      Indice == "v(RWiener)" ~ yi,
      Indice == "z(RWiener)" ~ yi, 
    ),
    Target = factor(
      Target,levels = c("Close", "Stranger")
    ),
    Indice = factor(
      Indice, levels = c("RT", "ACC", "d'", "η", "v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)")
    )
  ) 

rm(temp_meta, temp_plot, close, stranger)
```

```{r}
p1 <- plot[[7]] %>%
  dplyr::filter((Indice %in% c("RT", "ACC", "d'", "η"))) %>%
  ggplot2::ggplot(data = ., aes(x = yi, y = r, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 0, label.y = 0.9, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(
    limits = c(-0.5, 2), 
  ) +
   ggplot2::scale_y_continuous(
    limits = c(0, 1),
    expand = c(0, 0),
    breaks = c(0, 0.5, 0.7, 1),
  ) +
  #ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::labs(y = "Permutated Split-Half Reliability", x = expression("Hedges' " * italic(g))) +
  ggplot2::scale_color_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::scale_fill_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")


p2 <- plot[[7]] %>%
  dplyr::filter((Indice %in% c("v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)"))) %>%
  ggplot2::ggplot(data = ., aes(x = yi, y = r, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 0, label.y = 0.9, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(
    limits = c(-0.5, 2), 
  ) +
   ggplot2::scale_y_continuous(
    limits = c(0, 1),
    expand = c(0, 0),
    breaks = c(0, 0.5, 0.7, 1),
  ) +
  #ggplot2::geom_hline(yintercept = 0.8, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::labs(y = "", x = expression("Hedges' " * italic(g))) +
  ggplot2::scale_color_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::scale_fill_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

p3 <- p1 + p2 + plot_layout(guides = 'collect')

ggplot2::ggsave(
  plot = p3,
  filename = "./FIGURE/Figure_S8_yi&r.png",
  width = 10,
  height = 8,
)

rm(p1, p2, p3)
```

## Figure S9: Correlation Hedges'g & Trials
```{r}
close <- read.csv("./OUTPUT/meta/meta_close_FEP.csv")
stranger <- read.csv("./OUTPUT/meta/meta_stranger_FEP.csv")

plot[[8]] <- dplyr::bind_rows(close, stranger) %>%
  dplyr::mutate(
    Indice = case_when(
      Indice == "d" ~ "d'",
      Indice == "eta" ~ "η",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    yi = case_when(
      Indice == "RT" ~ yi * -1,
      Indice == "ACC" ~ yi,
      Indice == "d'" ~ yi,
      Indice == "η" ~ yi * -1,
      Indice == "v(hausekeep)" ~ yi,
      Indice == "z(hausekeep)" ~ yi,
      Indice == "v(RWiener)" ~ yi,
      Indice == "z(RWiener)" ~ yi, 
    ),
    Target = factor(
      Target,levels = c("Close", "Stranger")
    ),
    Indice = factor(
      Indice, levels = c("RT", "ACC", "d'", "η", "v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)")
    )
  )

rm(close, stranger)

names(plot)[8] <- "Correlation (yi & Trials)"
```

```{r}
pic1 <- plot[[8]] %>%
  dplyr::filter((Indice %in% c("RT", "ACC", "d'", "η"))) %>%
  ggplot2::ggplot(data = ., aes(x = Trials, y = yi, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 3, label.y = 2, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(
    limits = c(0, 140),
    expand = c(0, 0),
    breaks = c(0, 30, 60, 100, 130),
  ) +
  ggplot2::scale_y_continuous(
    limits = c(-0.5, 2),
    breaks = c(-0.5, 0, 0.5, 1, 1.5, 2)
  ) +
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::scale_color_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::scale_fill_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::labs(y = expression("Hedges' " * italic(g)), x = "Trial Numbers") +  
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

pic2 <- plot[[8]] %>%
  dplyr::filter((Indice %in% c("v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)"))) %>%
  ggplot2::ggplot(data = ., aes(x = Trials, y = yi, color = Indice, fill = Indice)) +
  ggplot2::geom_point() +  # 添加散点
  ggplot2::geom_smooth(method = "lm", se = TRUE, fullrange = TRUE) +  # 添加拟合曲线
  ggpubr::stat_cor(label.x = 3, label.y = 2, r.accuracy = .01, p.accuracy = .01) +
  ggplot2::scale_x_continuous(
    limits = c(0, 140),
    expand = c(0, 0),
    breaks = c(0, 30, 60, 100, 130),
  ) +
  ggplot2::scale_y_continuous(
    limits = c(-0.5, 2),
    breaks = c(-0.5, 0, 0.5, 1, 1.5, 2)
  ) +
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::scale_color_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::scale_fill_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::labs(y = "", x = "Trial Numbers") +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")
  
pic <- pic1 + pic2 + plot_layout(guides = 'collect')

ggsave(
  filename = "./FIGURE/Figure_S9cor_yi&trials.png",
  width = 10,
  height = 8,
)

rm(pic1, pic2, pic)
```

```{r}
spearman_cor <- plot[[8]] %>%
  dplyr::group_by(Target, Indice) %>%
  dplyr::summarise(cor = cor(Trials, yi, method = "spearman"))
```

## Figure S10: Needed Trials
```{r}
################################################################################
plot[[9]] <- plot[[1]] %>%
  dplyr::left_join(
    desc[[1]], by = "Paper_ID"
  ) %>%
  #dplyr::filter(Paper_ID != "Ps1E1") %>%
  dplyr::mutate(
    .,
    Indice = case_when(
      Indice == "Efficiency" ~ "η",
      Indice == "d Prime" ~ "d'",
      #Indice == "rwDDM v" ~ "v",
      #Indice == "rwDDM z" ~ "z",
      Indice == "rwDDM v" ~ "v(RWiener)",
      Indice == "rwDDM z" ~ "z(RWiener)",
      Indice == "ezDDM v" ~ "v(hausekeep)",
      Indice == "ezDDM z" ~ "z(hausekeep)",
      TRUE ~ Indice
    ),
    Target = factor(Target),
    Indice = factor(Indice),
    unique_ID = paste(Target, Indice, sep="_")
  ) 

temp <- base::split(x = plot[[9]], f = list(plot[[9]]$unique_ID))

result_df <- data.frame(
  unique_ID = character(0), 
  wtm_r = numeric(0), 
  wtm_t = numeric(0), 
  LLCI = numeric(0), 
  ULCI = numeric(0)
  
)

for (i in seq_along(temp)) {
  # 计算AATtools::cormean
  wtm_r <- AATtools::cormean(r = temp[[i]]$r, n = temp[[i]]$Sample_Size, wts = "df")
  wtm_t <- stats::weighted.mean(x = temp[[i]]$Trials, w = temp[[i]]$Sample_Size)
  LLCI <- AATtools::cormean(r = temp[[i]]$LLCI, n = temp[[i]]$Sample_Size, wts = "df")
  ULCI <- AATtools::cormean(r = temp[[i]]$ULCI, n = temp[[i]]$Sample_Size, wts = "df")
  
  # 获取子集的元素名
  element_name <- names(temp)[i]
  
  # 将结果添加到数据框中
  result_df <- rbind(result_df, data.frame(
    unique_ID = element_name, 
    wtm_r = wtm_r,
    wtm_t = wtm_t,
    LLCI = LLCI,
    ULCI = ULCI
    )
  )
}

# 创建一个空的数据框
plot[[9]] <- result_df %>%
  tidyr::separate(.,unique_ID, into = c("Target", "Indice"), sep = "_") %>%
  dplyr::mutate(
    Trial_10 = ( 0.1 - 0.1 * wtm_r) / (wtm_r - 0.1 * wtm_r) * wtm_t,
    LLCI_10 = ( 0.1 - 0.1 * ULCI) / (ULCI - 0.1 * ULCI) * wtm_t,
    ULCI_10 = ( 0.1 - 0.1 * LLCI) / (LLCI - 0.1 * LLCI) * wtm_t,
    
    Trial_20 = ( 0.2 - 0.2 * wtm_r) / (wtm_r - 0.2 * wtm_r) * wtm_t,
    LLCI_20 = ( 0.2 - 0.2 * ULCI) / (ULCI - 0.2 * ULCI) * wtm_t,
    ULCI_20 = ( 0.2 - 0.2 * LLCI) / (LLCI - 0.2 * LLCI) * wtm_t,

    Trial_30 = ( 0.3 - 0.3 * wtm_r) / (wtm_r - 0.3 * wtm_r) * wtm_t,
    LLCI_30 = ( 0.3 - 0.3 * ULCI) / (ULCI - 0.3 * ULCI) * wtm_t,
    ULCI_30 = ( 0.3 - 0.3 * LLCI) / (LLCI - 0.3 * LLCI) * wtm_t,	

    Trial_40 = ( 0.4 - 0.4 * wtm_r) / (wtm_r - 0.4 * wtm_r) * wtm_t,
    LLCI_40 = ( 0.4 - 0.4 * ULCI) / (ULCI - 0.4 * ULCI) * wtm_t,
    ULCI_40 = ( 0.4 - 0.4 * LLCI) / (LLCI - 0.4 * LLCI) * wtm_t,	

    Trial_50 = ( 0.5 - 0.5 * wtm_r) / (wtm_r - 0.5 * wtm_r) * wtm_t,
    LLCI_50 = ( 0.5 - 0.5 * ULCI) / (ULCI - 0.5 * ULCI) * wtm_t,
    ULCI_50 = ( 0.5 - 0.5 * LLCI) / (LLCI - 0.5 * LLCI) * wtm_t,		

    Trial_60 = ( 0.6 - 0.6 * wtm_r) / (wtm_r - 0.6 * wtm_r) * wtm_t,
    LLCI_60 = ( 0.6 - 0.6 * ULCI) / (ULCI - 0.6 * ULCI) * wtm_t,
    ULCI_60 = ( 0.6 - 0.6 * LLCI) / (LLCI - 0.6 * LLCI) * wtm_t,		
    
    Trial_70 = ( 0.7 - 0.7 * wtm_r) / (wtm_r - 0.7 * wtm_r) * wtm_t,
    LLCI_70 = ( 0.7 - 0.7 * ULCI) / (ULCI - 0.7 * ULCI) * wtm_t,	
    ULCI_70 = ( 0.7 - 0.7 * LLCI) / (LLCI - 0.7 * LLCI) * wtm_t,		

    Trial_80 = ( 0.8 - 0.8 * wtm_r) / (wtm_r - 0.8 * wtm_r) * wtm_t,
    LLCI_80 = ( 0.8 - 0.8 * ULCI) / (ULCI - 0.8 * ULCI) * wtm_t,	
    ULCI_80 = ( 0.8 - 0.8 * LLCI) / (LLCI - 0.8 * LLCI) * wtm_t,		
    
    Trial_90 = ( 0.9 - 0.9 * wtm_r) / (wtm_r - 0.9 * wtm_r) * wtm_t,
    LLCI_90 = ( 0.9 - 0.9 * ULCI) / (ULCI - 0.9 * ULCI) * wtm_t,	
    ULCI_90 = ( 0.9 - 0.9 * LLCI) / (LLCI - 0.9 * LLCI) * wtm_t,	
	

  ) %>%
  dplyr::select(-wtm_r, -wtm_t, -LLCI, -ULCI)

################################################################################

Mean <- plot[[9]] %>%
  dplyr::select(
    Target, Indice, contains("Trial_")
  ) %>%
  tidyr::pivot_longer(
    cols = starts_with("Trial_"), 
    names_to = "r_Expected",
    values_to = "Mean"
  ) %>%
  dplyr::mutate(
    r_Expected = str_remove(r_Expected, "Trial_"),
    r_Expected = as.numeric(r_Expected) / 100
  )

LLCI <- plot[[9]] %>%
  dplyr::select(
    Target, Indice, contains("LLCI_")
  ) %>%
  tidyr::pivot_longer(
    cols = starts_with("LLCI_"), 
    names_to = "r_Expected",
    values_to = "LLCI"
  ) %>%
  dplyr::mutate(
    r_Expected = str_remove(r_Expected, "LLCI_"),
    r_Expected = as.numeric(r_Expected) / 100
  )

ULCI <- plot[[9]] %>%
  dplyr::select(
    Target, Indice, contains("ULCI_")
  ) %>%
  tidyr::pivot_longer(
    cols = starts_with("ULCI_"), 
    names_to = "r_Expected",
    values_to = "ULCI"
  ) %>%
  dplyr::mutate(
    r_Expected = str_remove(r_Expected, "ULCI_"),
    r_Expected = as.numeric(r_Expected) / 100
  )

temp <- merge(Mean, LLCI, by = c("Target", "Indice", "r_Expected"), all.x = TRUE)
temp <- merge(temp, ULCI, by = c("Target", "Indice", "r_Expected"), all.x = TRUE)

rm(Mean, LLCI, ULCI)

plot[[9]] <- temp %>%
  dplyr::mutate(
    Target = factor(
      Target,levels = c("Close", "Stranger", "Celebrity", "NonPerson")
    ),
    Indice = factor(
      Indice, 
      levels = c(
        "RT", "ACC", "d'", "η", "v(RWiener)", 
        "z(RWiener)", "v(hausekeep)", "z(hausekeep)"
      )
    )
  )

rm(temp)

names(plot)[9] <- "Spearman-Brown"
```

```{r}
pic1 <- plot[[9]] %>%
  dplyr::filter(
    Target %in% c("Close", "Stranger"),
    (Indice %in% c("RT", "ACC", "d'", "η")),
  ) %>%
  dplyr::mutate(
    Mean = case_when(
      Mean >= 300 ~ 300,
      TRUE ~ Mean,
    ),
    LLCI = case_when(
      LLCI >= 300 ~ 300,
      TRUE ~ LLCI,
    ),
    ULCI = case_when(
      ULCI >= 300 ~ 300,
      TRUE ~ ULCI,
    )
  ) %>%
  ggplot2::ggplot(
    data = ., 
    mapping = aes(
      x = Mean, y = r_Expected, 
      color = Indice, fill = Indice
    )
  ) +
  ggplot2::geom_ribbon(
    aes(xmin = ULCI, xmax = LLCI, fill = Indice),
    linetype = "dashed", alpha = 0.3
  ) +
  ggplot2::geom_line() +
  ggplot2::scale_y_continuous(
    limits = c(0, 1),
    expand = c(0, 0),
    breaks = c(0, 0.5, 0.7, 0.9),
  ) +
  ggplot2::scale_x_continuous(
    limits = c(0, 300),
    expand = c(0, 0),
    breaks = c(0, 60, 120, 180, 240)
  ) +
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::scale_color_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::scale_fill_manual(values = c("#F8766D", "#CD9600", "#7AAC00", "#03BE66")) +
  ggplot2::labs(
    x = "Expected Trial Numbers", 
    y = "Expected Spli-Half Reliability",
  ) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

pic2 <- plot[[9]] %>%
  dplyr::filter(
    Target %in% c("Close", "Stranger"),
    Indice %in% c("v(RWiener)", "z(RWiener)", "v(hausekeep)", "z(hausekeep)")
  ) %>%
  dplyr::mutate(
    Mean = case_when(
      Mean >= 300 ~ 300,
      TRUE ~ Mean,
    ),
    LLCI = case_when(
      LLCI >= 300 ~ 300,
      TRUE ~ LLCI,
    ),
    ULCI = case_when(
      ULCI >= 300 ~ 300,
      TRUE ~ ULCI,
    )
  ) %>%
  ggplot2::ggplot(
    data = ., 
    mapping = aes(
      x = Mean, y = r_Expected, 
      color = Indice, fill = Indice
    )
  ) +
  ggplot2::geom_ribbon(
    aes(xmin = ULCI, xmax = LLCI, fill = Indice),
    linetype = "dashed", alpha = 0.3
  ) +
  ggplot2::geom_line() +
  ggplot2::scale_y_continuous(
    limits = c(0, 1),
    expand = c(0, 0),
    breaks = c(0, 0.5, 0.7, 0.9),
  ) +
  ggplot2::scale_x_continuous(
    limits = c(0, 300),
    expand = c(0, 0),
    breaks = c(0, 60, 120, 180, 240)
  ) +
  ggplot2::facet_grid(cols = vars(Target), rows = vars(Indice)) +
  ggplot2::geom_hline(yintercept = 0.75, linetype = "dotted", color = "black", linewidth = 1, alpha = 0.5) + # nolint
  ggplot2::scale_color_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::scale_fill_manual(values = c("#00BFC4", "#00A8FF", "#C678FF", "#FF60CC")) +
  ggplot2::labs(
    x = "Expected Trial Numbers", 
    y = "Expected Spli-Half Reliability",
  ) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")

pic <- pic1 + pic2 + plot_layout(guides = 'collect')

ggsave(
  filename = "./FIGURE/Figure_S10Spear_Brown.png",
  width = 10,
  height = 8,
)

rm(pic1, pic2, pic)
```

