---
title: "Untitled"
author: "yuki"
date: "2023-06-24"
output: html_document
---
```{r}
# Clean Data
library(tidyr)
library(dplyr)
# More efficient
library(data.table)
# for ICC
library(psych)
# for DDM
library(hausekeep) # EZ-DDM
library(RWiener) # RW-DDM
# Parallel Computing
library(foreach)
library(parallel)
library(iterators)
library(doParallel)
# My Packages
library(yukiSH)
library(yukiBP)
```

```{r List for Data Frame}
#df <- list()
df[[1]] <- read.csv("./DATA/df_1.csv")
df[[2]] <- read.csv("./DATA/df_2.csv")
df[[3]] <- read.csv("./DATA/df_3.csv")
df[[4]] <- read.csv("./DATA/df_4.csv")
df[[5]] <- read.csv("./DATA/df_5.csv")
df[[6]] <- read.csv("./DATA/df_6.csv")
df[[7]] <- read.csv("./DATA/df_7.csv")
df[[8]] <- read.csv("./DATA/df_8.csv")
df[[9]] <- read.csv("./DATA/df_9.csv")
df[[10]] <- read.csv("./DATA/df_10.csv")
df[[11]] <- read.csv("./DATA/df_11.csv")
df[[12]] <- read.csv("./DATA/df_12.csv")
df[[13]] <- read.csv("./DATA/df_13.csv")
df[[14]] <- read.csv("./DATA/df_14.csv")
df[[15]] <- read.csv("./DATA/df_15.csv")
df[[16]] <- read.csv("./DATA/df_16.csv")
df[[17]] <- read.csv("./DATA/df_17.csv")
df[[18]] <- read.csv("./DATA/df_18.csv")
df[[19]] <- read.csv("./DATA/df_19.csv")
df[[20]] <- read.csv("./DATA/df_20.csv")
df[[21]] <- read.csv("./DATA/df_21.csv")
df[[22]] <- read.csv("./DATA/df_22.csv")
df[[23]] <- read.csv("./DATA/df_23.csv")
df[[24]] <- read.csv("./DATA/df_24.csv")
df[[25]] <- read.csv("./DATA/df_25.csv")
df[[26]] <- read.csv("./DATA/df_26.csv")
df[[27]] <- read.csv("./DATA/df_27.csv")
df[[28]] <- read.csv("./DATA/df_28.csv")
df[[29]] <- read.csv("./DATA/df_29.csv")
df[[30]] <- read.csv("./DATA/df_30.csv")
df[[31]] <- read.csv("./DATA/df_31.csv")
df[[32]] <- read.csv("./DATA/df_32.csv")
df[[33]] <- read.csv("./DATA/df_33.csv")
df[[34]] <- read.csv("./DATA/df_34.csv")

df[[35]] <- read.csv("./DATA/df_35.csv")
df[[36]] <- read.csv("./DATA/df_36.csv")
df[[37]] <- read.csv("./DATA/df_37.csv")
df[[38]] <- read.csv("./DATA/df_38.csv")
df[[39]] <- read.csv("./DATA/df_39.csv")
df[[40]] <- read.csv("./DATA/df_40.csv")
df[[41]] <- read.csv("./DATA/df_41.csv")
```

```{r List for Paper ID}
p <- list()
p[[1]] <- "P0E1"
p[[2]] <- "P6E1"
p[[3]] <- "P46E2"
p[[4]] <- "P51E1"
p[[5]] <- "P51E2"
p[[6]] <- "P54E1"
p[[7]] <- "P54E3"
p[[8]] <- "Pn4E1"
p[[9]] <- "Pn13E1"
p[[10]] <- "Pn13E3"
p[[11]] <- "Pn13E4"
p[[12]] <- "Pn16E1"
p[[13]] <- "Pn16E2"
p[[14]] <- "Pn16E3"
p[[15]] <- "Pn23E1"

p[[16]] <- "P95E1"
p[[17]] <- "P95E2"
p[[18]] <- "Ps1E1"
p[[19]] <- "Ps2E1"
p[[20]] <- "Ps3E1"
p[[21]] <- "Ps4E1"
p[[22]] <- "Ps4E2"
p[[23]] <- "Ps5E1"
p[[24]] <- "Ps5E2"
p[[25]] <- "Ps5E3"
p[[26]] <- "Ps5E4"

p[[27]] <- "Pt1E1"
p[[28]] <- "Pt2E1"
p[[29]] <- "Pt3E1"
p[[30]] <- "Pt6E1"
p[[31]] <- "Pt6E2"
p[[32]] <- "Pt9E1"
p[[33]] <- "Pt9E2"
p[[34]] <- "Pt9E3"

p[[35]] <- "Pt10E1"
p[[36]] <- "Pt18E1"
p[[37]] <- "P19E1"
p[[38]] <- "P19E2"
p[[39]] <- "P34E1"
p[[40]] <- "P44E1"
p[[41]] <- "Pt27E1"
```

```{r List for Target}
t <- list()
t[[1]] <- c("Self", "Friend", "Stranger")
t[[2]] <- c("Self", "Partner", "Stranger")
t[[3]] <- c("Self", "Stranger")
t[[4]] <- c("Self", "Celebrity", "Stranger")
t[[5]] <- c("Self", "Celebrity")
t[[6]] <- c("Self", "Mother", "none", "Acquaintance")
t[[7]] <- c("Self", "Mother", "Acquaintance")
t[[8]] <- c("Self", "Friend", "Stranger")
t[[9]] <- c("Self", "Friend", "Stranger")
t[[10]] <- c("Self", "Father", "Stranger")
t[[11]] <- c("Self", "Friend", "Stranger")
t[[12]] <- c("Self", "Friend")
t[[13]] <- c("Self", "Friend")
t[[14]] <- c("Self", "Friend")
t[[15]] <- c("Self", "Friend", "Stranger")

t[[16]] <- c("Self", "Friend", "Stranger")
t[[17]] <- c("Self", "Friend", "Stranger")
t[[18]] <- c("Self", "Stranger")
t[[19]] <- c("Self", "Stranger")
t[[20]] <- c("Self", "Friend", "Stranger")
t[[21]] <- c("Self", "Friend", "Stranger")
t[[22]] <- c("Self", "Friend", "Stranger")
t[[23]] <- c("Self", "Mother", "Stranger")
t[[24]] <- c("Self", "Mother", "Stranger")
t[[25]] <- c("Self", "Mother", "Stranger")
t[[26]] <- c("Self", "Mother", "Stranger")

t[[27]] <- c("Self", "Stranger")
t[[28]] <- c("Self", "Friend", "Stranger")
t[[29]] <- c("Self", "Friend", "Stranger")
t[[30]] <- c("Self", "Stranger")
t[[31]] <- c("Self", "Stranger")
t[[32]] <- c("Self", "Friend", "None")
t[[33]] <- c("Self", "Friend", "None")
t[[34]] <- c("Self", "Friend", "None")

t[[35]] <- c("Self", "Stranger")
t[[36]] <- c("Self", "Friend", "Stranger")
t[[37]] <- c("Self", "Friend", "Stranger")
t[[38]] <- c("Self", "Friend", "Stranger")
t[[39]] <- c("Self", "Friend", "Stranger")
t[[40]] <- c("Self", "Friend", "Stranger")
t[[41]] <- c("Self", "Friend", "Stranger")

```

```{r lazy_nmshr}
lazy_nmshr <- function(Target, Paper_ID, nc) {

  # 计算8个参数的分半信度
  df_rt <- yukiBP::shr(list = shl[1:2], Target = Target, Paper_ID = Paper_ID, Indice = "rt", mc = FALSE, nc = nc) # nolint 
  df_acc <- yukiBP::shr(list = shl[1:2], Target = Target, Paper_ID = Paper_ID, Indice = "acc", mc = FALSE, nc = nc) # nolint 
  df_dp <- yukiBP::shr(list = shl[1:2], Target = Target, Paper_ID = Paper_ID, Indice = "dp", mc = FALSE, nc = nc) # nolint 
  df_eff <- yukiBP::shr(list = shl[1:2], Target = Target, Paper_ID = Paper_ID, Indice = "eff", mc = FALSE, nc = nc) # nolint 
  df_ezddm <- yukiBP::shr(list = shl[1:2], Target = Target, Paper_ID = Paper_ID, Indice = "ezddm", mc = FALSE, nc = nc) # nolint 
  df_rwddm <- yukiBP::shr(list = shl[1:2], Target = Target, Paper_ID = Paper_ID, Indice = "rwddm", mc = FALSE, nc = nc) # nolint 

  # 合并8个参数到一个表格内
  result <- rbind(
    df_rt, df_acc, df_dp, df_eff, df_ezddm, df_rwddm
  ) %>%
    dplyr::mutate(
      Indice = case_when(
        Indice == "rt" ~ "RT",
        Indice == "acc" ~ "ACC",
        Indice == "dp" ~ "d Prime",
        Indice == "eff" ~ "Efficiency",
        Indice == "ez_v" ~ "ezDDM v",
        Indice == "ez_z" ~ "ezDDM z",
        Indice == "rw_v" ~ "rwDDM v",
        Indice == "rw_z" ~ "rwDDM z",
      )
  ) %>%
    dplyr::mutate(
      Indice = factor(
        Indice, levels = c(
          "RT", "ACC", "d Prime", "Efficiency",
          "ezDDM v", "ezDDM z", "rwDDM v", "rwDDM z"
        )
      ),
      Method = factor(
        Method, levels = c("First-Second", "Odd-Even", "Permuted")
      ),
      Target = factor(Target),
    ) %>%
    dplyr::select(
      Target, Indice, Method, r, Paper_ID
    ) %>%
    dplyr::arrange(
      Target, Indice, Method
    )

  # 保存生成的表格
  Path <- paste0("./nmshr_", Paper_ID, ".csv")
  write.csv(x = result, file = Path, row.names = FALSE)

}
```

```{r lazy_pershr}
lazy_pershr <- function(Target, Paper_ID, nc) {

  # 计算8个参数的分半信度
  df_rt <- yukiBP::shr(list = shl[[3]], Target = Target, Paper_ID = Paper_ID, Indice = "rt", mc = TRUE, nc = nc) # nolint
  df_acc <- yukiBP::shr(list = shl[[3]], Target = Target, Paper_ID = Paper_ID, Indice = "acc", mc = TRUE, nc = nc) # nolint
  df_dp <- yukiBP::shr(list = shl[[3]], Target = Target, Paper_ID = Paper_ID, Indice = "dp", mc = TRUE, nc = nc) # nolint
  df_eff <- yukiBP::shr(list = shl[[3]], Target = Target, Paper_ID = Paper_ID, Indice = "eff", mc = TRUE, nc = nc) # nolint
  df_ezddm <- yukiBP::shr(list = shl[[3]], Target = Target, Paper_ID = Paper_ID, Indice = "ezddm", mc = TRUE, nc = nc) # nolint
  df_rwddm <- yukiBP::shr(list = shl[[3]], Target = Target, Paper_ID = Paper_ID, Indice = "rwddm", mc = TRUE, nc = nc) # nolint

  # 合并8个参数到一个表格内
  result <- rbind(df_rt, df_acc, df_dp, df_eff, df_ezddm, df_rwddm) %>%
    dplyr::mutate(
      Indice = case_when(
        Indice == "rt" ~ "RT",
        Indice == "acc" ~ "ACC",
        Indice == "dp" ~ "d Prime",
        Indice == "eff" ~ "Efficiency",
        Indice == "ez_v" ~ "ezDDM v",
        Indice == "ez_z" ~ "ezDDM z",
        Indice == "rw_v" ~ "rwDDM v",
        Indice == "rw_z" ~ "rwDDM z",
      )
    ) %>%
    dplyr::mutate(
      Indice = factor(
        Indice, levels = c(
          "RT", "ACC", "d Prime", "Efficiency",
          "ezDDM v", "ezDDM z", "rwDDM v", "rwDDM z"
        )
      ),
        Target = factor(Target),
    ) %>%
    dplyr::select(
      Target, Indice, r, LLCI, ULCI, Paper_ID
    ) %>%
    dplyr::arrange(
      Target, Indice
    )

  # 保存生成的表格
  Path <- paste0("./pershr_", Paper_ID, ".csv")
  write.csv(x = result, file = Path, row.names = FALSE)

}
```

```{r lazy_mcshr}
lazy_mcshr <- function(Target, Paper_ID, nc) {

  # 计算8个参数的分半信度
  df_rt <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "rt", mc = TRUE, nc = nc) # nolint
  df_acc <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "acc", mc = TRUE, nc = nc) # nolint
  df_dp <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "dp", mc = TRUE, nc = nc) # nolint
  df_eff <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "eff", mc = TRUE, nc = nc) # nolint
  df_ezddm <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "ezddm", mc = TRUE, nc = nc) # nolint
  df_rwddm <- yukiBP::shr(list = shl[[4]], Target = Target, Paper_ID = Paper_ID, Indice = "rwddm", mc = TRUE, nc = nc) # nolint

  # 合并8个参数到一个表格内
  result <- rbind(df_rt, df_acc, df_dp, df_eff, df_ezddm, df_rwddm) %>%
    dplyr::mutate(
      Indice = case_when(
        Indice == "rt" ~ "RT",
        Indice == "acc" ~ "ACC",
        Indice == "dp" ~ "d Prime",
        Indice == "eff" ~ "Efficiency",
        Indice == "ez_v" ~ "ezDDM v",
        Indice == "ez_z" ~ "ezDDM z",
        Indice == "rw_v" ~ "rwDDM v",
        Indice == "rw_z" ~ "rwDDM z",
      )
    ) %>%
    dplyr::mutate(
      Indice = factor(
        Indice, levels = c(
          "RT", "ACC", "d Prime", "Efficiency",
          "ezDDM v", "ezDDM z", "rwDDM v", "rwDDM z"
        )
      ),
        Target = factor(Target),
    ) %>%
    dplyr::select(
      Target, Indice, r, LLCI, ULCI, Paper_ID
    ) %>%
    dplyr::arrange(
      Target, Indice
    )

  # 保存生成的表格
  Path <- paste0("./mcshr_", Paper_ID, ".csv")
  write.csv(x = result, file = Path, row.names = FALSE)

}
```

```{r}
for (i in 35:36) {
  shl <- list(list(), list(), list(), list())

  gc()

  # First-Second
  shl[[1]] <- yukiSH::sh_tool(df.split = df[[i]], method = "fs", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session") # nolint
  # Odd-Even
  shl[[2]] <- yukiSH::sh_tool(df.split = df[[i]], method = "od", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session") # nolint
  # Permuted
  shl[[3]] <- yukiSH::sh_tool(df.split = df[[i]], method = "permuted", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session", iteration = 10, nc = 8) # nolint
  # Monte Carlo
  #shl[[4]] <- yukiSH::sh_tool(df.split = df[[i]], method = "mc", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session", iteration = 10, nc = 16) # nolint 

  lazy_nmshr(Target = t[[i]], Paper_ID = p[[i]], nc = 8)
  lazy_pershr(Target = t[[i]], Paper_ID = p[[i]], nc = 8)
  #lazy_mcshr(Target = t[[i]], Paper_ID = p[[i]], nc = 16)
}

rm(shl)
gc()
```




