---
title: "Untitled"
author: "yuki"
date: "2023-06-02"
output: html_document
---
```{r}
df_test <- df[[1]] %>%
  dplyr::filter(Subject == 6001 | Subject == 6002 | Subject == 6003 | Subject == 6004) 
```

```{r}
shl_test <- yukiSH::sh_tool(df.split = df_test, method = "mc",
                               sub = "Subject",
                               var1 = "Matching",
                               var2 = "Identity",
                               var3 = "Session",
                               iteration = 3, nc = 16
                               )
```

```{r}
SPE_half_1[[1]] <- SPE_half_1[[1]] %>%
  tidyr::unite(group, Subject, Matching, Identity, Session, sep = "_") %>%
  dplyr::mutate(group = factor(group))
```


```{r}
Start_Time <- Sys.time()
temp <- RWiener::wdm(SPE_half_1[[1]], xvar = "group", yvar = c("RT_sec", "ACC"))
End_Time <- Sys.time()
```


```{r}
result <- data.frame(temp$coefficients) %>%
  dplyr::mutate(group = rownames(.)) %>%
  tidyr::separate(group, into = c("Subject", "Matching", "Identity", "Session"), sep = "_") %>%
  tidyr::separate(Session, into = c("Session", "Indice"), sep = ":") %>%
  tidyr::pivot_wider(names_from = Indice,
                     values_from = temp.coefficients) %>%
  dplyr::mutate(a = alpha, t = tau, z = beta, v = delta,
                Subject = as.numeric(Subject),
                Matching = factor(Matching,
                                  levels = c("Matching", "Nonmatching")),
                Identity = factor(Identity,
                                  levels = c("Self", "Friend", "Stranger")),
                Session = as.character(Session)
                ) %>%
  dplyr::arrange(Subject, Matching, Identity, Session) %>%
  dplyr::select(Subject, Matching, Identity, Session, a, t, z, v)
```

```{r}
Start_Time <- Sys.time()
SPE_half_1 <- df_test %>%
  # RWiener::wdm 只识别lower upper
  dplyr::mutate(ACC = case_when(ACC == 0 ~ "lower",
                                ACC == 1 ~ "upper")) %>%
  # RWiener::wdm 只接受一个分组变量
  split(.$Subject) %>%
  # 执行wdm，然后将分割的结果重新组合
  base::lapply(., function(df) { 
    df <- df %>%
      tidyr::unite(group, Subject, Matching, Identity, Session, sep = "_") %>%
      dplyr::mutate(group = factor(group))
    ###############################Core Codes#################################
    temp <- RWiener::wdm(df, xvar = "group", yvar = c("RT_sec", "ACC"))
    ###############################Core Codes#################################
    result <- data.frame(temp$coefficients) %>%
      dplyr::mutate(group = rownames(.)) %>%
      tidyr::separate(group, into = c("Subject", "Matching", "Identity", "Session"), sep = "_") %>%
      tidyr::separate(Session, into = c("Session", "Indice"), sep = ":") %>%
      tidyr::pivot_wider(names_from = Indice,
                         values_from = temp.coefficients) %>%
      dplyr::mutate(a = alpha, t = tau, z = beta, v = delta,
                    Subject = as.numeric(Subject),
                    Matching = factor(Matching,
                                      levels = c("Matching", "Nonmatching")),
                    Identity = factor(Identity,
                                      levels = c("Self", "Friend", "Stranger")),
                    Session = as.character(Session)
                    ) %>%
      dplyr::arrange(Subject, Matching, Identity, Session) %>%
      dplyr::select(Subject, Matching, Identity, Session, a, t, z, v)
  return(result)
  }) %>%
  base::do.call(rbind, .)
End_Time <- Sys.time()
```

```{r}
df_rwddm <- nmshr_rwddm(list = shl[1:2], Target = "Friend", Paper_ID = "P0S1")
```


```{r}
Start_Time <- Sys.time()

SPE_half_1 <- shl_test[[1]][[1]] %>%
  # RWiener::wdm 只识别lower upper
  dplyr::mutate(ACC = case_when(ACC == 0 ~ "lower",
                                ACC == 1 ~ "upper")) %>%
  # RWiener::wdm 只接受一个分组变量
  split(.$Subject) %>%
  # 执行wdm，然后将分割的结果重新组合
  base::lapply(., function(df) { 
    df <- df %>%
      tidyr::unite(group, Subject, Matching, Identity, Session, sep = "_") %>%
      dplyr::mutate(group = factor(group))
    ###############################Core Codes#################################
    temp <- RWiener::wdm(df, xvar = "group", yvar = c("RT_sec", "ACC"))
    ###############################Core Codes#################################
    result <- data.frame(temp$coefficients) %>%
      dplyr::mutate(group = rownames(.)) %>%
      tidyr::separate(group, into = c("Subject", "Matching", "Identity", "Session"), sep = "_") %>%
      tidyr::separate(Session, into = c("Session", "Indice"), sep = ":") %>%
      tidyr::pivot_wider(names_from = Indice,
                         values_from = temp.coefficients) %>%
      dplyr::mutate(a = alpha, t = tau, z = beta, v = delta,
                    Subject = as.numeric(Subject),
                    Matching = factor(Matching,
                                      levels = c("Matching", "Nonmatching")),
                    Identity = factor(Identity,
                                      levels = c("Self", "Friend", "Stranger")),
                    Session = as.character(Session)
                    ) %>%
      dplyr::arrange(Subject, Matching, Identity, Session) %>%
      dplyr::select(Subject, Matching, Identity, Session, a, t, z, v)
  return(result)
  }) %>%
  base::do.call(rbind, .)

SPE_half_2 <- shl_test[[1]][[2]] %>%
  # RWiener::wdm 只识别lower upper
  dplyr::mutate(ACC = case_when(ACC == 0 ~ "lower",
                                ACC == 1 ~ "upper")) %>%
  # RWiener::wdm 只接受一个分组变量
  split(.$Subject) %>%
  # 执行wdm，然后将分割的结果重新组合
  base::lapply(., function(df) { 
    df <- df %>%
      tidyr::unite(group, Subject, Matching, Identity, Session, sep = "_") %>%
      dplyr::mutate(group = factor(group))
    ###############################Core Codes#################################
    temp <- RWiener::wdm(df, xvar = "group", yvar = c("RT_sec", "ACC"))
    ###############################Core Codes#################################
    result <- data.frame(temp$coefficients) %>%
      dplyr::mutate(group = rownames(.)) %>%
      tidyr::separate(group, into = c("Subject", "Matching", "Identity", "Session"), sep = "_") %>%
      tidyr::separate(Session, into = c("Session", "Indice"), sep = ":") %>%
      tidyr::pivot_wider(names_from = Indice,
                         values_from = temp.coefficients) %>%
      dplyr::mutate(a = alpha, t = tau, z = beta, v = delta,
                    Subject = as.numeric(Subject),
                    Matching = factor(Matching,
                                      levels = c("Matching", "Nonmatching")),
                    Identity = factor(Identity,
                                      levels = c("Self", "Friend", "Stranger")),
                    Session = as.character(Session)
                    ) %>%
      dplyr::arrange(Subject, Matching, Identity, Session) %>%
      dplyr::select(Subject, Matching, Identity, Session, a, t, z, v)
  return(result)
  }) %>%
  base::do.call(rbind, .)

End_Time <- Sys.time()
```

```{r}
cor(SPE_half_1$z, SPE_half_2$z)
```


```{r}
SPE_half_1_v <- SPE_half_1 %>%
  dplyr::select(Subject, Session, Matching, Identity, v) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = v) %>%
  dplyr::mutate(v_SPE_1 = Self - Friend) %>%
  dplyr::select(Subject, Session, v_SPE_1)

SPE_half_2_v <- SPE_half_2 %>%
  dplyr::select(Subject, Session, Matching, Identity, v) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = v) %>%
  dplyr::mutate(v_SPE_2 = Self - Friend) %>%
  dplyr::select(Subject, Session, v_SPE_2)
```

```{r}
df_cor_v <- SPE_half_1_v %>%
  dplyr::left_join(SPE_half_2_v, by = c("Subject", "Session")) %>%
  dplyr::filter(!is.na(v_SPE_1) & !is.na(v_SPE_2)) %>%
  dplyr::filter(is.finite(v_SPE_1) & is.finite(v_SPE_2))
```

```{r}
r_value_v <- cor(df_cor_v[,3], df_cor_v[,4], method = "pearson")
```

```{r}
j = 1
```

```{r}
#values_v <- data.frame()
values[j,1] <- "RW: v"
values[j,2] <- j
values[j,3] <- r_value_v[1]
values[j,4] <- "Friend"
values[j,5] <- "P0S1"
```

```{r}
SPE_half_1_z <- SPE_half_1 %>%
  dplyr::select(Subject, Session, Matching, Identity, z) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = z) %>%
  dplyr::mutate(z_SPE_1 = Self - Friend) %>%
  dplyr::select(Subject, Session, z_SPE_1)

SPE_half_2_z <- SPE_half_2 %>%
  dplyr::select(Subject, Session, Matching, Identity, z) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = z) %>%
  dplyr::mutate(z_SPE_2 = Self - Friend) %>%
  dplyr::select(Subject, Session, z_SPE_2)
```

```{r}
df_cor_z <- SPE_half_1_z %>%
  dplyr::left_join(SPE_half_2_z, by = c("Subject", "Session")) %>%
  dplyr::filter(!is.na(z_SPE_1) & !is.na(z_SPE_2)) %>%
  dplyr::filter(is.finite(z_SPE_1) & is.finite(z_SPE_2))
```

```{r}
r_value_z <- cor(df_cor_z[,3], df_cor_z[,4], method = "pearson")
```

```{r}
#values_z <- data.frame()
values[j+1,1] <- "RW: z"
values[j+1,2] <- j
values[j+1,3] <- r_value_z[1]
values[j+1,4] <- "Friend"
values[j+1,5] <- "P0S1"
```

```{r}
values <- data.frame()
colnames(values) <- c("X1", "X2", "X3", "V4", "V5")
```

```{r}
df.rwddm <- mcshr_rwddm(list = shl_test, Target = "Friend", Paper_ID = "P0S1")
```

```{r}
df.rwddm <- icc_rwddm(df = df_test, Target = "Friend")
```

