---
title: "test"
author: "yuki"
date: "2023-06-03"
output: html_document
---
```{r}
df_test <- df[[1]] 
```

```{r}
unique(df[[1]]$Subject)
```


```{r}
shl_test <- list()
```

# First-Second
```{r First-Second SHR}
shl_test[[1]] <- yukiSH::sh_tool(df.split = df_test, method = "fs", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session")
```
# Odd-Even
```{r Odd-Even SHR}
shl_test[[2]] <- yukiSH::sh_tool(df.split = df_test, method = "od", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session")
```
# Permuted
```{r Permuted SHR}
shl_test[[3]] <- yukiSH::sh_tool(df.split = df_test, method = "permuted", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session")
```
# Monte Carlo
```{r}
shl_test[[4]] <- yukiSH::sh_tool(df.split = df_test, method = "mc", sub = "Subject", var1 = "Matching", var2 = "Identity", var3 = "Session",
                                 iteration = 16, nc = 16)
```

```{r}
df_nm_rwddm <- nmshr_rwddm(list = shl_test[1:3], Target = "Friend", Paper_ID = "P0S1")
```

```{r}
Start_Time <- Sys.time()
df_mc_rwddm <- mcshr_rwddm(list = shl_test[[4]], Target = "Friend", Paper_ID = "P0S1")
End_Time <- Sys.time()
```

```{r}
new_list <- list()
for (i in 1:5) {
  new_list[[i]] <- list(shl_test[[4]][[2*i-1]], shl_test[[4]][[2*i]])
}
```

```{r}
# 创建一个空的数据框
result_df <- data.frame()

# 循环遍历new_list中的每个元素
for (i in 1:length(new_list)) {
  # 调用函数并得到数据框
  df_mc_rwddm <- mcshr_rwddm_test(list = new_list[[i]], Target = "Friend", Paper_ID = "P0S1")
  
  # 将结果添加到空的数据框中
  result_df <- rbind(result_df, df_mc_rwddm)
}

# 打印合并后的数据框
print(result_df)
```

```{r}
SPE_half_1 <- shl_test[[4]][[1]][[1]] %>%
  # RWiener::wdm 只识别lower upper
  dplyr::mutate(ACC = case_when(ACC == 0 ~ "lower",
                                ACC == 1 ~ "upper")) %>%
  # RWiener::wdm 只接受一个分组变量
  split(.$Subject) %>%
  # 执行wdm，然后将分割的结果重新组合
  base::lapply(., function(df) {
    df <- df %>%
      tidyr::unite(group, Subject, Matching, Identity, Session, sep = "_") %>%
      dplyr::mutate(group = factor(group))
    ###############################Core Codes#################################
    temp <- RWiener::wdm(df, xvar = "group", yvar = c("RT_sec", "ACC"))
    ###############################Core Codes#################################
    result <- data.frame(temp$coefficients) %>%
      dplyr::mutate(group = rownames(.)) %>%
      tidyr::separate(group, into = c("Subject", "Matching", "Identity", "Session"), sep = "_") %>%
      tidyr::separate(Session, into = c("Session", "Indice"), sep = ":") %>%
      tidyr::pivot_wider(names_from = Indice,
                         values_from = temp.coefficients) %>%
      dplyr::mutate(a = alpha, t = tau, z = beta, v = delta,
                    Subject = as.numeric(Subject),
                    Matching = factor(Matching,
                                      levels = c("Matching", "Nonmatching")),
                    Identity = factor(Identity,
                                      levels = c("Self", "Friend", "Stranger")),
                    Session = as.character(Session)
      ) %>%
      dplyr::arrange(Subject, Matching, Identity, Session) %>%
      dplyr::select(Subject, Matching, Identity, Session, a, t, z, v)
    return(result)
  }) %>%
  base::do.call(rbind, .)

SPE_half_2 <- shl_test[[4]][[1]][[2]] %>%
  # RWiener::wdm 只识别lower upper
  dplyr::mutate(ACC = case_when(ACC == 0 ~ "lower",
                                ACC == 1 ~ "upper")) %>%
  # RWiener::wdm 只接受一个分组变量
  split(.$Subject) %>%
  # 执行wdm，然后将分割的结果重新组合
  base::lapply(., function(df) {
    df <- df %>%
      tidyr::unite(group, Subject, Matching, Identity, Session, sep = "_") %>%
      dplyr::mutate(group = factor(group))
    ###############################Core Codes#################################
    temp <- RWiener::wdm(df, xvar = "group", yvar = c("RT_sec", "ACC"))
    ###############################Core Codes#################################
    result <- data.frame(temp$coefficients) %>%
      dplyr::mutate(group = rownames(.)) %>%
      tidyr::separate(group, into = c("Subject", "Matching", "Identity", "Session"), sep = "_") %>%
      tidyr::separate(Session, into = c("Session", "Indice"), sep = ":") %>%
      tidyr::pivot_wider(names_from = Indice,
                         values_from = temp.coefficients) %>%
      dplyr::mutate(a = alpha, t = tau, z = beta, v = delta,
                    Subject = as.numeric(Subject),
                    Matching = factor(Matching,
                                      levels = c("Matching", "Nonmatching")),
                    Identity = factor(Identity,
                                      levels = c("Self", "Friend", "Stranger")),
                    Session = as.character(Session)
      ) %>%
      dplyr::arrange(Subject, Matching, Identity, Session) %>%
      dplyr::select(Subject, Matching, Identity, Session, a, t, z, v)
    return(result)
  }) %>%
  base::do.call(rbind, .)

################################################################################

SPE_half_1_v <- SPE_half_1 %>%
  dplyr::select(Subject, Session, Matching, Identity, v) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = v) %>%
  dplyr::mutate(v_SPE_1 = Self - Friend) %>%
  dplyr::select(Subject, Session, v_SPE_1)

SPE_half_2_v <- SPE_half_2 %>%
  dplyr::select(Subject, Session, Matching, Identity, v) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = v) %>%
  dplyr::mutate(v_SPE_2 = Self - Friend) %>%
  dplyr::select(Subject, Session, v_SPE_2)

df_cor_v <- SPE_half_1_v %>%
  dplyr::left_join(SPE_half_2_v, by = c("Subject", "Session")) %>%
  dplyr::filter(!is.na(v_SPE_1) & !is.na(v_SPE_2)) %>%
  dplyr::filter(is.finite(v_SPE_1) & is.finite(v_SPE_2))

r_values_v <- cor(df_cor_v[,3], df_cor_v[,4], method = "pearson")

################################################################################

SPE_half_1_z <- SPE_half_1 %>%
  dplyr::select(Subject, Session, Matching, Identity, z) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = z) %>%
  dplyr::mutate(z_SPE_1 = Self - Friend) %>%
  dplyr::select(Subject, Session, z_SPE_1)

SPE_half_2_z <- SPE_half_2 %>%
  dplyr::select(Subject, Session, Matching, Identity, z) %>%
  dplyr::filter(Matching == "Matching") %>%
  tidyr::pivot_wider(names_from = Identity,
                     values_from = z) %>%
  dplyr::mutate(z_SPE_2 = Self - Friend) %>%
  dplyr::select(Subject, Session, z_SPE_2)

df_cor_z <- SPE_half_1_z %>%
  dplyr::left_join(SPE_half_2_z, by = c("Subject", "Session")) %>%
  dplyr::filter(!is.na(z_SPE_1) & !is.na(z_SPE_2)) %>%
  dplyr::filter(is.finite(z_SPE_1) & is.finite(z_SPE_2))

r_values_z <- cor(df_cor_z[,3], df_cor_z[,4], method = "pearson")

df_result <- data.frame(v = r_values_v[,1], z = r_values_z[,1])
```


```{r}
Start_Time <- Sys.time()
registerDoParallel(cores = 16)

# 使用foreach循环并行执行迭代
result_df <- foreach(i = 1:length(shl_test[[4]]), .combine = rbind, .packages = c("dplyr", "tidyr", "RWiener")) %dopar% {
  
  # 调用函数并得到数据框
  df_mc_rwddm <- mcshr_rwddm_test(list = shl_test[[4]][[i]], Target = "Friend", Paper_ID = "P0S1")
  
  # 返回结果
  df_mc_rwddm
}

# 停止并行计算
stopImplicitCluster()
End_Time <- Sys.time()
```

